// Package vision provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package vision

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for DetectionClassName.
const (
	GreenSign DetectionClassName = "green_sign"
	RedSign   DetectionClassName = "red_sign"
)

// Valid indicates whether the value is a known member of the DetectionClassName enum.
func (e DetectionClassName) Valid() bool {
	switch e {
	case GreenSign:
		return true
	case RedSign:
		return true
	default:
		return false
	}
}

// Annotation defines model for Annotation.
type Annotation struct {
	Bbox      BoundingBox             `json:"bbox"`
	ClassName string                  `json:"class_name"`
	CreatedAt time.Time               `json:"created_at"`
	Id        openapi_types.UUID      `json:"id"`
	ImageId   openapi_types.UUID      `json:"image_id"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	UpdatedAt *time.Time              `json:"updated_at,omitempty"`
}

// BoundingBox defines model for BoundingBox.
type BoundingBox struct {
	// Height Normalized height [0, 1]
	Height float64 `json:"height"`

	// Width Normalized width [0, 1]
	Width float64 `json:"width"`

	// X Normalized center X [0, 1]
	X float64 `json:"x"`

	// Y Normalized center Y [0, 1]
	Y float64 `json:"y"`
}

// CreateAnnotationRequest defines model for CreateAnnotationRequest.
type CreateAnnotationRequest struct {
	Bbox      BoundingBox             `json:"bbox"`
	ClassName string                  `binding:"required" json:"class_name"`
	ImageId   openapi_types.UUID      `binding:"required,uuid" json:"image_id"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
}

// Detection defines model for Detection.
type Detection struct {
	Bbox       BoundingBox         `json:"bbox"`
	ClassName  DetectionClassName  `json:"class_name"`
	Confidence float32             `json:"confidence"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Timestamp  *time.Time          `json:"timestamp,omitempty"`
}

// DetectionClassName defines model for Detection.ClassName.
type DetectionClassName string

// DetectionFrame defines model for DetectionFrame.
type DetectionFrame struct {
	Detections      []Detection `json:"detections"`
	ImageHeight     *int        `json:"image_height,omitempty"`
	ImageWidth      *int        `json:"image_width,omitempty"`
	InferenceTimeMs float32     `json:"inference_time_ms"`
	NpuFps          *float32    `json:"npu_fps,omitempty"`
	Timestamp       time.Time   `json:"timestamp"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ModelInfo defines model for ModelInfo.
type ModelInfo struct {
	Classes             []string `json:"classes"`
	ConfidenceThreshold *float32 `json:"confidence_threshold,omitempty"`

	// InputShape Model input shape (C, H, W) or (H, W, C)
	InputShape   []int    `json:"input_shape"`
	IouThreshold *float32 `json:"iou_threshold,omitempty"`
	Name         string   `json:"name"`
	Version      string   `json:"version"`
}

// PipelineStatus defines model for PipelineStatus.
type PipelineStatus struct {
	Active          bool       `json:"active"`
	Error           *string    `json:"error,omitempty"`
	Fps             float32    `json:"fps"`
	FramesProcessed *int       `json:"frames_processed,omitempty"`
	LastInference   *time.Time `json:"last_inference,omitempty"`
	ModelLoaded     bool       `json:"model_loaded"`
	ModelName       *string    `json:"model_name,omitempty"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// SetModelRequest defines model for SetModelRequest.
type SetModelRequest struct {
	Name    string  `json:"name"`
	Version *string `json:"version,omitempty"`
}

// UpdateAnnotationRequest defines model for UpdateAnnotationRequest.
type UpdateAnnotationRequest struct {
	Bbox      *BoundingBox `json:"bbox,omitempty"`
	ClassName *string      `json:"class_name,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ProblemDetails

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListDetectionsParams defines parameters for ListDetections.
type ListDetectionsParams struct {
	// Limit Maximum number of detections
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// ConfidenceMin Minimum confidence filter
	ConfidenceMin *float32 `form:"confidence_min,omitempty" json:"confidence_min,omitempty"`
}

// CreateAnnotationJSONRequestBody defines body for CreateAnnotation for application/json ContentType.
type CreateAnnotationJSONRequestBody = CreateAnnotationRequest

// UpdateAnnotationJSONRequestBody defines body for UpdateAnnotation for application/json ContentType.
type UpdateAnnotationJSONRequestBody = UpdateAnnotationRequest

// SetActiveModelJSONRequestBody defines body for SetActiveModel for application/json ContentType.
type SetActiveModelJSONRequestBody = SetModelRequest
