// Hand-maintained copy of platform/shared/config/robot.toml's values. Previously
// generated by `simgen generate-robot-constants` (removed 2026-09-03, unused and
// its output was broken); edit this file directly and keep it in sync with robot.toml
// -- see platform/robot/docs/robot-physical-constants.md.

package simconfig

// Robot chassis dimensions (meters). vTitan + Ackermann.
const (
	RobotLength      = 0.3
	RobotWidth       = 0.194
	RobotHeight      = 0.1
	RobotWheelbase   = 0.19
	RobotTrackWidth  = 0.1675
	RobotWheelRadius = 0.035
	RobotWheelWidth  = 0.025
	// RobotMaxSteering is the ROAD-WHEEL angle at full lock, derived from the
	// servo's travel through the linkage rather than declared.
	RobotMaxSteering      = 0.9599310885968813
	RobotServoMaxAngleDeg = 90.0               // SERVO degrees at full travel
	RobotMaxWheelAngleDeg = 55.0               // bench-measured road-wheel degrees at full servo lock
	RobotLinkageRatio     = 0.6111111111111112 // road-wheel degrees per servo degree, derived from the two above
	RobotChassisMass      = 1.3                // kg, body alone
	RobotWheelMass        = 0.05               // kg per wheel

	// Drive motor limits. Hard ceilings the kinematics clamp to, not tuning.
	RobotMaxSpeedMPS    = 0.156
	RobotMaxAccelMPS2   = 2.0
	RobotRearSteerRatio = 1.0 // 1.0 = counter-phase four-wheel steering

	// RobotLidarMountXOffset: chassis_length/2 - the lidar mesh's own radius (0.0278,
	// matching wro_robot.urdf.xacro's lidar_link visual/collision cylinder) — the C1
	// mounted flush with the front edge, centered left/right, upside-down.
	RobotLidarMountXOffset = 0.1222
	// RobotLidarMountZOffset: LIDAR sits above the chassis top by this much;
	// add RobotHeight for the LIDAR's absolute mount z.
	RobotLidarMountZOffset = 0.02
	// RobotLidarInverted: single source of truth for the upside-down mount.
	// Drives BOTH the sllidar_ros2 driver's own inverted launch parameter AND
	// a mandatory 180deg yaw rotation wherever raw /scan angles are consumed --
	// the two are consequences of the same physical fact, not independent
	// settings. Re-verify against a known object at chassis front/back/left/
	// right after any remount or cable work; don't assume the old value holds.
	RobotLidarInverted = true
	// RobotLidarMountYawOffsetDeg: residual yaw miscalibration NOT explained by
	// RobotLidarInverted's 180deg -- added on top of it, not a replacement.
	RobotLidarMountYawOffsetDeg = 0.0

	// IMU mounted near the chassis floor.
	RobotImuMountZOffset = 0.01

	// Camera mounted directly over the LIDAR, tilted down.
	RobotCameraMountXOffset = 0.1222
	RobotCameraMountZOffset = 0.16
	RobotCameraPitchRad     = 0.5236 // ~30°, tilted down
)
