// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: autoannotator/v1/compute.proto

// Package autoannotator.v1 is the language-neutral contract between the Go
// orchestration API (gRPC client) and the Python compute workers (gRPC servers).
// The workers own all ML compute (SAM inference, albumentations augmentation,
// Ultralytics YOLO training); the Go API owns the SQLite manifest DB.
//
// This is the single source of truth shared by both services. Each side vendors
// its own generated stubs: Go in api/domain/compute/grpc/pb, Python in
// ml-service/src/grpc_server/pb.

package computev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SegmentationService_Segment_FullMethodName = "/autoannotator.v1.SegmentationService/Segment"
)

// SegmentationServiceClient is the client API for SegmentationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SAM point-prompted segmentation. Stateless: every call carries all points.
type SegmentationServiceClient interface {
	Segment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
}

type segmentationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentationServiceClient(cc grpc.ClientConnInterface) SegmentationServiceClient {
	return &segmentationServiceClient{cc}
}

func (c *segmentationServiceClient) Segment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, SegmentationService_Segment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SegmentationServiceServer is the server API for SegmentationService service.
// All implementations must embed UnimplementedSegmentationServiceServer
// for forward compatibility.
//
// SAM point-prompted segmentation. Stateless: every call carries all points.
type SegmentationServiceServer interface {
	Segment(context.Context, *SegmentRequest) (*SegmentResponse, error)
	mustEmbedUnimplementedSegmentationServiceServer()
}

// UnimplementedSegmentationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSegmentationServiceServer struct{}

func (UnimplementedSegmentationServiceServer) Segment(context.Context, *SegmentRequest) (*SegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Segment not implemented")
}
func (UnimplementedSegmentationServiceServer) mustEmbedUnimplementedSegmentationServiceServer() {}
func (UnimplementedSegmentationServiceServer) testEmbeddedByValue()                             {}

// UnsafeSegmentationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentationServiceServer will
// result in compilation errors.
type UnsafeSegmentationServiceServer interface {
	mustEmbedUnimplementedSegmentationServiceServer()
}

func RegisterSegmentationServiceServer(s grpc.ServiceRegistrar, srv SegmentationServiceServer) {
	// If the following call panics, it indicates UnimplementedSegmentationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SegmentationService_ServiceDesc, srv)
}

func _SegmentationService_Segment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentationServiceServer).Segment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentationService_Segment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentationServiceServer).Segment(ctx, req.(*SegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SegmentationService_ServiceDesc is the grpc.ServiceDesc for SegmentationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SegmentationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoannotator.v1.SegmentationService",
	HandlerType: (*SegmentationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Segment",
			Handler:    _SegmentationService_Segment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autoannotator/v1/compute.proto",
}

const (
	AugmentationService_RunAugmentation_FullMethodName = "/autoannotator.v1.AugmentationService/RunAugmentation"
)

// AugmentationServiceClient is the client API for AugmentationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AugmentationServiceClient interface {
	RunAugmentation(ctx context.Context, in *AugmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobProgress], error)
}

type augmentationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAugmentationServiceClient(cc grpc.ClientConnInterface) AugmentationServiceClient {
	return &augmentationServiceClient{cc}
}

func (c *augmentationServiceClient) RunAugmentation(ctx context.Context, in *AugmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AugmentationService_ServiceDesc.Streams[0], AugmentationService_RunAugmentation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AugmentRequest, JobProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AugmentationService_RunAugmentationClient = grpc.ServerStreamingClient[JobProgress]

// AugmentationServiceServer is the server API for AugmentationService service.
// All implementations must embed UnimplementedAugmentationServiceServer
// for forward compatibility.
type AugmentationServiceServer interface {
	RunAugmentation(*AugmentRequest, grpc.ServerStreamingServer[JobProgress]) error
	mustEmbedUnimplementedAugmentationServiceServer()
}

// UnimplementedAugmentationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAugmentationServiceServer struct{}

func (UnimplementedAugmentationServiceServer) RunAugmentation(*AugmentRequest, grpc.ServerStreamingServer[JobProgress]) error {
	return status.Error(codes.Unimplemented, "method RunAugmentation not implemented")
}
func (UnimplementedAugmentationServiceServer) mustEmbedUnimplementedAugmentationServiceServer() {}
func (UnimplementedAugmentationServiceServer) testEmbeddedByValue()                             {}

// UnsafeAugmentationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AugmentationServiceServer will
// result in compilation errors.
type UnsafeAugmentationServiceServer interface {
	mustEmbedUnimplementedAugmentationServiceServer()
}

func RegisterAugmentationServiceServer(s grpc.ServiceRegistrar, srv AugmentationServiceServer) {
	// If the following call panics, it indicates UnimplementedAugmentationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AugmentationService_ServiceDesc, srv)
}

func _AugmentationService_RunAugmentation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AugmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AugmentationServiceServer).RunAugmentation(m, &grpc.GenericServerStream[AugmentRequest, JobProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AugmentationService_RunAugmentationServer = grpc.ServerStreamingServer[JobProgress]

// AugmentationService_ServiceDesc is the grpc.ServiceDesc for AugmentationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AugmentationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoannotator.v1.AugmentationService",
	HandlerType: (*AugmentationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunAugmentation",
			Handler:       _AugmentationService_RunAugmentation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "autoannotator/v1/compute.proto",
}

const (
	TrainingService_RunTraining_FullMethodName = "/autoannotator.v1.TrainingService/RunTraining"
)

// TrainingServiceClient is the client API for TrainingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingServiceClient interface {
	RunTraining(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobProgress], error)
}

type trainingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingServiceClient(cc grpc.ClientConnInterface) TrainingServiceClient {
	return &trainingServiceClient{cc}
}

func (c *trainingServiceClient) RunTraining(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrainingService_ServiceDesc.Streams[0], TrainingService_RunTraining_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrainRequest, JobProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrainingService_RunTrainingClient = grpc.ServerStreamingClient[JobProgress]

// TrainingServiceServer is the server API for TrainingService service.
// All implementations must embed UnimplementedTrainingServiceServer
// for forward compatibility.
type TrainingServiceServer interface {
	RunTraining(*TrainRequest, grpc.ServerStreamingServer[JobProgress]) error
	mustEmbedUnimplementedTrainingServiceServer()
}

// UnimplementedTrainingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainingServiceServer struct{}

func (UnimplementedTrainingServiceServer) RunTraining(*TrainRequest, grpc.ServerStreamingServer[JobProgress]) error {
	return status.Error(codes.Unimplemented, "method RunTraining not implemented")
}
func (UnimplementedTrainingServiceServer) mustEmbedUnimplementedTrainingServiceServer() {}
func (UnimplementedTrainingServiceServer) testEmbeddedByValue()                         {}

// UnsafeTrainingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingServiceServer will
// result in compilation errors.
type UnsafeTrainingServiceServer interface {
	mustEmbedUnimplementedTrainingServiceServer()
}

func RegisterTrainingServiceServer(s grpc.ServiceRegistrar, srv TrainingServiceServer) {
	// If the following call panics, it indicates UnimplementedTrainingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrainingService_ServiceDesc, srv)
}

func _TrainingService_RunTraining_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrainingServiceServer).RunTraining(m, &grpc.GenericServerStream[TrainRequest, JobProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrainingService_RunTrainingServer = grpc.ServerStreamingServer[JobProgress]

// TrainingService_ServiceDesc is the grpc.ServiceDesc for TrainingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autoannotator.v1.TrainingService",
	HandlerType: (*TrainingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunTraining",
			Handler:       _TrainingService_RunTraining_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "autoannotator/v1/compute.proto",
}
