#:schema ../../../model/hardware/motors/motors.schema.json
# Motor configuration. Rationale: adr:0076-drivetrain-and-steering-hardware

[steering]
offset = 0.0
left_limit_angle = -83.0
right_limit_angle = 22.0
center_angle = -30.0
centering_speed = 20
turning_speed = 30
reversed = false

[drive]
reversed = false
encoder_reversed = true
min_speed = -100
max_speed = 100
speed_scale = 30.0
default_speed = 15
test_duration = 1.5
