// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/actuation/v1/motor_status.proto

package actuationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MotorStatus_State int32

const (
	MotorStatus_STATE_UNSPECIFIED MotorStatus_State = 0
	MotorStatus_STATE_IDLE        MotorStatus_State = 1
	MotorStatus_STATE_RUNNING     MotorStatus_State = 2
	MotorStatus_STATE_FAULT       MotorStatus_State = 3
	MotorStatus_STATE_ESTOP       MotorStatus_State = 4
)

// Enum value maps for MotorStatus_State.
var (
	MotorStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_IDLE",
		2: "STATE_RUNNING",
		3: "STATE_FAULT",
		4: "STATE_ESTOP",
	}
	MotorStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_IDLE":        1,
		"STATE_RUNNING":     2,
		"STATE_FAULT":       3,
		"STATE_ESTOP":       4,
	}
)

func (x MotorStatus_State) Enum() *MotorStatus_State {
	p := new(MotorStatus_State)
	*p = x
	return p
}

func (x MotorStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotorStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_actuation_v1_motor_status_proto_enumTypes[0].Descriptor()
}

func (MotorStatus_State) Type() protoreflect.EnumType {
	return &file_vtitan_actuation_v1_motor_status_proto_enumTypes[0]
}

func (x MotorStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotorStatus_State.Descriptor instead.
func (MotorStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_actuation_v1_motor_status_proto_rawDescGZIP(), []int{0, 0}
}

// MotorStatus is the Go-stack replacement for the current std_msgs/String
// status topic published by the BTS7960 motor node. Published on the
// `vtitan.actuation.v1.motor_status` NATS subject.
type MotorStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replaces ROS2 Header: stamp + frame_id.
	Stamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FrameId string                 `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	State   MotorStatus_State      `protobuf:"varint,3,opt,name=state,proto3,enum=vtitan.actuation.v1.MotorStatus_State" json:"state,omitempty"`
	// Free-form fault/diagnostic detail, empty when state is not FAULT.
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// Measured duty cycle currently applied, signed [-1.0, 1.0].
	DutyCycle float32 `protobuf:"fixed32,5,opt,name=duty_cycle,json=dutyCycle,proto3" json:"duty_cycle,omitempty"`
	// Measured wheel speed from the encoder [m/s].
	MeasuredSpeed float32 `protobuf:"fixed32,6,opt,name=measured_speed,json=measuredSpeed,proto3" json:"measured_speed,omitempty"`
	// Milliseconds since the last accepted AckermannCmd — mirrors the
	// deadline watchdog described in go-migration-plan.md.
	CommandAgeMs  uint32 `protobuf:"varint,7,opt,name=command_age_ms,json=commandAgeMs,proto3" json:"command_age_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotorStatus) Reset() {
	*x = MotorStatus{}
	mi := &file_vtitan_actuation_v1_motor_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorStatus) ProtoMessage() {}

func (x *MotorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_actuation_v1_motor_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorStatus.ProtoReflect.Descriptor instead.
func (*MotorStatus) Descriptor() ([]byte, []int) {
	return file_vtitan_actuation_v1_motor_status_proto_rawDescGZIP(), []int{0}
}

func (x *MotorStatus) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *MotorStatus) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *MotorStatus) GetState() MotorStatus_State {
	if x != nil {
		return x.State
	}
	return MotorStatus_STATE_UNSPECIFIED
}

func (x *MotorStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *MotorStatus) GetDutyCycle() float32 {
	if x != nil {
		return x.DutyCycle
	}
	return 0
}

func (x *MotorStatus) GetMeasuredSpeed() float32 {
	if x != nil {
		return x.MeasuredSpeed
	}
	return 0
}

func (x *MotorStatus) GetCommandAgeMs() uint32 {
	if x != nil {
		return x.CommandAgeMs
	}
	return 0
}

var File_vtitan_actuation_v1_motor_status_proto protoreflect.FileDescriptor

const file_vtitan_actuation_v1_motor_status_proto_rawDesc = "" +
	"\n" +
	"&vtitan/actuation/v1/motor_status.proto\x12\x13vtitan.actuation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x03\n" +
	"\vMotorStatus\x120\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05stamp\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\tR\aframeId\x12<\n" +
	"\x05state\x18\x03 \x01(\x0e2&.vtitan.actuation.v1.MotorStatus.StateR\x05state\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"duty_cycle\x18\x05 \x01(\x02R\tdutyCycle\x12%\n" +
	"\x0emeasured_speed\x18\x06 \x01(\x02R\rmeasuredSpeed\x12$\n" +
	"\x0ecommand_age_ms\x18\a \x01(\rR\fcommandAgeMs\"c\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x02\x12\x0f\n" +
	"\vSTATE_FAULT\x10\x03\x12\x0f\n" +
	"\vSTATE_ESTOP\x10\x04BFZDgithub.com/teamvoltimor/vtitan/src/go/internal/schema/pb/actuationv1b\x06proto3"

var (
	file_vtitan_actuation_v1_motor_status_proto_rawDescOnce sync.Once
	file_vtitan_actuation_v1_motor_status_proto_rawDescData []byte
)

func file_vtitan_actuation_v1_motor_status_proto_rawDescGZIP() []byte {
	file_vtitan_actuation_v1_motor_status_proto_rawDescOnce.Do(func() {
		file_vtitan_actuation_v1_motor_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_actuation_v1_motor_status_proto_rawDesc), len(file_vtitan_actuation_v1_motor_status_proto_rawDesc)))
	})
	return file_vtitan_actuation_v1_motor_status_proto_rawDescData
}

var file_vtitan_actuation_v1_motor_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vtitan_actuation_v1_motor_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_actuation_v1_motor_status_proto_goTypes = []any{
	(MotorStatus_State)(0),        // 0: vtitan.actuation.v1.MotorStatus.State
	(*MotorStatus)(nil),           // 1: vtitan.actuation.v1.MotorStatus
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_vtitan_actuation_v1_motor_status_proto_depIdxs = []int32{
	2, // 0: vtitan.actuation.v1.MotorStatus.stamp:type_name -> google.protobuf.Timestamp
	0, // 1: vtitan.actuation.v1.MotorStatus.state:type_name -> vtitan.actuation.v1.MotorStatus.State
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vtitan_actuation_v1_motor_status_proto_init() }
func file_vtitan_actuation_v1_motor_status_proto_init() {
	if File_vtitan_actuation_v1_motor_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_actuation_v1_motor_status_proto_rawDesc), len(file_vtitan_actuation_v1_motor_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_actuation_v1_motor_status_proto_goTypes,
		DependencyIndexes: file_vtitan_actuation_v1_motor_status_proto_depIdxs,
		EnumInfos:         file_vtitan_actuation_v1_motor_status_proto_enumTypes,
		MessageInfos:      file_vtitan_actuation_v1_motor_status_proto_msgTypes,
	}.Build()
	File_vtitan_actuation_v1_motor_status_proto = out.File
	file_vtitan_actuation_v1_motor_status_proto_goTypes = nil
	file_vtitan_actuation_v1_motor_status_proto_depIdxs = nil
}
