[tools]
pnpm = "11.11.0"
task = "3.52.0"
uv = "0.11.28"
pixi = "0.72.2"
buf = "1.71.0"
biome = "2.5.3"
sqlc = "1.31.1"
golangci-lint = "2.12.2"
"go:golang.org/x/tools/cmd/goimports" = "0.48.0"
"ubi:dkorunic/betteralign" = "0.13.0"
"aqua:pressly/goose" = "3.27.2"
