// Package telemetry provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package telemetry

import (
	"time"
)

// Defines values for TelemetryMetricsNodeHealth.
const (
	NODEHEALTHNOMINAL     TelemetryMetricsNodeHealth = "NODE_HEALTH_NOMINAL"
	NODEHEALTHREPLANNING  TelemetryMetricsNodeHealth = "NODE_HEALTH_REPLANNING"
	NODEHEALTHUNSPECIFIED TelemetryMetricsNodeHealth = "NODE_HEALTH_UNSPECIFIED"
	NODEHEALTHWATCHDOG    TelemetryMetricsNodeHealth = "NODE_HEALTH_WATCHDOG"
)

// Valid indicates whether the value is a known member of the TelemetryMetricsNodeHealth enum.
func (e TelemetryMetricsNodeHealth) Valid() bool {
	switch e {
	case NODEHEALTHNOMINAL:
		return true
	case NODEHEALTHREPLANNING:
		return true
	case NODEHEALTHUNSPECIFIED:
		return true
	case NODEHEALTHWATCHDOG:
		return true
	default:
		return false
	}
}

// ConfigResponse defines model for ConfigResponse.
type ConfigResponse struct {
	Dev         bool   `json:"dev"`
	GrpcAddr    string `json:"grpc_addr"`
	HistorySize int    `json:"history_size"`
	HttpAddr    string `json:"http_addr"`
	MaxSessions int    `json:"max_sessions"`
	SessionsDir string `json:"sessions_dir"`
}

// Detection defines model for Detection.
type Detection struct {
	BboxH      float64 `json:"bbox_h"`
	BboxW      float64 `json:"bbox_w"`
	BboxX      float64 `json:"bbox_x"`
	BboxY      float64 `json:"bbox_y"`
	ClassName  string  `json:"class_name"`
	Confidence float64 `json:"confidence"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ImuData defines model for ImuData.
type ImuData struct {
	AngularVelocity    Position3D `json:"angular_velocity"`
	LinearAcceleration Position3D `json:"linear_acceleration"`
	OrientationW       float64    `json:"orientation_w"`
	OrientationX       float64    `json:"orientation_x"`
	OrientationY       float64    `json:"orientation_y"`
	OrientationZ       float64    `json:"orientation_z"`
}

// MotorState defines model for MotorState.
type MotorState struct {
	DriveSpeed      float64 `json:"drive_speed"`
	EncoderPosition int     `json:"encoder_position"`
	SteeringAngle   float64 `json:"steering_angle"`
}

// Position3D defines model for Position3D.
type Position3D struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

// ProblemDetails RFC 7807 Problem Details, emitted uniformly for every error response.
type ProblemDetails struct {
	// CorrelationId Matches the request_id in server logs for this response.
	CorrelationId *string `json:"correlation_id,omitempty"`
	Detail        *string `json:"detail,omitempty"`
	Instance      string  `json:"instance"`
	Status        int     `json:"status"`
	Title         string  `json:"title"`
	Type          string  `json:"type"`
}

// RobotSnapshot defines model for RobotSnapshot.
type RobotSnapshot struct {
	ImuData          *ImuData         `json:"imu_data,omitempty"`
	LidarPoints      *[]Position3D    `json:"lidar_points,omitempty"`
	Logs             *[]string        `json:"logs,omitempty"`
	Metrics          TelemetryMetrics `json:"metrics"`
	MissionName      string           `json:"mission_name"`
	MotorState       *MotorState      `json:"motor_state,omitempty"`
	PathHistory      *[]Position3D    `json:"path_history,omitempty"`
	RobotOrientation *float64         `json:"robot_orientation,omitempty"`
	RobotPosition    *Position3D      `json:"robot_position,omitempty"`
	Timestamp        time.Time        `json:"timestamp"`
	VisionDetections *[]Detection     `json:"vision_detections,omitempty"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	// CreatedAt ISO 8601 creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// EntryCount Number of snapshots in the session
	EntryCount int `json:"entry_count"`

	// SessionId Unique session identifier
	SessionId string `json:"session_id"`
}

// SpeedRequest defines model for SpeedRequest.
type SpeedRequest struct {
	// MaxLinearSpeed Maximum linear speed
	MaxLinearSpeed float64 `json:"maxLinearSpeed" validate:"required,gt=0"`
}

// SpeedUpdateResponse defines model for SpeedUpdateResponse.
type SpeedUpdateResponse struct {
	MaxLinearSpeed float64 `json:"maxLinearSpeed"`
	Status         string  `json:"status"`
}

// TelemetryMetrics defines model for TelemetryMetrics.
type TelemetryMetrics struct {
	Back              *float64                   `json:"back,omitempty"`
	CameraAvailable   bool                       `json:"camera_available"`
	Forward           *float64                   `json:"forward,omitempty"`
	ImuAvailable      bool                       `json:"imu_available"`
	Left              *float64                   `json:"left,omitempty"`
	LidarAvailable    bool                       `json:"lidar_available"`
	NodeHealth        TelemetryMetricsNodeHealth `json:"node_health"`
	OdometryAvailable bool                       `json:"odometry_available"`
	PointsCaptured    *int                       `json:"points_captured,omitempty"`
	RangeMax          *float64                   `json:"range_max,omitempty"`
	RangeMean         *float64                   `json:"range_mean,omitempty"`
	RangeMin          *float64                   `json:"range_min,omitempty"`
	Right             *float64                   `json:"right,omitempty"`
	Speed             *float64                   `json:"speed,omitempty"`
	Stage             *string                    `json:"stage,omitempty"`
	Timestamp         time.Time                  `json:"timestamp"`
}

// TelemetryMetricsNodeHealth defines model for TelemetryMetrics.NodeHealth.
type TelemetryMetricsNodeHealth string

// TopicUpdate defines model for TopicUpdate.
type TopicUpdate struct {
	Data         map[string]interface{} `json:"data"`
	MessageType  string                 `json:"message_type"`
	Timestamp    time.Time              `json:"timestamp"`
	TopicName    string                 `json:"topic_name"`
	UpdateRateHz float64                `json:"update_rate_hz"`
}

// TopicsSnapshot defines model for TopicsSnapshot.
type TopicsSnapshot struct {
	Timestamp time.Time     `json:"timestamp"`
	Topics    []TopicUpdate `json:"topics"`
}

// GetTelemetryHistoryParams defines parameters for GetTelemetryHistory.
type GetTelemetryHistoryParams struct {
	// Limit Maximum number of snapshots to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateRobotSpeedJSONRequestBody defines body for UpdateRobotSpeed for application/json ContentType.
type UpdateRobotSpeedJSONRequestBody = SpeedRequest
