// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package handlers

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GalleryItemStatus.
const (
	GalleryItemStatusDone    GalleryItemStatus = "done"
	GalleryItemStatusPending GalleryItemStatus = "pending"
	GalleryItemStatusSkipped GalleryItemStatus = "skipped"
)

// Valid indicates whether the value is a known member of the GalleryItemStatus enum.
func (e GalleryItemStatus) Valid() bool {
	switch e {
	case GalleryItemStatusDone:
		return true
	case GalleryItemStatusPending:
		return true
	case GalleryItemStatusSkipped:
		return true
	default:
		return false
	}
}

// Defines values for LivenessResponseStatus.
const (
	Ok LivenessResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivenessResponseStatus enum.
func (e LivenessResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ParentImageItemStatus.
const (
	ParentImageItemStatusDone    ParentImageItemStatus = "done"
	ParentImageItemStatusPending ParentImageItemStatus = "pending"
	ParentImageItemStatusSkipped ParentImageItemStatus = "skipped"
)

// Valid indicates whether the value is a known member of the ParentImageItemStatus enum.
func (e ParentImageItemStatus) Valid() bool {
	switch e {
	case ParentImageItemStatusDone:
		return true
	case ParentImageItemStatusPending:
		return true
	case ParentImageItemStatusSkipped:
		return true
	default:
		return false
	}
}

// Defines values for SaveAnnotationsRequestExportFormat.
const (
	Detection    SaveAnnotationsRequestExportFormat = "detection"
	Segmentation SaveAnnotationsRequestExportFormat = "segmentation"
)

// Valid indicates whether the value is a known member of the SaveAnnotationsRequestExportFormat enum.
func (e SaveAnnotationsRequestExportFormat) Valid() bool {
	switch e {
	case Detection:
		return true
	case Segmentation:
		return true
	default:
		return false
	}
}

// Defines values for SegmentationPointPointType.
const (
	Negative SegmentationPointPointType = "negative"
	Positive SegmentationPointPointType = "positive"
)

// Valid indicates whether the value is a known member of the SegmentationPointPointType enum.
func (e SegmentationPointPointType) Valid() bool {
	switch e {
	case Negative:
		return true
	case Positive:
		return true
	default:
		return false
	}
}

// Defines values for SegmentationResponseState.
const (
	Error   SegmentationResponseState = "error"
	Idle    SegmentationResponseState = "idle"
	Pending SegmentationResponseState = "pending"
	Ready   SegmentationResponseState = "ready"
)

// Valid indicates whether the value is a known member of the SegmentationResponseState enum.
func (e SegmentationResponseState) Valid() bool {
	switch e {
	case Error:
		return true
	case Idle:
		return true
	case Pending:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// AugmentRequest defines model for AugmentRequest.
type AugmentRequest struct {
	ImageIds         []int64 `json:"imageIds"`
	NumAugmentations int32   `json:"numAugmentations"`
}

// ClassItem defines model for ClassItem.
type ClassItem struct {
	Color string `json:"color"`
	Id    int64  `json:"id"`
	Name  string `json:"name"`
}

// DeleteImagesRequest defines model for DeleteImagesRequest.
type DeleteImagesRequest struct {
	ImageIds []int64 `json:"imageIds"`
}

// GalleryItem defines model for GalleryItem.
type GalleryItem struct {
	Annotations *[]Shape          `json:"annotations,omitempty"`
	Format      string            `json:"format"`
	Id          int64             `json:"id"`
	Label       string            `json:"label"`
	Src         string            `json:"src"`
	Status      GalleryItemStatus `json:"status"`
	ThumbSrc    string            `json:"thumbSrc"`

	// Updated Last update timestamp (RFC 3339 or empty)
	Updated string `json:"updated"`
}

// GalleryItemStatus defines model for GalleryItem.Status.
type GalleryItemStatus string

// GalleryResponse defines model for GalleryResponse.
type GalleryResponse struct {
	Items []GalleryItem `json:"items"`
	Stats GalleryStats  `json:"stats"`
}

// GalleryStats defines model for GalleryStats.
type GalleryStats struct {
	Done int `json:"done"`

	// Pct Completion percentage (0.0 - 100.0)
	Pct     float64 `json:"pct"`
	Pending int     `json:"pending"`
	Skipped int     `json:"skipped"`
	Total   int     `json:"total"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	DatabaseAccessible bool   `json:"databaseAccessible"`
	InferenceAvailable bool   `json:"inferenceAvailable"`
	Message            string `json:"message"`
	Ready              bool   `json:"ready"`
}

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	Message string `json:"message"`
	Running bool   `json:"running"`
}

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	Status LivenessResponseStatus `json:"status"`
}

// LivenessResponseStatus defines model for LivenessResponse.Status.
type LivenessResponseStatus string

// ModelItem defines model for ModelItem.
type ModelItem struct {
	Active       bool   `json:"active"`
	Available    bool   `json:"available"`
	Id           string `json:"id"`
	Label        string `json:"label"`
	ModelType    string `json:"modelType"`
	SupportsText bool   `json:"supportsText"`
}

// ParentImageItem defines model for ParentImageItem.
type ParentImageItem struct {
	AugCount int64                 `json:"aug_count"`
	Format   string                `json:"format"`
	Id       int64                 `json:"id"`
	Label    string                `json:"label"`
	Src      string                `json:"src"`
	Status   ParentImageItemStatus `json:"status"`

	// UpdatedAt Last update timestamp (RFC 3339 or empty)
	UpdatedAt string `json:"updated_at"`
}

// ParentImageItemStatus defines model for ParentImageItem.Status.
type ParentImageItemStatus string

// Point defines model for Point.
type Point struct {
	// X X coordinate (decimal string for precision)
	X string `binding:"required" json:"x"`

	// Y Y coordinate (decimal string for precision)
	Y string `binding:"required" json:"y"`
}

// SaveAnnotationsRequest defines model for SaveAnnotationsRequest.
type SaveAnnotationsRequest struct {
	ExportFormat SaveAnnotationsRequestExportFormat `json:"exportFormat"`
	ImageId      int64                              `json:"imageId"`
	Shapes       []Shape                            `json:"shapes"`
}

// SaveAnnotationsRequestExportFormat defines model for SaveAnnotationsRequest.ExportFormat.
type SaveAnnotationsRequestExportFormat string

// SegmentationPoint defines model for SegmentationPoint.
type SegmentationPoint struct {
	ClassName string                     `json:"className"`
	PointType SegmentationPointPointType `json:"pointType"`
	X         string                     `binding:"required" json:"x"`
	Y         string                     `binding:"required" json:"y"`
}

// SegmentationPointPointType defines model for SegmentationPoint.PointType.
type SegmentationPointPointType string

// SegmentationRequest defines model for SegmentationRequest.
type SegmentationRequest struct {
	ImageId int64               `json:"imageId"`
	Points  []SegmentationPoint `json:"points"`
}

// SegmentationResponse defines model for SegmentationResponse.
type SegmentationResponse struct {
	Message string                    `json:"message"`
	Shapes  []Shape                   `json:"shapes"`
	State   SegmentationResponseState `json:"state"`
}

// SegmentationResponseState defines model for SegmentationResponse.State.
type SegmentationResponseState string

// Shape defines model for Shape.
type Shape struct {
	// ClassName Annotation class/label
	ClassName string `json:"className"`

	// Id Unique annotation ID
	Id string `json:"id"`

	// Points Polygon vertices
	Points []Point `json:"points"`
}

// SkipRequest defines model for SkipRequest.
type SkipRequest struct {
	ImageId int64 `json:"imageId"`
}

// TrainRequest defines model for TrainRequest.
type TrainRequest struct {
	Batch     int32  `json:"batch"`
	Epochs    int32  `json:"epochs"`
	Imgsz     int32  `json:"imgsz"`
	ModelName string `json:"modelName"`
}

// UpsertClassRequest defines model for UpsertClassRequest.
type UpsertClassRequest struct {
	Color string `json:"color"`
	Name  string `json:"name"`
}

// ImportGalleryMultipartBody defines parameters for ImportGallery.
type ImportGalleryMultipartBody struct {
	// Files Image files to upload
	Files []openapi_types.File `json:"files"`
}

// SaveAnnotationsJSONRequestBody defines body for SaveAnnotations for application/json ContentType.
type SaveAnnotationsJSONRequestBody = SaveAnnotationsRequest

// SkipImageJSONRequestBody defines body for SkipImage for application/json ContentType.
type SkipImageJSONRequestBody = SkipRequest

// StartAugmentJSONRequestBody defines body for StartAugment for application/json ContentType.
type StartAugmentJSONRequestBody = AugmentRequest

// UpsertClassJSONRequestBody defines body for UpsertClass for application/json ContentType.
type UpsertClassJSONRequestBody = UpsertClassRequest

// ImportGalleryMultipartRequestBody defines body for ImportGallery for multipart/form-data ContentType.
type ImportGalleryMultipartRequestBody ImportGalleryMultipartBody

// DeleteImagesJSONRequestBody defines body for DeleteImages for application/json ContentType.
type DeleteImagesJSONRequestBody = DeleteImagesRequest

// SegmentJSONRequestBody defines body for Segment for application/json ContentType.
type SegmentJSONRequestBody = SegmentationRequest

// StartTrainJSONRequestBody defines body for StartTrain for application/json ContentType.
type StartTrainJSONRequestBody = TrainRequest
