baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Docs"
theme = "hugo-book"
defaultContentLanguage = "en"
enableGitInfo = true
contentDir = "content/v1"

[params]
BookTheme = "auto"
BookToC = true
BookSearch = true
BookRepo = "https://github.com/your/repo"
BookLogo = "logo.png"
BookSection = "*"



[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]