baseURL = "https://voldemorbot.teamvoldemor.com/"
languageCode = "en-us"
title = "Voldemorbot Docs"
theme = "hugo-book"
defaultContentLanguage = "en"
enableGitInfo = true
enableRobotsTXT = true
contentDir = "content/v1"

[params]
BookTheme = "auto"
BookToC = true
BookSearch = true
BookRepo = "https://github.com/teamvoldemor/voldemorbot"
BookSection = "*"
BookDebug = false



[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]