// Package simulation provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package simulation

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GenerateScenarioRequestChallenge.
const (
	GenerateScenarioRequestChallengeObstacles GenerateScenarioRequestChallenge = "obstacles"
	GenerateScenarioRequestChallengeOpen      GenerateScenarioRequestChallenge = "open"
)

// Valid indicates whether the value is a known member of the GenerateScenarioRequestChallenge enum.
func (e GenerateScenarioRequestChallenge) Valid() bool {
	switch e {
	case GenerateScenarioRequestChallengeObstacles:
		return true
	case GenerateScenarioRequestChallengeOpen:
		return true
	default:
		return false
	}
}

// Defines values for GenerateScenarioRequestCorridors.
const (
	Mixed  GenerateScenarioRequestCorridors = "mixed"
	Narrow GenerateScenarioRequestCorridors = "narrow"
	Wide   GenerateScenarioRequestCorridors = "wide"
)

// Valid indicates whether the value is a known member of the GenerateScenarioRequestCorridors enum.
func (e GenerateScenarioRequestCorridors) Valid() bool {
	switch e {
	case Mixed:
		return true
	case Narrow:
		return true
	case Wide:
		return true
	default:
		return false
	}
}

// Defines values for GenerateScenarioRequestLighting.
const (
	CLOUDY         GenerateScenarioRequestLighting = "CLOUDY"
	DIRECTSUNLIGHT GenerateScenarioRequestLighting = "DIRECT_SUNLIGHT"
	EVENING        GenerateScenarioRequestLighting = "EVENING"
	INDOORBRIGHT   GenerateScenarioRequestLighting = "INDOOR_BRIGHT"
	INDOORDIM      GenerateScenarioRequestLighting = "INDOOR_DIM"
	MIXED          GenerateScenarioRequestLighting = "MIXED"
)

// Valid indicates whether the value is a known member of the GenerateScenarioRequestLighting enum.
func (e GenerateScenarioRequestLighting) Valid() bool {
	switch e {
	case CLOUDY:
		return true
	case DIRECTSUNLIGHT:
		return true
	case EVENING:
		return true
	case INDOORBRIGHT:
		return true
	case INDOORDIM:
		return true
	case MIXED:
		return true
	default:
		return false
	}
}

// Defines values for RunControlRequestAction.
const (
	Pause   RunControlRequestAction = "pause"
	Restart RunControlRequestAction = "restart"
	Resume  RunControlRequestAction = "resume"
	Stop    RunControlRequestAction = "stop"
)

// Valid indicates whether the value is a known member of the RunControlRequestAction enum.
func (e RunControlRequestAction) Valid() bool {
	switch e {
	case Pause:
		return true
	case Restart:
		return true
	case Resume:
		return true
	case Stop:
		return true
	default:
		return false
	}
}

// Defines values for ScenarioChallenge.
const (
	ScenarioChallengeObstacles ScenarioChallenge = "obstacles"
	ScenarioChallengeOpen      ScenarioChallenge = "open"
)

// Valid indicates whether the value is a known member of the ScenarioChallenge enum.
func (e ScenarioChallenge) Valid() bool {
	switch e {
	case ScenarioChallengeObstacles:
		return true
	case ScenarioChallengeOpen:
		return true
	default:
		return false
	}
}

// Defines values for ScenarioSummaryChallenge.
const (
	ScenarioSummaryChallengeObstacles ScenarioSummaryChallenge = "obstacles"
	ScenarioSummaryChallengeOpen      ScenarioSummaryChallenge = "open"
)

// Valid indicates whether the value is a known member of the ScenarioSummaryChallenge enum.
func (e ScenarioSummaryChallenge) Valid() bool {
	switch e {
	case ScenarioSummaryChallengeObstacles:
		return true
	case ScenarioSummaryChallengeOpen:
		return true
	default:
		return false
	}
}

// Defines values for SimulationRunStatus.
const (
	Cancelled SimulationRunStatus = "cancelled"
	Completed SimulationRunStatus = "completed"
	Failed    SimulationRunStatus = "failed"
	Paused    SimulationRunStatus = "paused"
	Pending   SimulationRunStatus = "pending"
	Running   SimulationRunStatus = "running"
)

// Valid indicates whether the value is a known member of the SimulationRunStatus enum.
func (e SimulationRunStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Paused:
		return true
	case Pending:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for StartingZoneConfigDirection.
const (
	CLOCKWISE        StartingZoneConfigDirection = "CLOCKWISE"
	COUNTERCLOCKWISE StartingZoneConfigDirection = "COUNTERCLOCKWISE"
)

// Valid indicates whether the value is a known member of the StartingZoneConfigDirection enum.
func (e StartingZoneConfigDirection) Valid() bool {
	switch e {
	case CLOCKWISE:
		return true
	case COUNTERCLOCKWISE:
		return true
	default:
		return false
	}
}

// Defines values for ListScenariosParamsChallenge.
const (
	ListScenariosParamsChallengeObstacles ListScenariosParamsChallenge = "obstacles"
	ListScenariosParamsChallengeOpen      ListScenariosParamsChallenge = "open"
)

// Valid indicates whether the value is a known member of the ListScenariosParamsChallenge enum.
func (e ListScenariosParamsChallenge) Valid() bool {
	switch e {
	case ListScenariosParamsChallengeObstacles:
		return true
	case ListScenariosParamsChallengeOpen:
		return true
	default:
		return false
	}
}

// EnvironmentConfig defines model for EnvironmentConfig.
type EnvironmentConfig struct {
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Lighting  *LightingConfig     `json:"lighting,omitempty"`
	Name      *string             `json:"name,omitempty"`
	WorldFile *string             `json:"world_file,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GenerateScenarioRequest defines model for GenerateScenarioRequest.
type GenerateScenarioRequest struct {
	Challenge GenerateScenarioRequestChallenge `json:"challenge"`

	// Corridors Corridor width profile
	Corridors *GenerateScenarioRequestCorridors `json:"corridors,omitempty"`
	Lighting  *GenerateScenarioRequestLighting  `json:"lighting,omitempty"`
	NumSigns  *int                              `json:"num_signs,omitempty"`
	Randomize *bool                             `json:"randomize,omitempty"`
}

// GenerateScenarioRequestChallenge defines model for GenerateScenarioRequest.Challenge.
type GenerateScenarioRequestChallenge string

// GenerateScenarioRequestCorridors Corridor width profile
type GenerateScenarioRequestCorridors string

// GenerateScenarioRequestLighting defines model for GenerateScenarioRequest.Lighting.
type GenerateScenarioRequestLighting string

// LightingConfig defines model for LightingConfig.
type LightingConfig struct {
	AmbientIntensity *float32   `json:"ambient_intensity,omitempty"`
	CastShadows      *bool      `json:"cast_shadows,omitempty"`
	Direction        *[]float32 `json:"direction,omitempty"`
	Intensity        *float32   `json:"intensity,omitempty"`
	Scenario         *string    `json:"scenario,omitempty"`
}

// ParkingLotConfig defines model for ParkingLotConfig.
type ParkingLotConfig struct {
	Block1Position *[]float64 `json:"block1_position,omitempty"`
	Block2Position *[]float64 `json:"block2_position,omitempty"`
	Depth          *float64   `json:"depth,omitempty"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// RunControlRequest defines model for RunControlRequest.
type RunControlRequest struct {
	Action RunControlRequestAction `json:"action"`
}

// RunControlRequestAction defines model for RunControlRequest.Action.
type RunControlRequestAction string

// RunMetrics defines model for RunMetrics.
type RunMetrics struct {
	AvgLapTimeS      *float64 `json:"avg_lap_time_s,omitempty"`
	AvgSpeedMs       *float64 `json:"avg_speed_ms,omitempty"`
	MaxSpeedMs       *float64 `json:"max_speed_ms,omitempty"`
	ObstacleContacts *int     `json:"obstacle_contacts,omitempty"`
	PathLengthM      *float64 `json:"path_length_m,omitempty"`
	SignDetections   *int     `json:"sign_detections,omitempty"`
}

// Scenario defines model for Scenario.
type Scenario struct {
	Challenge      ScenarioChallenge   `json:"challenge"`
	CreatedAt      time.Time           `json:"created_at"`
	DetectionCount *int                `json:"detection_count,omitempty"`
	Environment    *string             `json:"environment,omitempty"`
	Id             openapi_types.UUID  `json:"id"`
	Lighting       *LightingConfig     `json:"lighting,omitempty"`
	Name           string              `json:"name"`
	ParkingLot     *ParkingLotConfig   `json:"parking_lot,omitempty"`
	StartingZone   *StartingZoneConfig `json:"starting_zone,omitempty"`
	TrackConfig    *TrackConfig        `json:"track_config,omitempty"`
}

// ScenarioChallenge defines model for Scenario.Challenge.
type ScenarioChallenge string

// ScenarioSummary defines model for ScenarioSummary.
type ScenarioSummary struct {
	Challenge      ScenarioSummaryChallenge `json:"challenge"`
	CreatedAt      time.Time                `json:"created_at"`
	DetectionCount *int                     `json:"detection_count,omitempty"`
	Environment    *string                  `json:"environment,omitempty"`
	Id             openapi_types.UUID       `json:"id"`
	Name           string                   `json:"name"`
}

// ScenarioSummaryChallenge defines model for ScenarioSummary.Challenge.
type ScenarioSummaryChallenge string

// SimulationRun defines model for SimulationRun.
type SimulationRun struct {
	CollisionCount *int                `json:"collision_count,omitempty"`
	CompletedAt    *time.Time          `json:"completed_at,omitempty"`
	DurationS      *float64            `json:"duration_s,omitempty"`
	Id             openapi_types.UUID  `json:"id"`
	LapsCompleted  *int                `json:"laps_completed,omitempty"`
	Metrics        *RunMetrics         `json:"metrics,omitempty"`
	ScenarioId     openapi_types.UUID  `json:"scenario_id"`
	StartedAt      time.Time           `json:"started_at"`
	Status         SimulationRunStatus `json:"status"`
	TotalLaps      *int                `json:"total_laps,omitempty"`
}

// SimulationRunStatus defines model for SimulationRun.Status.
type SimulationRunStatus string

// StartRunRequest defines model for StartRunRequest.
type StartRunRequest struct {
	Headless   *bool              `json:"headless,omitempty"`
	Laps       *int               `json:"laps,omitempty"`
	ScenarioId openapi_types.UUID `json:"scenario_id"`
}

// StartingZoneConfig defines model for StartingZoneConfig.
type StartingZoneConfig struct {
	Direction *StartingZoneConfigDirection `json:"direction,omitempty"`
	Length    *float64                     `json:"length,omitempty"`
	Position  *[]float64                   `json:"position,omitempty"`
}

// StartingZoneConfigDirection defines model for StartingZoneConfig.Direction.
type StartingZoneConfigDirection string

// TrackConfig defines model for TrackConfig.
type TrackConfig struct {
	CorridorWidths *map[string]struct {
		Type  *string  `json:"type,omitempty"`
		Width *float64 `json:"width,omitempty"`
	} `json:"corridor_widths,omitempty"`
	Sections   *[]string `json:"sections,omitempty"`
	TrackWidth *float64  `json:"track_width,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ProblemDetails

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListScenariosParams defines parameters for ListScenarios.
type ListScenariosParams struct {
	// Challenge Filter by challenge type
	Challenge *ListScenariosParamsChallenge `form:"challenge,omitempty" json:"challenge,omitempty"`
	Limit     *int                          `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListScenariosParamsChallenge defines parameters for ListScenarios.
type ListScenariosParamsChallenge string

// StartSimulationRunJSONRequestBody defines body for StartSimulationRun for application/json ContentType.
type StartSimulationRunJSONRequestBody = StartRunRequest

// ControlSimulationRunJSONRequestBody defines body for ControlSimulationRun for application/json ContentType.
type ControlSimulationRunJSONRequestBody = RunControlRequest

// GenerateScenarioJSONRequestBody defines body for GenerateScenario for application/json ContentType.
type GenerateScenarioJSONRequestBody = GenerateScenarioRequest
