// Code generated by `simgen generate-robot-constants` from platform/shared/config/robot.toml. DO NOT EDIT.

package simconfig

// Robot chassis dimensions (meters). LEGO Bugatti Bolide + Ackermann.
const (
	RobotLength      = 0.3
	RobotWidth       = 0.2
	RobotHeight      = 0.1
	RobotWheelbase   = 0.19
	RobotTrackWidth  = 0.1675
	RobotWheelRadius = 0.035
	RobotWheelWidth  = 0.025
	RobotMaxSteering = 1.2253 // ~30°
	RobotChassisMass = 0.8    // kg
	RobotWheelMass   = 0.05   // kg per wheel

	// RobotLidarMountXOffset: chassis_length/2 - the lidar mesh's own radius (0.0278,
	// matching wro_robot.urdf.xacro's lidar_link visual/collision cylinder) — the C1
	// mounted flush with the front edge, centered left/right, upside-down.
	RobotLidarMountXOffset = 0.1222

	// Camera mounted directly over the LIDAR, tilted down.
	RobotCameraMountXOffset = 0.1222
	RobotCameraMountZOffset = 0.16
	RobotCameraPitchRad     = 0.5236 // ~30°, tilted down
)
