"""Code generated by `simgen generate-robot-constants` from platform/shared/config/robot.toml. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

# Chassis (meters, kg)
CHASSIS_LENGTH: Final[float] = 0.3
CHASSIS_WIDTH: Final[float] = 0.194
CHASSIS_HEIGHT: Final[float] = 0.1
CHASSIS_MASS: Final[float] = 1.3

# Ackermann geometry (meters, radians)
WHEELBASE: Final[float] = 0.19
TRACK_WIDTH: Final[float] = 0.1675
# Road-wheel angle at full lock, derived from the servo travel below.
MAX_STEERING_ANGLE: Final[float] = 1.2252211349000193

# Steering hardware (servo degrees, ratio). The road-wheel angle above is
# their product; these are the two measured facts it comes from.
SERVO_MAX_ANGLE_DEG: Final[float] = 90.0
LINKAGE_RATIO: Final[float] = 0.78

# Wheel (meters, kg)
WHEEL_RADIUS: Final[float] = 0.035
WHEEL_WIDTH: Final[float] = 0.025
WHEEL_MASS: Final[float] = 0.05

# Drivetrain limits (m/s, m/s^2, ratio). Hard ceilings, not tuning.
MAX_SPEED_MPS: Final[float] = 0.156
MAX_ACCEL_MPS2: Final[float] = 2.0
REAR_STEER_RATIO: Final[float] = 1.0

# LIDAR mount (meters, degrees). LIDAR_INVERTED is the single source of
# truth for the upside-down mount -- consumers needing the total yaw
# correction combine (180.0 if LIDAR_INVERTED else 0.0) + LIDAR_MOUNT_YAW_OFFSET_DEG
# themselves rather than reading a pre-combined constant, since some (the
# sllidar_ros2 launch parameter) need LIDAR_INVERTED alone.
LIDAR_MOUNT_X_OFFSET: Final[float] = 0.1222
LIDAR_MOUNT_Z_OFFSET: Final[float] = 0.02
LIDAR_INVERTED: Final[bool] = True
LIDAR_MOUNT_YAW_OFFSET_DEG: Final[float] = 0.0

# IMU mount (meters)
IMU_MOUNT_Z_OFFSET: Final[float] = 0.01

# Camera mount (meters, radians)
CAMERA_MOUNT_X_OFFSET: Final[float] = 0.1222
CAMERA_MOUNT_Z_OFFSET: Final[float] = 0.16
CAMERA_MOUNT_PITCH_RAD: Final[float] = 0.5236
