// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE session_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT session_id, created_at, entry_count
FROM sessions
WHERE session_id = ?
`

func (q *Queries) GetSession(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i Session
	err := row.Scan(&i.SessionID, &i.CreatedAt, &i.EntryCount)
	return i, err
}

const incrementEntryCount = `-- name: IncrementEntryCount :exec
UPDATE sessions SET entry_count = entry_count + 1 WHERE session_id = ?
`

func (q *Queries) IncrementEntryCount(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, incrementEntryCount, sessionID)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (session_id, created_at, entry_count)
VALUES (?, ?, 0)
`

type InsertSessionParams struct {
	SessionID string
	CreatedAt int64
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession, arg.SessionID, arg.CreatedAt)
	return err
}

const listSessions = `-- name: ListSessions :many
SELECT session_id, created_at, entry_count
FROM sessions
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(&i.SessionID, &i.CreatedAt, &i.EntryCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
