"""Scenario catalogs backing the RViz live visualizer and two pytest batteries.

Both catalogs load ``*_metadata.json`` fixtures generated by the Go generator
(``platform/gazebo/generator``, ``simgen``) — the same generator that drives
Gazebo and the real robot — so visualizing "scenario N" here means watching a
real official-generator layout, including the actual WRO 2026 36-scenario
traffic-sign table (``internal/generate/scenarios.go``) for Obstacles
Challenge, not a hand-approximated one.

To regenerate the fixtures (e.g. after a corridor/sign-table change in Go),
from ``platform/gazebo/generator``:

    go run ./cmd/simgen generate --challenge open --num-scenarios 28 --seed 2026 --output-dir /tmp/fixtures/open
    go run ./cmd/simgen generate --challenge obstacles --num-scenarios 16 --seed 2026 --output-dir /tmp/fixtures/obstacles

then copy only the ``*_metadata.json`` files (discard the ``.sdf``/``.svg``
siblings) into ``tests/fixtures/scenarios/{open,obstacles}/`` here. Plain
``--seed`` (not ``--deterministic``, which pins every scenario to the same
South/clockwise/wide defaults) keeps generation both reproducible and varied.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from shared.config.constants import CompetitionSpecs

_FIXTURES_DIR = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "scenarios"


@dataclass(frozen=True, slots=True)
class NamedScenario:
    """One (metadata, laps, seed) input, labeled after its Go-generated fixture."""

    label: str
    metadata: dict[str, Any]
    laps: int
    seed: int


def _load_fixture_scenarios(
    subdir: str,
    label_prefix: str,
    fixtures_dir: Path | None = None,
) -> list[NamedScenario]:
    """Load every ``*_metadata.json`` under ``fixtures_dir/subdir``.

    ``fixtures_dir`` overrides the committed fixture set. The committed one is
    deliberately small (16 obstacles, 28 open) because it is the unit-test
    battery and has to stay fast; statistical questions -- how often some
    configuration occurs, how a change behaves across the space rather than on
    one sample -- need hundreds, which is what the override is for. Generate
    them with the same Go generator and a pinned seed (see the module
    docstring), so a corpus is reproducible without being committed.
    """
    root = fixtures_dir if fixtures_dir is not None else _FIXTURES_DIR / subdir
    scenarios = []
    for path in sorted(root.glob("*_metadata.json")):
        meta = json.loads(path.read_text())
        sc = meta["starting_conditions"]
        label = f"{label_prefix}_{meta['scenario_id']:04d}[{sc['section']}/{sc['direction']}]"
        scenarios.append(NamedScenario(label, meta, CompetitionSpecs.OPEN_CHALLENGE_LAPS, seed=meta["scenario_id"]))
    return scenarios


def all_test_scenarios(fixtures_dir: Path | None = None) -> list[NamedScenario]:
    """The Go-generated Open Challenge scenario fixtures."""
    return _load_fixture_scenarios("open", "go_open", fixtures_dir)


def all_obstacles_demo_scenarios(fixtures_dir: Path | None = None) -> list[NamedScenario]:
    """The Go-generated Obstacles Challenge scenario fixtures (signs + parking).

    Every scenario has both a sign layout (from the real 36-scenario table)
    and a parking lot — the Go generator always builds them together for the
    Obstacles Challenge, matching the real competition rules.

    Pass ``fixtures_dir`` to run against a larger generated corpus instead of
    the committed 16 — see :func:`_load_fixture_scenarios`.
    """
    return _load_fixture_scenarios("obstacles", "go_obstacles", fixtures_dir)


def find_scenario(selector: str, scenarios: list[NamedScenario]) -> NamedScenario:
    """Resolve a CLI selector to one scenario: an index, or a label substring."""
    if selector.isdigit():
        idx = int(selector)
        if 0 <= idx < len(scenarios):
            return scenarios[idx]
        msg = f"Scenario index {idx} out of range (0-{len(scenarios) - 1})."
        raise ValueError(msg)
    matches = [s for s in scenarios if selector.lower() in s.label.lower()]
    if not matches:
        msg = f"No scenario label contains {selector!r}."
        raise ValueError(msg)
    if len(matches) > 1:
        labels = ", ".join(m.label for m in matches)
        msg = f"{selector!r} matches multiple scenarios: {labels}"
        raise ValueError(msg)
    return matches[0]
