// Package robot provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package robot

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for DisableCommandChannelCommandCommandType.
const (
	DISABLECOMMANDCHANNEL DisableCommandChannelCommandCommandType = "DISABLE_COMMAND_CHANNEL"
)

// Valid indicates whether the value is a known member of the DisableCommandChannelCommandCommandType enum.
func (e DisableCommandChannelCommandCommandType) Valid() bool {
	switch e {
	case DISABLECOMMANDCHANNEL:
		return true
	default:
		return false
	}
}

// Defines values for EmergencyStopCommandCommandType.
const (
	EMERGENCYSTOP EmergencyStopCommandCommandType = "EMERGENCY_STOP"
)

// Valid indicates whether the value is a known member of the EmergencyStopCommandCommandType enum.
func (e EmergencyStopCommandCommandType) Valid() bool {
	switch e {
	case EMERGENCYSTOP:
		return true
	default:
		return false
	}
}

// Defines values for PauseCommandCommandType.
const (
	PAUSE PauseCommandCommandType = "PAUSE"
)

// Valid indicates whether the value is a known member of the PauseCommandCommandType enum.
func (e PauseCommandCommandType) Valid() bool {
	switch e {
	case PAUSE:
		return true
	default:
		return false
	}
}

// Defines values for RebootCommandCommandType.
const (
	REBOOT RebootCommandCommandType = "REBOOT"
)

// Valid indicates whether the value is a known member of the RebootCommandCommandType enum.
func (e RebootCommandCommandType) Valid() bool {
	switch e {
	case REBOOT:
		return true
	default:
		return false
	}
}

// Defines values for ResumeCommandCommandType.
const (
	RESUME ResumeCommandCommandType = "RESUME"
)

// Valid indicates whether the value is a known member of the ResumeCommandCommandType enum.
func (e ResumeCommandCommandType) Valid() bool {
	switch e {
	case RESUME:
		return true
	default:
		return false
	}
}

// Defines values for ReturnToStartCommandCommandType.
const (
	RETURNTOSTART ReturnToStartCommandCommandType = "RETURN_TO_START"
)

// Valid indicates whether the value is a known member of the ReturnToStartCommandCommandType enum.
func (e ReturnToStartCommandCommandType) Valid() bool {
	switch e {
	case RETURNTOSTART:
		return true
	default:
		return false
	}
}

// Defines values for RobotCommandResponseStatus.
const (
	Accepted RobotCommandResponseStatus = "accepted"
	Queued   RobotCommandResponseStatus = "queued"
	Rejected RobotCommandResponseStatus = "rejected"
)

// Valid indicates whether the value is a known member of the RobotCommandResponseStatus enum.
func (e RobotCommandResponseStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Queued:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for RobotState.
const (
	BOOTCHECK RobotState = "BOOT_CHECK"
	ERROR     RobotState = "ERROR"
	FINISHED  RobotState = "FINISHED"
	OFFLINE   RobotState = "OFFLINE"
	RACING    RobotState = "RACING"
	READY     RobotState = "READY"
)

// Valid indicates whether the value is a known member of the RobotState enum.
func (e RobotState) Valid() bool {
	switch e {
	case BOOTCHECK:
		return true
	case ERROR:
		return true
	case FINISHED:
		return true
	case OFFLINE:
		return true
	case RACING:
		return true
	case READY:
		return true
	default:
		return false
	}
}

// Defines values for SetTelemetryChannelCommandCommandType.
const (
	SETTELEMETRYCHANNEL SetTelemetryChannelCommandCommandType = "SET_TELEMETRY_CHANNEL"
)

// Valid indicates whether the value is a known member of the SetTelemetryChannelCommandCommandType enum.
func (e SetTelemetryChannelCommandCommandType) Valid() bool {
	switch e {
	case SETTELEMETRYCHANNEL:
		return true
	default:
		return false
	}
}

// Defines values for SetVisionDebugCommandCommandType.
const (
	SETVISIONDEBUG SetVisionDebugCommandCommandType = "SET_VISION_DEBUG"
)

// Valid indicates whether the value is a known member of the SetVisionDebugCommandCommandType enum.
func (e SetVisionDebugCommandCommandType) Valid() bool {
	switch e {
	case SETVISIONDEBUG:
		return true
	default:
		return false
	}
}

// Defines values for ShutdownCommandCommandType.
const (
	SHUTDOWN ShutdownCommandCommandType = "SHUTDOWN"
)

// Valid indicates whether the value is a known member of the ShutdownCommandCommandType enum.
func (e ShutdownCommandCommandType) Valid() bool {
	switch e {
	case SHUTDOWN:
		return true
	default:
		return false
	}
}

// Defines values for StartRaceCommandCommandType.
const (
	STARTRACE StartRaceCommandCommandType = "START_RACE"
)

// Valid indicates whether the value is a known member of the StartRaceCommandCommandType enum.
func (e StartRaceCommandCommandType) Valid() bool {
	switch e {
	case STARTRACE:
		return true
	default:
		return false
	}
}

// Defines values for StopRaceCommandCommandType.
const (
	STOPRACE StopRaceCommandCommandType = "STOP_RACE"
)

// Valid indicates whether the value is a known member of the StopRaceCommandCommandType enum.
func (e StopRaceCommandCommandType) Valid() bool {
	switch e {
	case STOPRACE:
		return true
	default:
		return false
	}
}

// BatteryStatus defines model for BatteryStatus.
type BatteryStatus struct {
	// Current Current draw in amps
	Current *float64 `json:"current,omitempty"`

	// StateOfCharge State of charge percentage
	StateOfCharge float64 `json:"state_of_charge"`

	// Voltage Battery voltage
	Voltage float64 `json:"voltage"`
}

// CreateRobotRequest defines model for CreateRobotRequest.
type CreateRobotRequest struct {
	FleetId openapi_types.UUID `binding:"required,uuid" json:"fleet_id"`
	Name    string             `binding:"required,max=255" json:"name"`
}

// DisableCommandChannelCommand One-way: disables the robot's gRPC command channel remotely. Re-enabling requires local robot access, since disabling this command closes the very channel a remote re-enable command would need to travel over.
type DisableCommandChannelCommand struct {
	CommandType DisableCommandChannelCommandCommandType `json:"command_type"`
}

// DisableCommandChannelCommandCommandType defines model for DisableCommandChannelCommand.CommandType.
type DisableCommandChannelCommandCommandType string

// EmergencyStopCommand defines model for EmergencyStopCommand.
type EmergencyStopCommand struct {
	CommandType EmergencyStopCommandCommandType `json:"command_type"`
}

// EmergencyStopCommandCommandType defines model for EmergencyStopCommand.CommandType.
type EmergencyStopCommandCommandType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// PauseCommand defines model for PauseCommand.
type PauseCommand struct {
	CommandType PauseCommandCommandType `json:"command_type"`
}

// PauseCommandCommandType defines model for PauseCommand.CommandType.
type PauseCommandCommandType string

// Pose defines model for Pose.
type Pose struct {
	// X X position in meters
	X float64 `json:"x"`

	// Y Y position in meters
	Y float64 `json:"y"`

	// Yaw Orientation in radians
	Yaw float64 `json:"yaw"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// RebootCommand defines model for RebootCommand.
type RebootCommand struct {
	CommandType RebootCommandCommandType `json:"command_type"`
}

// RebootCommandCommandType defines model for RebootCommand.CommandType.
type RebootCommandCommandType string

// ResumeCommand defines model for ResumeCommand.
type ResumeCommand struct {
	CommandType ResumeCommandCommandType `json:"command_type"`
}

// ResumeCommandCommandType defines model for ResumeCommand.CommandType.
type ResumeCommandCommandType string

// ReturnToStartCommand defines model for ReturnToStartCommand.
type ReturnToStartCommand struct {
	CommandType ReturnToStartCommandCommandType `json:"command_type"`
}

// ReturnToStartCommandCommandType defines model for ReturnToStartCommand.CommandType.
type ReturnToStartCommandCommandType string

// Robot defines model for Robot.
type Robot struct {
	CreatedAt time.Time          `json:"created_at"`
	FleetId   openapi_types.UUID `binding:"required,uuid" json:"fleet_id"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `binding:"required,max=255" json:"name"`
	State     RobotState         `json:"state"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// RobotCommand defines model for RobotCommand.
type RobotCommand struct {
	union json.RawMessage
}

// RobotCommandResponse defines model for RobotCommandResponse.
type RobotCommandResponse struct {
	CommandId openapi_types.UUID         `json:"command_id"`
	Message   *string                    `json:"message,omitempty"`
	Status    RobotCommandResponseStatus `json:"status"`
}

// RobotCommandResponseStatus defines model for RobotCommandResponse.Status.
type RobotCommandResponseStatus string

// RobotConfig defines model for RobotConfig.
type RobotConfig struct {
	// LookaheadDistance Pure pursuit lookahead in meters
	LookaheadDistance *float64 `json:"lookahead_distance,omitempty"`

	// MaxAngularSpeed Maximum angular speed in rad/s
	MaxAngularSpeed *float64 `json:"max_angular_speed,omitempty"`

	// MaxLinearSpeed Maximum linear speed in m/s
	MaxLinearSpeed *float64  `json:"max_linear_speed,omitempty"`
	SpeedProfiles  *[]string `json:"speed_profiles,omitempty"`

	// SteeringKp Steering PID proportional gain
	SteeringKp *float64 `json:"steering_kp,omitempty"`
}

// RobotState defines model for RobotState.
type RobotState string

// RobotStatus defines model for RobotStatus.
type RobotStatus struct {
	Battery      *BatteryStatus     `json:"battery,omitempty"`
	LapNumber    *int               `json:"lap_number,omitempty"`
	MissionName  *string            `json:"mission_name,omitempty"`
	Pose         Pose               `json:"pose"`
	RobotId      openapi_types.UUID `json:"robot_id"`
	State        RobotState         `json:"state"`
	SystemStatus SystemStatus       `json:"system_status"`
	Timestamp    time.Time          `json:"timestamp"`
	Velocity     Velocity           `json:"velocity"`
}

// SetTelemetryChannelCommand Bidirectional: toggles the telemetry gRPC channel without affecting the command channel, so it is remotely reversible either way.
type SetTelemetryChannelCommand struct {
	CommandType SetTelemetryChannelCommandCommandType `json:"command_type"`
	Parameters  SetTelemetryChannelParams             `json:"parameters"`
}

// SetTelemetryChannelCommandCommandType defines model for SetTelemetryChannelCommand.CommandType.
type SetTelemetryChannelCommandCommandType string

// SetTelemetryChannelParams defines model for SetTelemetryChannelParams.
type SetTelemetryChannelParams struct {
	// Enabled Enable or disable the telemetry gRPC stream
	Enabled bool `json:"enabled"`
}

// SetVisionDebugCommand defines model for SetVisionDebugCommand.
type SetVisionDebugCommand struct {
	CommandType SetVisionDebugCommandCommandType `json:"command_type"`
	Parameters  SetVisionDebugParams             `json:"parameters"`
}

// SetVisionDebugCommandCommandType defines model for SetVisionDebugCommand.CommandType.
type SetVisionDebugCommandCommandType string

// SetVisionDebugParams defines model for SetVisionDebugParams.
type SetVisionDebugParams struct {
	// Enabled Enable or disable the vision debug annotated-image stream
	Enabled bool `json:"enabled"`

	// StreamFps Optional cap on the debug stream frame rate
	StreamFps *int32 `json:"stream_fps,omitempty"`
}

// ShutdownCommand defines model for ShutdownCommand.
type ShutdownCommand struct {
	CommandType ShutdownCommandCommandType `json:"command_type"`
}

// ShutdownCommandCommandType defines model for ShutdownCommand.CommandType.
type ShutdownCommandCommandType string

// StartRaceCommand defines model for StartRaceCommand.
type StartRaceCommand struct {
	CommandType StartRaceCommandCommandType `json:"command_type"`
	Parameters  *StartRaceParams            `json:"parameters,omitempty"`
}

// StartRaceCommandCommandType defines model for StartRaceCommand.CommandType.
type StartRaceCommandCommandType string

// StartRaceParams defines model for StartRaceParams.
type StartRaceParams struct {
	MissionName *string `json:"mission_name,omitempty"`
}

// StopRaceCommand defines model for StopRaceCommand.
type StopRaceCommand struct {
	CommandType StopRaceCommandCommandType `json:"command_type"`
}

// StopRaceCommandCommandType defines model for StopRaceCommand.CommandType.
type StopRaceCommandCommandType string

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	CameraReady *bool `json:"camera_ready,omitempty"`

	// CpuTemp CPU temperature in Celsius
	CpuTemp    *float64 `json:"cpu_temp,omitempty"`
	DriveReady *bool    `json:"drive_ready,omitempty"`
	ImuReady   *bool    `json:"imu_ready,omitempty"`
	LidarReady *bool    `json:"lidar_ready,omitempty"`

	// MotorTemps Motor temperatures in Celsius
	MotorTemps *[]float64 `json:"motor_temps,omitempty"`

	// RosNodesActive Number of active ROS nodes
	RosNodesActive *int `json:"ros_nodes_active,omitempty"`
}

// UpdateRobotConfigRequest defines model for UpdateRobotConfigRequest.
type UpdateRobotConfigRequest struct {
	LookaheadDistance *float64 `json:"lookahead_distance,omitempty"`
	MaxAngularSpeed   *float64 `json:"max_angular_speed,omitempty"`
	MaxLinearSpeed    *float64 `json:"max_linear_speed,omitempty"`
	SpeedProfile      *string  `json:"speed_profile,omitempty"`
	SteeringKp        *float64 `json:"steering_kp,omitempty"`
}

// UpdateRobotRequest defines model for UpdateRobotRequest.
type UpdateRobotRequest struct {
	Name *string `binding:"omitempty,max=255" json:"name,omitempty"`
}

// Velocity defines model for Velocity.
type Velocity struct {
	// Angular Angular velocity in rad/s
	Angular float64 `json:"angular"`

	// Linear Linear velocity in m/s
	Linear float64 `json:"linear"`
}

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ProblemDetails

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListRobotsParams defines parameters for ListRobots.
type ListRobotsParams struct {
	// FleetId Filter by fleet
	FleetId *openapi_types.UUID `form:"fleet_id,omitempty" json:"fleet_id,omitempty"`
	State   *RobotState         `form:"state,omitempty" json:"state,omitempty"`
}

// CreateRobotJSONRequestBody defines body for CreateRobot for application/json ContentType.
type CreateRobotJSONRequestBody = CreateRobotRequest

// UpdateRobotJSONRequestBody defines body for UpdateRobot for application/json ContentType.
type UpdateRobotJSONRequestBody = UpdateRobotRequest

// SendRobotCommandJSONRequestBody defines body for SendRobotCommand for application/json ContentType.
type SendRobotCommandJSONRequestBody = RobotCommand

// UpdateRobotConfigJSONRequestBody defines body for UpdateRobotConfig for application/json ContentType.
type UpdateRobotConfigJSONRequestBody = UpdateRobotConfigRequest

// AsStartRaceCommand returns the union data inside the RobotCommand as a StartRaceCommand
func (t RobotCommand) AsStartRaceCommand() (StartRaceCommand, error) {
	var body StartRaceCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartRaceCommand overwrites any union data inside the RobotCommand as the provided StartRaceCommand
func (t *RobotCommand) FromStartRaceCommand(v StartRaceCommand) error {
	v.CommandType = "START_RACE"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartRaceCommand performs a merge with any union data inside the RobotCommand, using the provided StartRaceCommand
func (t *RobotCommand) MergeStartRaceCommand(v StartRaceCommand) error {
	v.CommandType = "START_RACE"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStopRaceCommand returns the union data inside the RobotCommand as a StopRaceCommand
func (t RobotCommand) AsStopRaceCommand() (StopRaceCommand, error) {
	var body StopRaceCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStopRaceCommand overwrites any union data inside the RobotCommand as the provided StopRaceCommand
func (t *RobotCommand) FromStopRaceCommand(v StopRaceCommand) error {
	v.CommandType = "STOP_RACE"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStopRaceCommand performs a merge with any union data inside the RobotCommand, using the provided StopRaceCommand
func (t *RobotCommand) MergeStopRaceCommand(v StopRaceCommand) error {
	v.CommandType = "STOP_RACE"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPauseCommand returns the union data inside the RobotCommand as a PauseCommand
func (t RobotCommand) AsPauseCommand() (PauseCommand, error) {
	var body PauseCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPauseCommand overwrites any union data inside the RobotCommand as the provided PauseCommand
func (t *RobotCommand) FromPauseCommand(v PauseCommand) error {
	v.CommandType = "PAUSE"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePauseCommand performs a merge with any union data inside the RobotCommand, using the provided PauseCommand
func (t *RobotCommand) MergePauseCommand(v PauseCommand) error {
	v.CommandType = "PAUSE"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResumeCommand returns the union data inside the RobotCommand as a ResumeCommand
func (t RobotCommand) AsResumeCommand() (ResumeCommand, error) {
	var body ResumeCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResumeCommand overwrites any union data inside the RobotCommand as the provided ResumeCommand
func (t *RobotCommand) FromResumeCommand(v ResumeCommand) error {
	v.CommandType = "RESUME"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResumeCommand performs a merge with any union data inside the RobotCommand, using the provided ResumeCommand
func (t *RobotCommand) MergeResumeCommand(v ResumeCommand) error {
	v.CommandType = "RESUME"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmergencyStopCommand returns the union data inside the RobotCommand as a EmergencyStopCommand
func (t RobotCommand) AsEmergencyStopCommand() (EmergencyStopCommand, error) {
	var body EmergencyStopCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmergencyStopCommand overwrites any union data inside the RobotCommand as the provided EmergencyStopCommand
func (t *RobotCommand) FromEmergencyStopCommand(v EmergencyStopCommand) error {
	v.CommandType = "EMERGENCY_STOP"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmergencyStopCommand performs a merge with any union data inside the RobotCommand, using the provided EmergencyStopCommand
func (t *RobotCommand) MergeEmergencyStopCommand(v EmergencyStopCommand) error {
	v.CommandType = "EMERGENCY_STOP"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReturnToStartCommand returns the union data inside the RobotCommand as a ReturnToStartCommand
func (t RobotCommand) AsReturnToStartCommand() (ReturnToStartCommand, error) {
	var body ReturnToStartCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReturnToStartCommand overwrites any union data inside the RobotCommand as the provided ReturnToStartCommand
func (t *RobotCommand) FromReturnToStartCommand(v ReturnToStartCommand) error {
	v.CommandType = "RETURN_TO_START"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReturnToStartCommand performs a merge with any union data inside the RobotCommand, using the provided ReturnToStartCommand
func (t *RobotCommand) MergeReturnToStartCommand(v ReturnToStartCommand) error {
	v.CommandType = "RETURN_TO_START"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRebootCommand returns the union data inside the RobotCommand as a RebootCommand
func (t RobotCommand) AsRebootCommand() (RebootCommand, error) {
	var body RebootCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRebootCommand overwrites any union data inside the RobotCommand as the provided RebootCommand
func (t *RobotCommand) FromRebootCommand(v RebootCommand) error {
	v.CommandType = "REBOOT"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRebootCommand performs a merge with any union data inside the RobotCommand, using the provided RebootCommand
func (t *RobotCommand) MergeRebootCommand(v RebootCommand) error {
	v.CommandType = "REBOOT"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsShutdownCommand returns the union data inside the RobotCommand as a ShutdownCommand
func (t RobotCommand) AsShutdownCommand() (ShutdownCommand, error) {
	var body ShutdownCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromShutdownCommand overwrites any union data inside the RobotCommand as the provided ShutdownCommand
func (t *RobotCommand) FromShutdownCommand(v ShutdownCommand) error {
	v.CommandType = "SHUTDOWN"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeShutdownCommand performs a merge with any union data inside the RobotCommand, using the provided ShutdownCommand
func (t *RobotCommand) MergeShutdownCommand(v ShutdownCommand) error {
	v.CommandType = "SHUTDOWN"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetVisionDebugCommand returns the union data inside the RobotCommand as a SetVisionDebugCommand
func (t RobotCommand) AsSetVisionDebugCommand() (SetVisionDebugCommand, error) {
	var body SetVisionDebugCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetVisionDebugCommand overwrites any union data inside the RobotCommand as the provided SetVisionDebugCommand
func (t *RobotCommand) FromSetVisionDebugCommand(v SetVisionDebugCommand) error {
	v.CommandType = "SET_VISION_DEBUG"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetVisionDebugCommand performs a merge with any union data inside the RobotCommand, using the provided SetVisionDebugCommand
func (t *RobotCommand) MergeSetVisionDebugCommand(v SetVisionDebugCommand) error {
	v.CommandType = "SET_VISION_DEBUG"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDisableCommandChannelCommand returns the union data inside the RobotCommand as a DisableCommandChannelCommand
func (t RobotCommand) AsDisableCommandChannelCommand() (DisableCommandChannelCommand, error) {
	var body DisableCommandChannelCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDisableCommandChannelCommand overwrites any union data inside the RobotCommand as the provided DisableCommandChannelCommand
func (t *RobotCommand) FromDisableCommandChannelCommand(v DisableCommandChannelCommand) error {
	v.CommandType = "DISABLE_COMMAND_CHANNEL"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDisableCommandChannelCommand performs a merge with any union data inside the RobotCommand, using the provided DisableCommandChannelCommand
func (t *RobotCommand) MergeDisableCommandChannelCommand(v DisableCommandChannelCommand) error {
	v.CommandType = "DISABLE_COMMAND_CHANNEL"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetTelemetryChannelCommand returns the union data inside the RobotCommand as a SetTelemetryChannelCommand
func (t RobotCommand) AsSetTelemetryChannelCommand() (SetTelemetryChannelCommand, error) {
	var body SetTelemetryChannelCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetTelemetryChannelCommand overwrites any union data inside the RobotCommand as the provided SetTelemetryChannelCommand
func (t *RobotCommand) FromSetTelemetryChannelCommand(v SetTelemetryChannelCommand) error {
	v.CommandType = "SET_TELEMETRY_CHANNEL"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetTelemetryChannelCommand performs a merge with any union data inside the RobotCommand, using the provided SetTelemetryChannelCommand
func (t *RobotCommand) MergeSetTelemetryChannelCommand(v SetTelemetryChannelCommand) error {
	v.CommandType = "SET_TELEMETRY_CHANNEL"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RobotCommand) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"command_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RobotCommand) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DISABLE_COMMAND_CHANNEL":
		return t.AsDisableCommandChannelCommand()
	case "EMERGENCY_STOP":
		return t.AsEmergencyStopCommand()
	case "PAUSE":
		return t.AsPauseCommand()
	case "REBOOT":
		return t.AsRebootCommand()
	case "RESUME":
		return t.AsResumeCommand()
	case "RETURN_TO_START":
		return t.AsReturnToStartCommand()
	case "SET_TELEMETRY_CHANNEL":
		return t.AsSetTelemetryChannelCommand()
	case "SET_VISION_DEBUG":
		return t.AsSetVisionDebugCommand()
	case "SHUTDOWN":
		return t.AsShutdownCommand()
	case "START_RACE":
		return t.AsStartRaceCommand()
	case "STOP_RACE":
		return t.AsStopRaceCommand()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RobotCommand) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RobotCommand) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
