// Package robot provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package robot

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for RobotCommandCommandType.
const (
	EMERGENCYSTOP RobotCommandCommandType = "EMERGENCY_STOP"
	PAUSE         RobotCommandCommandType = "PAUSE"
	REBOOT        RobotCommandCommandType = "REBOOT"
	RESUME        RobotCommandCommandType = "RESUME"
	RETURNTOSTART RobotCommandCommandType = "RETURN_TO_START"
	SHUTDOWN      RobotCommandCommandType = "SHUTDOWN"
	STARTRACE     RobotCommandCommandType = "START_RACE"
	STOPRACE      RobotCommandCommandType = "STOP_RACE"
)

// Valid indicates whether the value is a known member of the RobotCommandCommandType enum.
func (e RobotCommandCommandType) Valid() bool {
	switch e {
	case EMERGENCYSTOP:
		return true
	case PAUSE:
		return true
	case REBOOT:
		return true
	case RESUME:
		return true
	case RETURNTOSTART:
		return true
	case SHUTDOWN:
		return true
	case STARTRACE:
		return true
	case STOPRACE:
		return true
	default:
		return false
	}
}

// Defines values for RobotCommandResponseStatus.
const (
	Accepted RobotCommandResponseStatus = "accepted"
	Queued   RobotCommandResponseStatus = "queued"
	Rejected RobotCommandResponseStatus = "rejected"
)

// Valid indicates whether the value is a known member of the RobotCommandResponseStatus enum.
func (e RobotCommandResponseStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Queued:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for RobotState.
const (
	BOOTCHECK RobotState = "BOOT_CHECK"
	ERROR     RobotState = "ERROR"
	FINISHED  RobotState = "FINISHED"
	OFFLINE   RobotState = "OFFLINE"
	RACING    RobotState = "RACING"
	READY     RobotState = "READY"
)

// Valid indicates whether the value is a known member of the RobotState enum.
func (e RobotState) Valid() bool {
	switch e {
	case BOOTCHECK:
		return true
	case ERROR:
		return true
	case FINISHED:
		return true
	case OFFLINE:
		return true
	case RACING:
		return true
	case READY:
		return true
	default:
		return false
	}
}

// BatteryStatus defines model for BatteryStatus.
type BatteryStatus struct {
	// Current Current draw in amps
	Current *float64 `json:"current,omitempty"`

	// StateOfCharge State of charge percentage
	StateOfCharge float64 `json:"state_of_charge"`

	// Voltage Battery voltage
	Voltage float64 `json:"voltage"`
}

// CreateRobotRequest defines model for CreateRobotRequest.
type CreateRobotRequest struct {
	FleetId openapi_types.UUID `binding:"required,uuid" json:"fleet_id"`
	Name    string             `binding:"required,max=255" json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Pose defines model for Pose.
type Pose struct {
	// X X position in meters
	X float64 `json:"x"`

	// Y Y position in meters
	Y float64 `json:"y"`

	// Yaw Orientation in radians
	Yaw float64 `json:"yaw"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// Robot defines model for Robot.
type Robot struct {
	CreatedAt time.Time          `json:"created_at"`
	FleetId   openapi_types.UUID `binding:"required,uuid" json:"fleet_id"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `binding:"required,max=255" json:"name"`
	State     RobotState         `json:"state"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// RobotCommand defines model for RobotCommand.
type RobotCommand struct {
	CommandType RobotCommandCommandType `json:"command_type"`
	Parameters  *map[string]interface{} `json:"parameters,omitempty"`
}

// RobotCommandCommandType defines model for RobotCommand.CommandType.
type RobotCommandCommandType string

// RobotCommandResponse defines model for RobotCommandResponse.
type RobotCommandResponse struct {
	CommandId openapi_types.UUID         `json:"command_id"`
	Message   *string                    `json:"message,omitempty"`
	Status    RobotCommandResponseStatus `json:"status"`
}

// RobotCommandResponseStatus defines model for RobotCommandResponse.Status.
type RobotCommandResponseStatus string

// RobotConfig defines model for RobotConfig.
type RobotConfig struct {
	// LookaheadDistance Pure pursuit lookahead in meters
	LookaheadDistance *float64 `json:"lookahead_distance,omitempty"`

	// MaxAngularSpeed Maximum angular speed in rad/s
	MaxAngularSpeed *float64 `json:"max_angular_speed,omitempty"`

	// MaxLinearSpeed Maximum linear speed in m/s
	MaxLinearSpeed *float64  `json:"max_linear_speed,omitempty"`
	SpeedProfiles  *[]string `json:"speed_profiles,omitempty"`

	// SteeringKp Steering PID proportional gain
	SteeringKp *float64 `json:"steering_kp,omitempty"`
}

// RobotState defines model for RobotState.
type RobotState string

// RobotStatus defines model for RobotStatus.
type RobotStatus struct {
	Battery      *BatteryStatus     `json:"battery,omitempty"`
	LapNumber    *int               `json:"lap_number,omitempty"`
	MissionName  *string            `json:"mission_name,omitempty"`
	Pose         Pose               `json:"pose"`
	RobotId      openapi_types.UUID `json:"robot_id"`
	State        RobotState         `json:"state"`
	SystemStatus SystemStatus       `json:"system_status"`
	Timestamp    time.Time          `json:"timestamp"`
	Velocity     Velocity           `json:"velocity"`
}

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	CameraReady *bool `json:"camera_ready,omitempty"`

	// CpuTemp CPU temperature in Celsius
	CpuTemp    *float64 `json:"cpu_temp,omitempty"`
	DriveReady *bool    `json:"drive_ready,omitempty"`
	ImuReady   *bool    `json:"imu_ready,omitempty"`
	LidarReady *bool    `json:"lidar_ready,omitempty"`

	// MotorTemps Motor temperatures in Celsius
	MotorTemps *[]float64 `json:"motor_temps,omitempty"`

	// RosNodesActive Number of active ROS nodes
	RosNodesActive *int `json:"ros_nodes_active,omitempty"`
}

// UpdateRobotConfigRequest defines model for UpdateRobotConfigRequest.
type UpdateRobotConfigRequest struct {
	LookaheadDistance *float64 `json:"lookahead_distance,omitempty"`
	MaxAngularSpeed   *float64 `json:"max_angular_speed,omitempty"`
	MaxLinearSpeed    *float64 `json:"max_linear_speed,omitempty"`
	SpeedProfile      *string  `json:"speed_profile,omitempty"`
	SteeringKp        *float64 `json:"steering_kp,omitempty"`
}

// UpdateRobotRequest defines model for UpdateRobotRequest.
type UpdateRobotRequest struct {
	Name *string `binding:"omitempty,max=255" json:"name,omitempty"`
}

// Velocity defines model for Velocity.
type Velocity struct {
	// Angular Angular velocity in rad/s
	Angular float64 `json:"angular"`

	// Linear Linear velocity in m/s
	Linear float64 `json:"linear"`
}

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ProblemDetails

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListRobotsParams defines parameters for ListRobots.
type ListRobotsParams struct {
	// FleetId Filter by fleet
	FleetId *openapi_types.UUID `form:"fleet_id,omitempty" json:"fleet_id,omitempty"`
	State   *RobotState         `form:"state,omitempty" json:"state,omitempty"`
}

// CreateRobotJSONRequestBody defines body for CreateRobot for application/json ContentType.
type CreateRobotJSONRequestBody = CreateRobotRequest

// UpdateRobotJSONRequestBody defines body for UpdateRobot for application/json ContentType.
type UpdateRobotJSONRequestBody = UpdateRobotRequest

// SendRobotCommandJSONRequestBody defines body for SendRobotCommand for application/json ContentType.
type SendRobotCommandJSONRequestBody = RobotCommand

// UpdateRobotConfigJSONRequestBody defines body for UpdateRobotConfig for application/json ContentType.
type UpdateRobotConfigJSONRequestBody = UpdateRobotConfigRequest
