baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Docs"
theme = "hugo-book"
defaultContentLanguage = "en"
enableGitInfo = true

[params]
BookTheme = "dark"
BookToC = true
BookSearch = true
BookRepo = "https://github.com/your/repo"
BookLogo = "logo.png"



[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

[outputs]
  home = ["HTML", "RSS", "JSON"]
