// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/state/v1/race_metrics.proto

package statev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RaceMetrics is the Go-stack replacement for /race_metrics, currently a
// std_msgs/String carrying the JSON of RaceMetricsWire (see
// src/ros2/wire_models.py). Published on the `vtitan.state.v1.race_metrics`
// NATS subject; produced by the state machine, consumed by the OLED display.
//
// That wire model's docstring is explicit that these field names are a
// cross-process contract -- a rename on one side is a silent break on the
// other, because a JSON lookup just misses. Converting that class of break
// into a `buf breaking` failure is the point of this schema.
//
// FIELD NAMES ARE CARRIED FROM THE PYTHON MODEL VERBATIM, without the _m/
// _mps/_rad suffixes used elsewhere in these protos. The producing node is
// not in platform/robot (RaceMetricsWire is defined but populated nowhere in
// this tree), so the units of current_steering and gyro_yaw could not be
// verified against a producer. Renaming them to assert a unit would be a
// guess of exactly the kind that made /motor/drive_speed read as RPM when it
// was actually deg/s. Measure against a real publisher, then rename and add
// range constraints in one change.
//
// target_laps is optional because the wire model distinguishes "the state
// machine has not published a target yet" from a real zero: the OLED falls
// back to its own lap target so the "n/3" line stays honest before the first
// real figure arrives. The other fields default to zero in Python and carry
// no such distinction, so they are plain.
type RaceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stamp         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	LapsCompleted int32                  `protobuf:"varint,2,opt,name=laps_completed,json=lapsCompleted,proto3" json:"laps_completed,omitempty"`
	TargetLaps    *int32                 `protobuf:"varint,3,opt,name=target_laps,json=targetLaps,proto3,oneof" json:"target_laps,omitempty"`
	// Seconds. The only unit here that is corroborated -- race_tracker.py's
	// RaceMetrics.elapsed_time documents the same quantity as seconds.
	TotalRaceTime float64 `protobuf:"fixed64,4,opt,name=total_race_time,json=totalRaceTime,proto3" json:"total_race_time,omitempty"`
	// Signed regardless of unit: the drivetrain reverses during escape
	// maneuvers, so a gte:0 bound would reject real frames.
	CurrentVelocity float64 `protobuf:"fixed64,5,opt,name=current_velocity,json=currentVelocity,proto3" json:"current_velocity,omitempty"`
	// Unit UNVERIFIED: normalized [-1, 1] per ports.DriveCommand, or radians.
	// Left unbounded rather than constrained to a guessed range.
	CurrentSteering float64 `protobuf:"fixed64,6,opt,name=current_steering,json=currentSteering,proto3" json:"current_steering,omitempty"`
	// Unit UNVERIFIED: radians or degrees. Same reasoning.
	GyroYaw float64 `protobuf:"fixed64,7,opt,name=gyro_yaw,json=gyroYaw,proto3" json:"gyro_yaw,omitempty"`
	// Empty until the navigator has classified a corridor. Typed as Section on
	// the producing side; carried as a string so state/v1 does not depend on
	// nav/v1 for one display field.
	CurrentCorridor string `protobuf:"bytes,8,opt,name=current_corridor,json=currentCorridor,proto3" json:"current_corridor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RaceMetrics) Reset() {
	*x = RaceMetrics{}
	mi := &file_vtitan_state_v1_race_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceMetrics) ProtoMessage() {}

func (x *RaceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_state_v1_race_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceMetrics.ProtoReflect.Descriptor instead.
func (*RaceMetrics) Descriptor() ([]byte, []int) {
	return file_vtitan_state_v1_race_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *RaceMetrics) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *RaceMetrics) GetLapsCompleted() int32 {
	if x != nil {
		return x.LapsCompleted
	}
	return 0
}

func (x *RaceMetrics) GetTargetLaps() int32 {
	if x != nil && x.TargetLaps != nil {
		return *x.TargetLaps
	}
	return 0
}

func (x *RaceMetrics) GetTotalRaceTime() float64 {
	if x != nil {
		return x.TotalRaceTime
	}
	return 0
}

func (x *RaceMetrics) GetCurrentVelocity() float64 {
	if x != nil {
		return x.CurrentVelocity
	}
	return 0
}

func (x *RaceMetrics) GetCurrentSteering() float64 {
	if x != nil {
		return x.CurrentSteering
	}
	return 0
}

func (x *RaceMetrics) GetGyroYaw() float64 {
	if x != nil {
		return x.GyroYaw
	}
	return 0
}

func (x *RaceMetrics) GetCurrentCorridor() string {
	if x != nil {
		return x.CurrentCorridor
	}
	return ""
}

var File_vtitan_state_v1_race_metrics_proto protoreflect.FileDescriptor

const file_vtitan_state_v1_race_metrics_proto_rawDesc = "" +
	"\n" +
	"\"vtitan/state/v1/race_metrics.proto\x12\x0fvtitan.state.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x03\n" +
	"\vRaceMetrics\x128\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x05stamp\x12.\n" +
	"\x0elaps_completed\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\rlapsCompleted\x12-\n" +
	"\vtarget_laps\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x00R\n" +
	"targetLaps\x88\x01\x01\x128\n" +
	"\x0ftotal_race_time\x18\x04 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00R\rtotalRaceTime\x122\n" +
	"\x10current_velocity\x18\x05 \x01(\x01B\a\xbaH\x04\x12\x02@\x01R\x0fcurrentVelocity\x122\n" +
	"\x10current_steering\x18\x06 \x01(\x01B\a\xbaH\x04\x12\x02@\x01R\x0fcurrentSteering\x12\"\n" +
	"\bgyro_yaw\x18\a \x01(\x01B\a\xbaH\x04\x12\x02@\x01R\agyroYaw\x12)\n" +
	"\x10current_corridor\x18\b \x01(\tR\x0fcurrentCorridorB\x0e\n" +
	"\f_target_lapsBMZKgithub.com/teamvoltimor/vtitan/platform/robot-go/internal/schema/pb/statev1b\x06proto3"

var (
	file_vtitan_state_v1_race_metrics_proto_rawDescOnce sync.Once
	file_vtitan_state_v1_race_metrics_proto_rawDescData []byte
)

func file_vtitan_state_v1_race_metrics_proto_rawDescGZIP() []byte {
	file_vtitan_state_v1_race_metrics_proto_rawDescOnce.Do(func() {
		file_vtitan_state_v1_race_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_state_v1_race_metrics_proto_rawDesc), len(file_vtitan_state_v1_race_metrics_proto_rawDesc)))
	})
	return file_vtitan_state_v1_race_metrics_proto_rawDescData
}

var file_vtitan_state_v1_race_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_state_v1_race_metrics_proto_goTypes = []any{
	(*RaceMetrics)(nil),           // 0: vtitan.state.v1.RaceMetrics
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_vtitan_state_v1_race_metrics_proto_depIdxs = []int32{
	1, // 0: vtitan.state.v1.RaceMetrics.stamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vtitan_state_v1_race_metrics_proto_init() }
func file_vtitan_state_v1_race_metrics_proto_init() {
	if File_vtitan_state_v1_race_metrics_proto != nil {
		return
	}
	file_vtitan_state_v1_race_metrics_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_state_v1_race_metrics_proto_rawDesc), len(file_vtitan_state_v1_race_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_state_v1_race_metrics_proto_goTypes,
		DependencyIndexes: file_vtitan_state_v1_race_metrics_proto_depIdxs,
		MessageInfos:      file_vtitan_state_v1_race_metrics_proto_msgTypes,
	}.Build()
	File_vtitan_state_v1_race_metrics_proto = out.File
	file_vtitan_state_v1_race_metrics_proto_goTypes = nil
	file_vtitan_state_v1_race_metrics_proto_depIdxs = nil
}
