package robotconfig

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

const generatedHeader = "Code generated by `simgen generate-robot-constants` from " +
	"platform/shared/config/robot.toml. DO NOT EDIT."

// f formats v as the shortest round-trippable float literal (e.g. 0.30 -> "0.3").
func f(v float64) string {
	return strconv.FormatFloat(v, 'g', -1, 64)
}

// GenerateGo renders cfg as a Go const block for package simconfig.
func GenerateGo(cfg *Config) (string, error) {
	var sb strings.Builder

	fmt.Fprintf(&sb, "// %s\n\n", generatedHeader)
	sb.WriteString("package simconfig\n\n")
	sb.WriteString("// Robot chassis dimensions (meters). LEGO Bugatti Bolide + Ackermann.\n")
	sb.WriteString("const (\n")
	fmt.Fprintf(&sb, "\tRobotLength      = %s\n", f(cfg.Chassis.Length))
	fmt.Fprintf(&sb, "\tRobotWidth       = %s\n", f(cfg.Chassis.Width))
	fmt.Fprintf(&sb, "\tRobotHeight      = %s\n", f(cfg.Chassis.Height))
	fmt.Fprintf(&sb, "\tRobotWheelbase   = %s\n", f(cfg.Ackermann.Wheelbase))
	fmt.Fprintf(&sb, "\tRobotTrackWidth  = %s\n", f(cfg.Ackermann.TrackWidth))
	fmt.Fprintf(&sb, "\tRobotWheelRadius = %s\n", f(cfg.Wheel.Radius))
	fmt.Fprintf(&sb, "\tRobotWheelWidth  = %s\n", f(cfg.Wheel.Width))
	fmt.Fprintf(&sb, "\tRobotMaxSteering = %s // ~30°\n", f(cfg.Ackermann.MaxSteeringAngle))
	fmt.Fprintf(&sb, "\tRobotChassisMass = %s // kg\n", f(cfg.Chassis.Mass))
	fmt.Fprintf(&sb, "\tRobotWheelMass   = %s // kg per wheel\n", f(cfg.Wheel.Mass))
	sb.WriteString("\n")
	sb.WriteString("\t// RobotLidarMountXOffset: chassis_length/2 - the lidar mesh's own radius (0.0278,\n")
	sb.WriteString("\t// matching wro_robot.urdf.xacro's lidar_link visual/collision cylinder) — the C1\n")
	sb.WriteString("\t// mounted flush with the front edge, centered left/right, upside-down.\n")
	fmt.Fprintf(&sb, "\tRobotLidarMountXOffset = %s\n", f(cfg.Lidar.MountXOffset))
	sb.WriteString("\n")
	sb.WriteString("\t// Camera mounted directly over the LIDAR, tilted down.\n")
	fmt.Fprintf(&sb, "\tRobotCameraMountXOffset = %s\n", f(cfg.Camera.MountXOffset))
	fmt.Fprintf(&sb, "\tRobotCameraMountZOffset = %s\n", f(cfg.Camera.MountZOffset))
	fmt.Fprintf(&sb, "\tRobotCameraPitchRad     = %s // ~30°, tilted down\n", f(cfg.Camera.MountPitch))
	sb.WriteString(")\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return "", fmt.Errorf("format generated go source: %w", err)
	}

	return string(formatted), nil
}

// GenerateXacro renders cfg as a property-only xacro fragment, meant to be pulled in via
// `xacro:include` from wro_robot.urdf.xacro.
func GenerateXacro(cfg *Config) string {
	var sb strings.Builder

	sb.WriteString("<?xml version=\"1.0\"?>\n")
	fmt.Fprintf(&sb, "<!-- %s -->\n", generatedHeader)
	sb.WriteString("<robot xmlns:xacro=\"http://www.ros.org/wiki/xacro\">\n\n")

	sb.WriteString("  <!-- Chassis properties (LEGO Bugatti Bolide) -->\n")
	fmt.Fprintf(&sb, "  <xacro:property name=\"chassis_length\" value=\"%s\"/>\n", f(cfg.Chassis.Length))
	fmt.Fprintf(&sb, "  <xacro:property name=\"chassis_width\" value=\"%s\"/>\n", f(cfg.Chassis.Width))
	fmt.Fprintf(&sb, "  <xacro:property name=\"chassis_height\" value=\"%s\"/>\n", f(cfg.Chassis.Height))
	fmt.Fprintf(&sb, "  <xacro:property name=\"chassis_mass\" value=\"%s\"/>\n\n", f(cfg.Chassis.Mass))

	sb.WriteString("  <!-- Ackermann geometry -->\n")
	fmt.Fprintf(&sb, "  <xacro:property name=\"wheelbase\" value=\"%s\"/>\n", f(cfg.Ackermann.Wheelbase))
	fmt.Fprintf(&sb, "  <xacro:property name=\"track_width\" value=\"%s\"/>\n", f(cfg.Ackermann.TrackWidth))
	fmt.Fprintf(
		&sb,
		"  <xacro:property name=\"max_steering_angle\" value=\"%s\"/>\n\n",
		f(cfg.Ackermann.MaxSteeringAngle),
	)

	sb.WriteString("  <!-- Wheel properties -->\n")
	fmt.Fprintf(&sb, "  <xacro:property name=\"wheel_radius\" value=\"%s\"/>\n", f(cfg.Wheel.Radius))
	fmt.Fprintf(&sb, "  <xacro:property name=\"wheel_width\" value=\"%s\"/>\n", f(cfg.Wheel.Width))
	fmt.Fprintf(&sb, "  <xacro:property name=\"wheel_mass\" value=\"%s\"/>\n\n", f(cfg.Wheel.Mass))

	sb.WriteString("  <!-- Sensor mount offsets -->\n")
	fmt.Fprintf(&sb, "  <xacro:property name=\"lidar_mount_x\" value=\"%s\"/>\n", f(cfg.Lidar.MountXOffset))
	fmt.Fprintf(&sb, "  <xacro:property name=\"camera_mount_x\" value=\"%s\"/>\n", f(cfg.Camera.MountXOffset))
	fmt.Fprintf(&sb, "  <xacro:property name=\"camera_mount_z\" value=\"%s\"/>\n", f(cfg.Camera.MountZOffset))
	fmt.Fprintf(&sb, "  <xacro:property name=\"camera_mount_pitch\" value=\"%s\"/>\n", f(cfg.Camera.MountPitch))

	sb.WriteString("\n</robot>\n")

	return sb.String()
}

// GeneratePython renders cfg as a Python module of module-level Final constants, meant to
// be imported by shared/config/constants.py's RobotSpecs class.
func GeneratePython(cfg *Config) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "\"\"\"%s\"\"\"\n\n", generatedHeader)
	sb.WriteString("from __future__ import annotations\n\n")
	sb.WriteString("from typing import Final\n\n")

	sb.WriteString("# Chassis (meters, kg)\n")
	fmt.Fprintf(&sb, "CHASSIS_LENGTH: Final[float] = %s\n", f(cfg.Chassis.Length))
	fmt.Fprintf(&sb, "CHASSIS_WIDTH: Final[float] = %s\n", f(cfg.Chassis.Width))
	fmt.Fprintf(&sb, "CHASSIS_HEIGHT: Final[float] = %s\n", f(cfg.Chassis.Height))
	fmt.Fprintf(&sb, "CHASSIS_MASS: Final[float] = %s\n\n", f(cfg.Chassis.Mass))

	sb.WriteString("# Ackermann geometry (meters, radians)\n")
	fmt.Fprintf(&sb, "WHEELBASE: Final[float] = %s\n", f(cfg.Ackermann.Wheelbase))
	fmt.Fprintf(&sb, "TRACK_WIDTH: Final[float] = %s\n", f(cfg.Ackermann.TrackWidth))
	fmt.Fprintf(&sb, "MAX_STEERING_ANGLE: Final[float] = %s\n\n", f(cfg.Ackermann.MaxSteeringAngle))

	sb.WriteString("# Wheel (meters, kg)\n")
	fmt.Fprintf(&sb, "WHEEL_RADIUS: Final[float] = %s\n", f(cfg.Wheel.Radius))
	fmt.Fprintf(&sb, "WHEEL_WIDTH: Final[float] = %s\n", f(cfg.Wheel.Width))
	fmt.Fprintf(&sb, "WHEEL_MASS: Final[float] = %s\n\n", f(cfg.Wheel.Mass))

	sb.WriteString("# LIDAR mount (meters)\n")
	fmt.Fprintf(&sb, "LIDAR_MOUNT_X_OFFSET: Final[float] = %s\n\n", f(cfg.Lidar.MountXOffset))

	sb.WriteString("# Camera mount (meters, radians)\n")
	fmt.Fprintf(&sb, "CAMERA_MOUNT_X_OFFSET: Final[float] = %s\n", f(cfg.Camera.MountXOffset))
	fmt.Fprintf(&sb, "CAMERA_MOUNT_Z_OFFSET: Final[float] = %s\n", f(cfg.Camera.MountZOffset))
	fmt.Fprintf(&sb, "CAMERA_MOUNT_PITCH_RAD: Final[float] = %s\n", f(cfg.Camera.MountPitch))

	return sb.String()
}
