// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/nav/v1/navigator_debug.proto

package navv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Phase identifies which branch of the navigator's step() produced a
// snapshot, and so which of NavigatorDebug's groups are populated. Mirrors
// shared.domain.enums.NavigatorPhase.
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED            Phase = 0
	Phase_PHASE_NOT_YET_STEPPED        Phase = 1
	Phase_PHASE_NO_POSE                Phase = 2
	Phase_PHASE_BLIND_CREEP            Phase = 3
	Phase_PHASE_ACTIVE_MANEUVER        Phase = 4
	Phase_PHASE_STUCK_ESCAPE_HOLDING   Phase = 5
	Phase_PHASE_STUCK_ESCAPE_MANEUVER  Phase = 6
	Phase_PHASE_FINISHED_HOLD          Phase = 7
	Phase_PHASE_PARKING                Phase = 8
	Phase_PHASE_WAYPOINT_WRAP_FALLBACK Phase = 9
	Phase_PHASE_WAYPOINT_REACHED       Phase = 10
	Phase_PHASE_NORMAL_DRIVE           Phase = 11
	Phase_PHASE_ESCAPE_TRIGGERED       Phase = 12
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0:  "PHASE_UNSPECIFIED",
		1:  "PHASE_NOT_YET_STEPPED",
		2:  "PHASE_NO_POSE",
		3:  "PHASE_BLIND_CREEP",
		4:  "PHASE_ACTIVE_MANEUVER",
		5:  "PHASE_STUCK_ESCAPE_HOLDING",
		6:  "PHASE_STUCK_ESCAPE_MANEUVER",
		7:  "PHASE_FINISHED_HOLD",
		8:  "PHASE_PARKING",
		9:  "PHASE_WAYPOINT_WRAP_FALLBACK",
		10: "PHASE_WAYPOINT_REACHED",
		11: "PHASE_NORMAL_DRIVE",
		12: "PHASE_ESCAPE_TRIGGERED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":            0,
		"PHASE_NOT_YET_STEPPED":        1,
		"PHASE_NO_POSE":                2,
		"PHASE_BLIND_CREEP":            3,
		"PHASE_ACTIVE_MANEUVER":        4,
		"PHASE_STUCK_ESCAPE_HOLDING":   5,
		"PHASE_STUCK_ESCAPE_MANEUVER":  6,
		"PHASE_FINISHED_HOLD":          7,
		"PHASE_PARKING":                8,
		"PHASE_WAYPOINT_WRAP_FALLBACK": 9,
		"PHASE_WAYPOINT_REACHED":       10,
		"PHASE_NORMAL_DRIVE":           11,
		"PHASE_ESCAPE_TRIGGERED":       12,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_nav_v1_navigator_debug_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_vtitan_nav_v1_navigator_debug_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{0}
}

// Direction is the travel direction around the loop. Mirrors Direction.
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED      Direction = 0
	Direction_DIRECTION_CLOCKWISE        Direction = 1
	Direction_DIRECTION_COUNTERCLOCKWISE Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_CLOCKWISE",
		2: "DIRECTION_COUNTERCLOCKWISE",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED":      0,
		"DIRECTION_CLOCKWISE":        1,
		"DIRECTION_COUNTERCLOCKWISE": 2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_nav_v1_navigator_debug_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_vtitan_nav_v1_navigator_debug_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{1}
}

// Section is which side of the mat a position falls on. Mirrors Section.
type Section int32

const (
	Section_SECTION_UNSPECIFIED Section = 0
	Section_SECTION_NORTH       Section = 1
	Section_SECTION_SOUTH       Section = 2
	Section_SECTION_EAST        Section = 3
	Section_SECTION_WEST        Section = 4
)

// Enum value maps for Section.
var (
	Section_name = map[int32]string{
		0: "SECTION_UNSPECIFIED",
		1: "SECTION_NORTH",
		2: "SECTION_SOUTH",
		3: "SECTION_EAST",
		4: "SECTION_WEST",
	}
	Section_value = map[string]int32{
		"SECTION_UNSPECIFIED": 0,
		"SECTION_NORTH":       1,
		"SECTION_SOUTH":       2,
		"SECTION_EAST":        3,
		"SECTION_WEST":        4,
	}
)

func (x Section) Enum() *Section {
	p := new(Section)
	*p = x
	return p
}

func (x Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Section) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_nav_v1_navigator_debug_proto_enumTypes[2].Descriptor()
}

func (Section) Type() protoreflect.EnumType {
	return &file_vtitan_nav_v1_navigator_debug_proto_enumTypes[2]
}

func (x Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Section.Descriptor instead.
func (Section) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{2}
}

// RiskLevel is a collision-risk reading. Mirrors RiskLevel.
type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_SAFE        RiskLevel = 1
	RiskLevel_RISK_LEVEL_OBSTACLE    RiskLevel = 2
	RiskLevel_RISK_LEVEL_CRITICAL    RiskLevel = 3
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_SAFE",
		2: "RISK_LEVEL_OBSTACLE",
		3: "RISK_LEVEL_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_SAFE":        1,
		"RISK_LEVEL_OBSTACLE":    2,
		"RISK_LEVEL_CRITICAL":    3,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_nav_v1_navigator_debug_proto_enumTypes[3].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_vtitan_nav_v1_navigator_debug_proto_enumTypes[3]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{3}
}

// ManeuverType is the kind of escape maneuver commanded. Mirrors
// ManeuverType.
type ManeuverType int32

const (
	ManeuverType_MANEUVER_TYPE_UNSPECIFIED     ManeuverType = 0
	ManeuverType_MANEUVER_TYPE_K_TURN          ManeuverType = 1
	ManeuverType_MANEUVER_TYPE_SIDE_CORRECTION ManeuverType = 2
	ManeuverType_MANEUVER_TYPE_STUCK_REVERSE   ManeuverType = 3
	ManeuverType_MANEUVER_TYPE_STUCK_FORWARD   ManeuverType = 4
)

// Enum value maps for ManeuverType.
var (
	ManeuverType_name = map[int32]string{
		0: "MANEUVER_TYPE_UNSPECIFIED",
		1: "MANEUVER_TYPE_K_TURN",
		2: "MANEUVER_TYPE_SIDE_CORRECTION",
		3: "MANEUVER_TYPE_STUCK_REVERSE",
		4: "MANEUVER_TYPE_STUCK_FORWARD",
	}
	ManeuverType_value = map[string]int32{
		"MANEUVER_TYPE_UNSPECIFIED":     0,
		"MANEUVER_TYPE_K_TURN":          1,
		"MANEUVER_TYPE_SIDE_CORRECTION": 2,
		"MANEUVER_TYPE_STUCK_REVERSE":   3,
		"MANEUVER_TYPE_STUCK_FORWARD":   4,
	}
)

func (x ManeuverType) Enum() *ManeuverType {
	p := new(ManeuverType)
	*p = x
	return p
}

func (x ManeuverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManeuverType) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_nav_v1_navigator_debug_proto_enumTypes[4].Descriptor()
}

func (ManeuverType) Type() protoreflect.EnumType {
	return &file_vtitan_nav_v1_navigator_debug_proto_enumTypes[4]
}

func (x ManeuverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManeuverType.Descriptor instead.
func (ManeuverType) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{4}
}

// ParkPhase is a parking maneuver phase. Mirrors ParkPhase.
type ParkPhase int32

const (
	ParkPhase_PARK_PHASE_UNSPECIFIED ParkPhase = 0
	ParkPhase_PARK_PHASE_STAGE       ParkPhase = 1
	ParkPhase_PARK_PHASE_ENTER       ParkPhase = 2
	ParkPhase_PARK_PHASE_DONE        ParkPhase = 3
)

// Enum value maps for ParkPhase.
var (
	ParkPhase_name = map[int32]string{
		0: "PARK_PHASE_UNSPECIFIED",
		1: "PARK_PHASE_STAGE",
		2: "PARK_PHASE_ENTER",
		3: "PARK_PHASE_DONE",
	}
	ParkPhase_value = map[string]int32{
		"PARK_PHASE_UNSPECIFIED": 0,
		"PARK_PHASE_STAGE":       1,
		"PARK_PHASE_ENTER":       2,
		"PARK_PHASE_DONE":        3,
	}
)

func (x ParkPhase) Enum() *ParkPhase {
	p := new(ParkPhase)
	*p = x
	return p
}

func (x ParkPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParkPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_nav_v1_navigator_debug_proto_enumTypes[5].Descriptor()
}

func (ParkPhase) Type() protoreflect.EnumType {
	return &file_vtitan_nav_v1_navigator_debug_proto_enumTypes[5]
}

func (x ParkPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParkPhase.Descriptor instead.
func (ParkPhase) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{5}
}

// NavigatorPose is the localizer's estimate this tick, absent only on the
// NO_POSE phase. Grouped because the three components are set together or
// not at all.
//
// Deliberately constrained to finite rather than to the mat's bounds: a pose
// outside the track is exactly the failure this topic exists to record, and
// a range constraint would reject the most diagnostic messages in the bag.
type NavigatorPose struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	X     float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	// Not bounded to [-pi, pi]: callers may record an unwrapped heading, and
	// rejecting that would lose the reading rather than reveal the bug.
	Yaw           float64 `protobuf:"fixed64,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigatorPose) Reset() {
	*x = NavigatorPose{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigatorPose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigatorPose) ProtoMessage() {}

func (x *NavigatorPose) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigatorPose.ProtoReflect.Descriptor instead.
func (*NavigatorPose) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{0}
}

func (x *NavigatorPose) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NavigatorPose) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NavigatorPose) GetYaw() float64 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

// RaceState is progress around the loop.
type RaceState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Direction       Direction              `protobuf:"varint,1,opt,name=direction,proto3,enum=vtitan.nav.v1.Direction" json:"direction,omitempty"`
	CurrentCorridor Section                `protobuf:"varint,2,opt,name=current_corridor,json=currentCorridor,proto3,enum=vtitan.nav.v1.Section" json:"current_corridor,omitempty"`
	WaypointIndex   *int32                 `protobuf:"varint,3,opt,name=waypoint_index,json=waypointIndex,proto3,oneof" json:"waypoint_index,omitempty"`
	LapsCompleted   int32                  `protobuf:"varint,4,opt,name=laps_completed,json=lapsCompleted,proto3" json:"laps_completed,omitempty"`
	NumLaps         int32                  `protobuf:"varint,5,opt,name=num_laps,json=numLaps,proto3" json:"num_laps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RaceState) Reset() {
	*x = RaceState{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceState) ProtoMessage() {}

func (x *RaceState) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceState.ProtoReflect.Descriptor instead.
func (*RaceState) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{1}
}

func (x *RaceState) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *RaceState) GetCurrentCorridor() Section {
	if x != nil {
		return x.CurrentCorridor
	}
	return Section_SECTION_UNSPECIFIED
}

func (x *RaceState) GetWaypointIndex() int32 {
	if x != nil && x.WaypointIndex != nil {
		return *x.WaypointIndex
	}
	return 0
}

func (x *RaceState) GetLapsCompleted() int32 {
	if x != nil {
		return x.LapsCompleted
	}
	return 0
}

func (x *RaceState) GetNumLaps() int32 {
	if x != nil {
		return x.NumLaps
	}
	return 0
}

// StuckDetection mirrors StuckDetector.get_diagnostics, present whenever the
// detector ran this tick. It does not run once the robot has reached its
// final deliberate stop, so this group is absent on FINISHED_HOLD.
type StuckDetection struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	IsStuck    *bool                  `protobuf:"varint,1,opt,name=is_stuck,json=isStuck,proto3,oneof" json:"is_stuck,omitempty"`
	StuckCount *int32                 `protobuf:"varint,2,opt,name=stuck_count,json=stuckCount,proto3,oneof" json:"stuck_count,omitempty"`
	// A distance travelled, so never negative.
	RecentMovementM *float64 `protobuf:"fixed64,3,opt,name=recent_movement_m,json=recentMovementM,proto3,oneof" json:"recent_movement_m,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StuckDetection) Reset() {
	*x = StuckDetection{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StuckDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuckDetection) ProtoMessage() {}

func (x *StuckDetection) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuckDetection.ProtoReflect.Descriptor instead.
func (*StuckDetection) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{2}
}

func (x *StuckDetection) GetIsStuck() bool {
	if x != nil && x.IsStuck != nil {
		return *x.IsStuck
	}
	return false
}

func (x *StuckDetection) GetStuckCount() int32 {
	if x != nil && x.StuckCount != nil {
		return *x.StuckCount
	}
	return 0
}

func (x *StuckDetection) GetRecentMovementM() float64 {
	if x != nil && x.RecentMovementM != nil {
		return *x.RecentMovementM
	}
	return 0
}

// Perception is the LIDAR-derived picture one tick works from.
//
// The two risk readings are deliberate and not redundant: `risk` is measured
// on the RAW scan and governs how fast the robot may go, while `escape_risk`
// is measured on the mapped-obstacle-masked scan and governs whether the
// escape maneuver fires. A sign being routed around is passed inside contact
// distance by design, so on the raw scan alone the escape would fire at
// every sign pass.
type Perception struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ForwardClearanceM *float64               `protobuf:"fixed64,1,opt,name=forward_clearance_m,json=forwardClearanceM,proto3,oneof" json:"forward_clearance_m,omitempty"`
	MinLidarRangeM    *float64               `protobuf:"fixed64,2,opt,name=min_lidar_range_m,json=minLidarRangeM,proto3,oneof" json:"min_lidar_range_m,omitempty"`
	Risk              RiskLevel              `protobuf:"varint,3,opt,name=risk,proto3,enum=vtitan.nav.v1.RiskLevel" json:"risk,omitempty"`
	EscapeRisk        RiskLevel              `protobuf:"varint,4,opt,name=escape_risk,json=escapeRisk,proto3,enum=vtitan.nav.v1.RiskLevel" json:"escape_risk,omitempty"`
	RearClearanceM    *float64               `protobuf:"fixed64,5,opt,name=rear_clearance_m,json=rearClearanceM,proto3,oneof" json:"rear_clearance_m,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Perception) Reset() {
	*x = Perception{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Perception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perception) ProtoMessage() {}

func (x *Perception) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perception.ProtoReflect.Descriptor instead.
func (*Perception) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{3}
}

func (x *Perception) GetForwardClearanceM() float64 {
	if x != nil && x.ForwardClearanceM != nil {
		return *x.ForwardClearanceM
	}
	return 0
}

func (x *Perception) GetMinLidarRangeM() float64 {
	if x != nil && x.MinLidarRangeM != nil {
		return *x.MinLidarRangeM
	}
	return 0
}

func (x *Perception) GetRisk() RiskLevel {
	if x != nil {
		return x.Risk
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *Perception) GetEscapeRisk() RiskLevel {
	if x != nil {
		return x.EscapeRisk
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *Perception) GetRearClearanceM() float64 {
	if x != nil && x.RearClearanceM != nil {
		return *x.RearClearanceM
	}
	return 0
}

// PathTracking is how well the robot is following the planned path, and
// which target it chose. Set on the NORMAL_DRIVE phase.
//
// Several of these cannot be reconstructed from /motor/* and /imu/data after
// the fact at all, which is why the debug topic exists.
type PathTracking struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed: which side of the path the robot is on is the whole point.
	CrosstrackErrorM   *float64 `protobuf:"fixed64,1,opt,name=crosstrack_error_m,json=crosstrackErrorM,proto3,oneof" json:"crosstrack_error_m,omitempty"`
	LookaheadDistanceM *float64 `protobuf:"fixed64,2,opt,name=lookahead_distance_m,json=lookaheadDistanceM,proto3,oneof" json:"lookahead_distance_m,omitempty"`
	// Heading change the planned path makes within the preview distance: ~0 on
	// a straight, rising before a corner, so a bag shows whether the short
	// lookahead armed on entry or a corner late.
	PathTurnAheadRad *float64 `protobuf:"fixed64,3,opt,name=path_turn_ahead_rad,json=pathTurnAheadRad,proto3,oneof" json:"path_turn_ahead_rad,omitempty"`
	SteerTargetX     *float64 `protobuf:"fixed64,4,opt,name=steer_target_x,json=steerTargetX,proto3,oneof" json:"steer_target_x,omitempty"`
	SteerTargetY     *float64 `protobuf:"fixed64,5,opt,name=steer_target_y,json=steerTargetY,proto3,oneof" json:"steer_target_y,omitempty"`
	AngleErrorRad    *float64 `protobuf:"fixed64,6,opt,name=angle_error_rad,json=angleErrorRad,proto3,oneof" json:"angle_error_rad,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PathTracking) Reset() {
	*x = PathTracking{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTracking) ProtoMessage() {}

func (x *PathTracking) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTracking.ProtoReflect.Descriptor instead.
func (*PathTracking) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{4}
}

func (x *PathTracking) GetCrosstrackErrorM() float64 {
	if x != nil && x.CrosstrackErrorM != nil {
		return *x.CrosstrackErrorM
	}
	return 0
}

func (x *PathTracking) GetLookaheadDistanceM() float64 {
	if x != nil && x.LookaheadDistanceM != nil {
		return *x.LookaheadDistanceM
	}
	return 0
}

func (x *PathTracking) GetPathTurnAheadRad() float64 {
	if x != nil && x.PathTurnAheadRad != nil {
		return *x.PathTurnAheadRad
	}
	return 0
}

func (x *PathTracking) GetSteerTargetX() float64 {
	if x != nil && x.SteerTargetX != nil {
		return *x.SteerTargetX
	}
	return 0
}

func (x *PathTracking) GetSteerTargetY() float64 {
	if x != nil && x.SteerTargetY != nil {
		return *x.SteerTargetY
	}
	return 0
}

func (x *PathTracking) GetAngleErrorRad() float64 {
	if x != nil && x.AngleErrorRad != nil {
		return *x.AngleErrorRad
	}
	return 0
}

// SpeedSelection is the two candidate speeds the speed controller chose
// between. Set on the NORMAL_DRIVE phase. Both are magnitudes, so neither is
// signed even though the final command can be.
type SpeedSelection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClearanceSpeedMps *float64               `protobuf:"fixed64,1,opt,name=clearance_speed_mps,json=clearanceSpeedMps,proto3,oneof" json:"clearance_speed_mps,omitempty"`
	HeadingSpeedMps   *float64               `protobuf:"fixed64,2,opt,name=heading_speed_mps,json=headingSpeedMps,proto3,oneof" json:"heading_speed_mps,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeedSelection) Reset() {
	*x = SpeedSelection{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedSelection) ProtoMessage() {}

func (x *SpeedSelection) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedSelection.ProtoReflect.Descriptor instead.
func (*SpeedSelection) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{5}
}

func (x *SpeedSelection) GetClearanceSpeedMps() float64 {
	if x != nil && x.ClearanceSpeedMps != nil {
		return *x.ClearanceSpeedMps
	}
	return 0
}

func (x *SpeedSelection) GetHeadingSpeedMps() float64 {
	if x != nil && x.HeadingSpeedMps != nil {
		return *x.HeadingSpeedMps
	}
	return 0
}

// DriveCommand is what was actually published, set on every phase that
// publishes one -- including the stop branches, where zeroes are a
// deliberate command rather than an absent value.
type DriveCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed, NOT bounded below at zero: escape maneuvers reverse.
	SpeedMps *float64 `protobuf:"fixed64,1,opt,name=speed_mps,json=speedMps,proto3,oneof" json:"speed_mps,omitempty"`
	// The port contract is [-1, 1], + = left. A value outside it is a bug in
	// the producer, so reject rather than record it.
	SteeringNorm  *float64 `protobuf:"fixed64,2,opt,name=steering_norm,json=steeringNorm,proto3,oneof" json:"steering_norm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveCommand) Reset() {
	*x = DriveCommand{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveCommand) ProtoMessage() {}

func (x *DriveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveCommand.ProtoReflect.Descriptor instead.
func (*DriveCommand) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{6}
}

func (x *DriveCommand) GetSpeedMps() float64 {
	if x != nil && x.SpeedMps != nil {
		return *x.SpeedMps
	}
	return 0
}

func (x *DriveCommand) GetSteeringNorm() float64 {
	if x != nil && x.SteeringNorm != nil {
		return *x.SteeringNorm
	}
	return 0
}

// Maneuver is the escape/stuck maneuver state, present whenever one is
// latched or begun.
type Maneuver struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ActiveType ManeuverType           `protobuf:"varint,1,opt,name=active_type,json=activeType,proto3,enum=vtitan.nav.v1.ManeuverType" json:"active_type,omitempty"`
	Steering   *float64               `protobuf:"fixed64,2,opt,name=steering,proto3,oneof" json:"steering,omitempty"`
	// Signed: a reverse maneuver is the common case.
	SpeedMps   *float64 `protobuf:"fixed64,3,opt,name=speed_mps,json=speedMps,proto3,oneof" json:"speed_mps,omitempty"`
	FramesLeft *int32   `protobuf:"varint,4,opt,name=frames_left,json=framesLeft,proto3,oneof" json:"frames_left,omitempty"`
	// escape_count is escapes begun since the last normal drive tick with real
	// progress, so it escalates within a sequence rather than counting the
	// whole race.
	EscapeCount   *int32 `protobuf:"varint,5,opt,name=escape_count,json=escapeCount,proto3,oneof" json:"escape_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maneuver) Reset() {
	*x = Maneuver{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maneuver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maneuver) ProtoMessage() {}

func (x *Maneuver) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maneuver.ProtoReflect.Descriptor instead.
func (*Maneuver) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{7}
}

func (x *Maneuver) GetActiveType() ManeuverType {
	if x != nil {
		return x.ActiveType
	}
	return ManeuverType_MANEUVER_TYPE_UNSPECIFIED
}

func (x *Maneuver) GetSteering() float64 {
	if x != nil && x.Steering != nil {
		return *x.Steering
	}
	return 0
}

func (x *Maneuver) GetSpeedMps() float64 {
	if x != nil && x.SpeedMps != nil {
		return *x.SpeedMps
	}
	return 0
}

func (x *Maneuver) GetFramesLeft() int32 {
	if x != nil && x.FramesLeft != nil {
		return *x.FramesLeft
	}
	return 0
}

func (x *Maneuver) GetEscapeCount() int32 {
	if x != nil && x.EscapeCount != nil {
		return *x.EscapeCount
	}
	return 0
}

// Parking is the parking maneuver state. No Go counterpart yet (the port has
// no ParkController), carried so a Python-recorded bag round-trips through
// this schema without loss.
type Parking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engaged       *bool                  `protobuf:"varint,1,opt,name=engaged,proto3,oneof" json:"engaged,omitempty"`
	Phase         ParkPhase              `protobuf:"varint,2,opt,name=phase,proto3,enum=vtitan.nav.v1.ParkPhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parking) Reset() {
	*x = Parking{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parking) ProtoMessage() {}

func (x *Parking) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parking.ProtoReflect.Descriptor instead.
func (*Parking) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{8}
}

func (x *Parking) GetEngaged() bool {
	if x != nil && x.Engaged != nil {
		return *x.Engaged
	}
	return false
}

func (x *Parking) GetPhase() ParkPhase {
	if x != nil {
		return x.Phase
	}
	return ParkPhase_PARK_PHASE_UNSPECIFIED
}

// SignRouting is Obstacles Challenge traffic-sign routing, present on the
// NORMAL_DRIVE phase whenever a SignRouter is attached.
type SignRouting struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActiveSignCount  *int32                 `protobuf:"varint,1,opt,name=active_sign_count,json=activeSignCount,proto3,oneof" json:"active_sign_count,omitempty"`
	DeformMagnitudeM *float64               `protobuf:"fixed64,2,opt,name=deform_magnitude_m,json=deformMagnitudeM,proto3,oneof" json:"deform_magnitude_m,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignRouting) Reset() {
	*x = SignRouting{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRouting) ProtoMessage() {}

func (x *SignRouting) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRouting.ProtoReflect.Descriptor instead.
func (*SignRouting) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{9}
}

func (x *SignRouting) GetActiveSignCount() int32 {
	if x != nil && x.ActiveSignCount != nil {
		return *x.ActiveSignCount
	}
	return 0
}

func (x *SignRouting) GetDeformMagnitudeM() float64 {
	if x != nil && x.DeformMagnitudeM != nil {
		return *x.DeformMagnitudeM
	}
	return 0
}

// BlindCreep is direction inference before the travel direction has settled,
// present only on the BLIND_CREEP phase. No Go counterpart yet.
type BlindCreep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Free-form rather than an enum: the Python side writes a human-readable
	// gate verdict, not a closed set.
	GateVerdict           *string  `protobuf:"bytes,1,opt,name=gate_verdict,json=gateVerdict,proto3,oneof" json:"gate_verdict,omitempty"`
	LeftRangeM            *float64 `protobuf:"fixed64,2,opt,name=left_range_m,json=leftRangeM,proto3,oneof" json:"left_range_m,omitempty"`
	RightRangeM           *float64 `protobuf:"fixed64,3,opt,name=right_range_m,json=rightRangeM,proto3,oneof" json:"right_range_m,omitempty"`
	VotesClockwise        *int32   `protobuf:"varint,4,opt,name=votes_clockwise,json=votesClockwise,proto3,oneof" json:"votes_clockwise,omitempty"`
	VotesCounterclockwise *int32   `protobuf:"varint,5,opt,name=votes_counterclockwise,json=votesCounterclockwise,proto3,oneof" json:"votes_counterclockwise,omitempty"`
	CorridorWidthBeliefM  *float64 `protobuf:"fixed64,6,opt,name=corridor_width_belief_m,json=corridorWidthBeliefM,proto3,oneof" json:"corridor_width_belief_m,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BlindCreep) Reset() {
	*x = BlindCreep{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlindCreep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindCreep) ProtoMessage() {}

func (x *BlindCreep) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindCreep.ProtoReflect.Descriptor instead.
func (*BlindCreep) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{10}
}

func (x *BlindCreep) GetGateVerdict() string {
	if x != nil && x.GateVerdict != nil {
		return *x.GateVerdict
	}
	return ""
}

func (x *BlindCreep) GetLeftRangeM() float64 {
	if x != nil && x.LeftRangeM != nil {
		return *x.LeftRangeM
	}
	return 0
}

func (x *BlindCreep) GetRightRangeM() float64 {
	if x != nil && x.RightRangeM != nil {
		return *x.RightRangeM
	}
	return 0
}

func (x *BlindCreep) GetVotesClockwise() int32 {
	if x != nil && x.VotesClockwise != nil {
		return *x.VotesClockwise
	}
	return 0
}

func (x *BlindCreep) GetVotesCounterclockwise() int32 {
	if x != nil && x.VotesCounterclockwise != nil {
		return *x.VotesCounterclockwise
	}
	return 0
}

func (x *BlindCreep) GetCorridorWidthBeliefM() float64 {
	if x != nil && x.CorridorWidthBeliefM != nil {
		return *x.CorridorWidthBeliefM
	}
	return 0
}

// NavigatorDebug is the Go-stack replacement for the current /nav_debug
// topic, which is a std_msgs/String carrying pydantic JSON (see
// track_navigator_node.py and scripts/common/bag_io.py's decode_nav_debug).
// Published on the `vtitan.nav.v1.navigator_debug` NATS subject.
//
// Mirrors shared.domain.models.NavigatorDebugSnapshot, so a recorded bag and
// a live Go run describe the same thing and the migration's parity gate can
// diff them directly.
//
// The flat Python model is grouped here into sub-messages, which carries
// information the flat form only implied: a message field has explicit
// presence, so an ABSENT GROUP means that branch of step() did not run this
// tick. Fields inside a group stay `optional` on top of that, preserving the
// model's own per-field nulls -- that docstring is explicit that a null
// means "not computed on this tick's branch", not "unknown" and not zero.
// Both layers are needed to keep the mapping 1:1; collapsing either would
// make a deliberately-absent value arrive as a measured 0.0.
//
// Sized against a real 132.6 s run (run_20260829_140424): the JSON form
// averages 1527 B per message at 20 Hz, and /nav_debug alone accounted for
// 3978 kB of that bag. This encoding is several times smaller, and unlike
// the JSON it is schema-checked -- a renamed field fails `buf breaking`
// instead of silently vanishing from every consumer.
type NavigatorDebug struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replaces ROS2 Header: stamp + frame_id.
	Stamp         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FrameId       string                 `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Phase         Phase                  `protobuf:"varint,3,opt,name=phase,proto3,enum=vtitan.nav.v1.Phase" json:"phase,omitempty"`
	Pose          *NavigatorPose         `protobuf:"bytes,4,opt,name=pose,proto3" json:"pose,omitempty"`
	Race          *RaceState             `protobuf:"bytes,5,opt,name=race,proto3" json:"race,omitempty"`
	Stuck         *StuckDetection        `protobuf:"bytes,6,opt,name=stuck,proto3" json:"stuck,omitempty"`
	Perception    *Perception            `protobuf:"bytes,7,opt,name=perception,proto3" json:"perception,omitempty"`
	PathTracking  *PathTracking          `protobuf:"bytes,8,opt,name=path_tracking,json=pathTracking,proto3" json:"path_tracking,omitempty"`
	Speed         *SpeedSelection        `protobuf:"bytes,9,opt,name=speed,proto3" json:"speed,omitempty"`
	Command       *DriveCommand          `protobuf:"bytes,10,opt,name=command,proto3" json:"command,omitempty"`
	Maneuver      *Maneuver              `protobuf:"bytes,11,opt,name=maneuver,proto3" json:"maneuver,omitempty"`
	Parking       *Parking               `protobuf:"bytes,12,opt,name=parking,proto3" json:"parking,omitempty"`
	SignRouting   *SignRouting           `protobuf:"bytes,13,opt,name=sign_routing,json=signRouting,proto3" json:"sign_routing,omitempty"`
	BlindCreep    *BlindCreep            `protobuf:"bytes,14,opt,name=blind_creep,json=blindCreep,proto3" json:"blind_creep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigatorDebug) Reset() {
	*x = NavigatorDebug{}
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigatorDebug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigatorDebug) ProtoMessage() {}

func (x *NavigatorDebug) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_nav_v1_navigator_debug_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigatorDebug.ProtoReflect.Descriptor instead.
func (*NavigatorDebug) Descriptor() ([]byte, []int) {
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP(), []int{11}
}

func (x *NavigatorDebug) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *NavigatorDebug) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *NavigatorDebug) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *NavigatorDebug) GetPose() *NavigatorPose {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *NavigatorDebug) GetRace() *RaceState {
	if x != nil {
		return x.Race
	}
	return nil
}

func (x *NavigatorDebug) GetStuck() *StuckDetection {
	if x != nil {
		return x.Stuck
	}
	return nil
}

func (x *NavigatorDebug) GetPerception() *Perception {
	if x != nil {
		return x.Perception
	}
	return nil
}

func (x *NavigatorDebug) GetPathTracking() *PathTracking {
	if x != nil {
		return x.PathTracking
	}
	return nil
}

func (x *NavigatorDebug) GetSpeed() *SpeedSelection {
	if x != nil {
		return x.Speed
	}
	return nil
}

func (x *NavigatorDebug) GetCommand() *DriveCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *NavigatorDebug) GetManeuver() *Maneuver {
	if x != nil {
		return x.Maneuver
	}
	return nil
}

func (x *NavigatorDebug) GetParking() *Parking {
	if x != nil {
		return x.Parking
	}
	return nil
}

func (x *NavigatorDebug) GetSignRouting() *SignRouting {
	if x != nil {
		return x.SignRouting
	}
	return nil
}

func (x *NavigatorDebug) GetBlindCreep() *BlindCreep {
	if x != nil {
		return x.BlindCreep
	}
	return nil
}

var File_vtitan_nav_v1_navigator_debug_proto protoreflect.FileDescriptor

const file_vtitan_nav_v1_navigator_debug_proto_rawDesc = "" +
	"\n" +
	"#vtitan/nav/v1/navigator_debug.proto\x12\rvtitan.nav.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\rNavigatorPose\x12\x15\n" +
	"\x01x\x18\x01 \x01(\x01B\a\xbaH\x04\x12\x02@\x01R\x01x\x12\x15\n" +
	"\x01y\x18\x02 \x01(\x01B\a\xbaH\x04\x12\x02@\x01R\x01y\x12\x19\n" +
	"\x03yaw\x18\x03 \x01(\x01B\a\xbaH\x04\x12\x02@\x01R\x03yaw\"\xb6\x02\n" +
	"\tRaceState\x12@\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x18.vtitan.nav.v1.DirectionB\b\xbaH\x05\x82\x01\x02\x10\x01R\tdirection\x12K\n" +
	"\x10current_corridor\x18\x02 \x01(\x0e2\x16.vtitan.nav.v1.SectionB\b\xbaH\x05\x82\x01\x02\x10\x01R\x0fcurrentCorridor\x123\n" +
	"\x0ewaypoint_index\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x00R\rwaypointIndex\x88\x01\x01\x12.\n" +
	"\x0elaps_completed\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\rlapsCompleted\x12\"\n" +
	"\bnum_laps\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\anumLapsB\x11\n" +
	"\x0f_waypoint_index\"\xd5\x01\n" +
	"\x0eStuckDetection\x12\x1e\n" +
	"\bis_stuck\x18\x01 \x01(\bH\x00R\aisStuck\x88\x01\x01\x12-\n" +
	"\vstuck_count\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x01R\n" +
	"stuckCount\x88\x01\x01\x12A\n" +
	"\x11recent_movement_m\x18\x03 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x02R\x0frecentMovementM\x88\x01\x01B\v\n" +
	"\t_is_stuckB\x0e\n" +
	"\f_stuck_countB\x14\n" +
	"\x12_recent_movement_m\"\x96\x03\n" +
	"\n" +
	"Perception\x12E\n" +
	"\x13forward_clearance_m\x18\x01 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x00R\x11forwardClearanceM\x88\x01\x01\x12@\n" +
	"\x11min_lidar_range_m\x18\x02 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\x0eminLidarRangeM\x88\x01\x01\x126\n" +
	"\x04risk\x18\x03 \x01(\x0e2\x18.vtitan.nav.v1.RiskLevelB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04risk\x12C\n" +
	"\vescape_risk\x18\x04 \x01(\x0e2\x18.vtitan.nav.v1.RiskLevelB\b\xbaH\x05\x82\x01\x02\x10\x01R\n" +
	"escapeRisk\x12?\n" +
	"\x10rear_clearance_m\x18\x05 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x02R\x0erearClearanceM\x88\x01\x01B\x16\n" +
	"\x14_forward_clearance_mB\x14\n" +
	"\x12_min_lidar_range_mB\x13\n" +
	"\x11_rear_clearance_m\"\xf0\x03\n" +
	"\fPathTracking\x12:\n" +
	"\x12crosstrack_error_m\x18\x01 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x00R\x10crosstrackErrorM\x88\x01\x01\x12G\n" +
	"\x14lookahead_distance_m\x18\x02 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\x12lookaheadDistanceM\x88\x01\x01\x12;\n" +
	"\x13path_turn_ahead_rad\x18\x03 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x02R\x10pathTurnAheadRad\x88\x01\x01\x122\n" +
	"\x0esteer_target_x\x18\x04 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x03R\fsteerTargetX\x88\x01\x01\x122\n" +
	"\x0esteer_target_y\x18\x05 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x04R\fsteerTargetY\x88\x01\x01\x124\n" +
	"\x0fangle_error_rad\x18\x06 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x05R\rangleErrorRad\x88\x01\x01B\x15\n" +
	"\x13_crosstrack_error_mB\x17\n" +
	"\x15_lookahead_distance_mB\x16\n" +
	"\x14_path_turn_ahead_radB\x11\n" +
	"\x0f_steer_target_xB\x11\n" +
	"\x0f_steer_target_yB\x12\n" +
	"\x10_angle_error_rad\"\xc8\x01\n" +
	"\x0eSpeedSelection\x12E\n" +
	"\x13clearance_speed_mps\x18\x01 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x00R\x11clearanceSpeedMps\x88\x01\x01\x12A\n" +
	"\x11heading_speed_mps\x18\x02 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\x0fheadingSpeedMps\x88\x01\x01B\x16\n" +
	"\x14_clearance_speed_mpsB\x14\n" +
	"\x12_heading_speed_mps\"\x9c\x01\n" +
	"\fDriveCommand\x12)\n" +
	"\tspeed_mps\x18\x01 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x00R\bspeedMps\x88\x01\x01\x12A\n" +
	"\rsteering_norm\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\xf0\xbfH\x01R\fsteeringNorm\x88\x01\x01B\f\n" +
	"\n" +
	"_speed_mpsB\x10\n" +
	"\x0e_steering_norm\"\xd3\x02\n" +
	"\bManeuver\x12F\n" +
	"\vactive_type\x18\x01 \x01(\x0e2\x1b.vtitan.nav.v1.ManeuverTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\n" +
	"activeType\x128\n" +
	"\bsteering\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\xf0\xbfH\x00R\bsteering\x88\x01\x01\x12)\n" +
	"\tspeed_mps\x18\x03 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x01R\bspeedMps\x88\x01\x01\x12-\n" +
	"\vframes_left\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x02R\n" +
	"framesLeft\x88\x01\x01\x12/\n" +
	"\fescape_count\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x03R\vescapeCount\x88\x01\x01B\v\n" +
	"\t_steeringB\f\n" +
	"\n" +
	"_speed_mpsB\x0e\n" +
	"\f_frames_leftB\x0f\n" +
	"\r_escape_count\"n\n" +
	"\aParking\x12\x1d\n" +
	"\aengaged\x18\x01 \x01(\bH\x00R\aengaged\x88\x01\x01\x128\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x18.vtitan.nav.v1.ParkPhaseB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05phaseB\n" +
	"\n" +
	"\b_engaged\"\xb9\x01\n" +
	"\vSignRouting\x128\n" +
	"\x11active_sign_count\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x00R\x0factiveSignCount\x88\x01\x01\x12C\n" +
	"\x12deform_magnitude_m\x18\x02 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\x10deformMagnitudeM\x88\x01\x01B\x14\n" +
	"\x12_active_sign_countB\x15\n" +
	"\x13_deform_magnitude_m\"\xf1\x03\n" +
	"\n" +
	"BlindCreep\x12&\n" +
	"\fgate_verdict\x18\x01 \x01(\tH\x00R\vgateVerdict\x88\x01\x01\x127\n" +
	"\fleft_range_m\x18\x02 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\n" +
	"leftRangeM\x88\x01\x01\x129\n" +
	"\rright_range_m\x18\x03 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x02R\vrightRangeM\x88\x01\x01\x125\n" +
	"\x0fvotes_clockwise\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x03R\x0evotesClockwise\x88\x01\x01\x12C\n" +
	"\x16votes_counterclockwise\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x04R\x15votesCounterclockwise\x88\x01\x01\x12L\n" +
	"\x17corridor_width_belief_m\x18\x06 \x01(\x01B\x10\xbaH\r\x12\v@\x01)\x00\x00\x00\x00\x00\x00\x00\x00H\x05R\x14corridorWidthBeliefM\x88\x01\x01B\x0f\n" +
	"\r_gate_verdictB\x0f\n" +
	"\r_left_range_mB\x10\n" +
	"\x0e_right_range_mB\x12\n" +
	"\x10_votes_clockwiseB\x19\n" +
	"\x17_votes_counterclockwiseB\x1a\n" +
	"\x18_corridor_width_belief_m\"\xfb\x05\n" +
	"\x0eNavigatorDebug\x128\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x05stamp\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\tR\aframeId\x124\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x14.vtitan.nav.v1.PhaseB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05phase\x120\n" +
	"\x04pose\x18\x04 \x01(\v2\x1c.vtitan.nav.v1.NavigatorPoseR\x04pose\x12,\n" +
	"\x04race\x18\x05 \x01(\v2\x18.vtitan.nav.v1.RaceStateR\x04race\x123\n" +
	"\x05stuck\x18\x06 \x01(\v2\x1d.vtitan.nav.v1.StuckDetectionR\x05stuck\x129\n" +
	"\n" +
	"perception\x18\a \x01(\v2\x19.vtitan.nav.v1.PerceptionR\n" +
	"perception\x12@\n" +
	"\rpath_tracking\x18\b \x01(\v2\x1b.vtitan.nav.v1.PathTrackingR\fpathTracking\x123\n" +
	"\x05speed\x18\t \x01(\v2\x1d.vtitan.nav.v1.SpeedSelectionR\x05speed\x125\n" +
	"\acommand\x18\n" +
	" \x01(\v2\x1b.vtitan.nav.v1.DriveCommandR\acommand\x123\n" +
	"\bmaneuver\x18\v \x01(\v2\x17.vtitan.nav.v1.ManeuverR\bmaneuver\x120\n" +
	"\aparking\x18\f \x01(\v2\x16.vtitan.nav.v1.ParkingR\aparking\x12=\n" +
	"\fsign_routing\x18\r \x01(\v2\x1a.vtitan.nav.v1.SignRoutingR\vsignRouting\x12:\n" +
	"\vblind_creep\x18\x0e \x01(\v2\x19.vtitan.nav.v1.BlindCreepR\n" +
	"blindCreep*\xdd\x02\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PHASE_NOT_YET_STEPPED\x10\x01\x12\x11\n" +
	"\rPHASE_NO_POSE\x10\x02\x12\x15\n" +
	"\x11PHASE_BLIND_CREEP\x10\x03\x12\x19\n" +
	"\x15PHASE_ACTIVE_MANEUVER\x10\x04\x12\x1e\n" +
	"\x1aPHASE_STUCK_ESCAPE_HOLDING\x10\x05\x12\x1f\n" +
	"\x1bPHASE_STUCK_ESCAPE_MANEUVER\x10\x06\x12\x17\n" +
	"\x13PHASE_FINISHED_HOLD\x10\a\x12\x11\n" +
	"\rPHASE_PARKING\x10\b\x12 \n" +
	"\x1cPHASE_WAYPOINT_WRAP_FALLBACK\x10\t\x12\x1a\n" +
	"\x16PHASE_WAYPOINT_REACHED\x10\n" +
	"\x12\x16\n" +
	"\x12PHASE_NORMAL_DRIVE\x10\v\x12\x1a\n" +
	"\x16PHASE_ESCAPE_TRIGGERED\x10\f*_\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DIRECTION_CLOCKWISE\x10\x01\x12\x1e\n" +
	"\x1aDIRECTION_COUNTERCLOCKWISE\x10\x02*l\n" +
	"\aSection\x12\x17\n" +
	"\x13SECTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSECTION_NORTH\x10\x01\x12\x11\n" +
	"\rSECTION_SOUTH\x10\x02\x12\x10\n" +
	"\fSECTION_EAST\x10\x03\x12\x10\n" +
	"\fSECTION_WEST\x10\x04*n\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fRISK_LEVEL_SAFE\x10\x01\x12\x17\n" +
	"\x13RISK_LEVEL_OBSTACLE\x10\x02\x12\x17\n" +
	"\x13RISK_LEVEL_CRITICAL\x10\x03*\xac\x01\n" +
	"\fManeuverType\x12\x1d\n" +
	"\x19MANEUVER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MANEUVER_TYPE_K_TURN\x10\x01\x12!\n" +
	"\x1dMANEUVER_TYPE_SIDE_CORRECTION\x10\x02\x12\x1f\n" +
	"\x1bMANEUVER_TYPE_STUCK_REVERSE\x10\x03\x12\x1f\n" +
	"\x1bMANEUVER_TYPE_STUCK_FORWARD\x10\x04*h\n" +
	"\tParkPhase\x12\x1a\n" +
	"\x16PARK_PHASE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PARK_PHASE_STAGE\x10\x01\x12\x14\n" +
	"\x10PARK_PHASE_ENTER\x10\x02\x12\x13\n" +
	"\x0fPARK_PHASE_DONE\x10\x03B@Z>github.com/teamvoltimor/vtitan/src/go/internal/schema/pb/navv1b\x06proto3"

var (
	file_vtitan_nav_v1_navigator_debug_proto_rawDescOnce sync.Once
	file_vtitan_nav_v1_navigator_debug_proto_rawDescData []byte
)

func file_vtitan_nav_v1_navigator_debug_proto_rawDescGZIP() []byte {
	file_vtitan_nav_v1_navigator_debug_proto_rawDescOnce.Do(func() {
		file_vtitan_nav_v1_navigator_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_nav_v1_navigator_debug_proto_rawDesc), len(file_vtitan_nav_v1_navigator_debug_proto_rawDesc)))
	})
	return file_vtitan_nav_v1_navigator_debug_proto_rawDescData
}

var file_vtitan_nav_v1_navigator_debug_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_vtitan_nav_v1_navigator_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vtitan_nav_v1_navigator_debug_proto_goTypes = []any{
	(Phase)(0),                    // 0: vtitan.nav.v1.Phase
	(Direction)(0),                // 1: vtitan.nav.v1.Direction
	(Section)(0),                  // 2: vtitan.nav.v1.Section
	(RiskLevel)(0),                // 3: vtitan.nav.v1.RiskLevel
	(ManeuverType)(0),             // 4: vtitan.nav.v1.ManeuverType
	(ParkPhase)(0),                // 5: vtitan.nav.v1.ParkPhase
	(*NavigatorPose)(nil),         // 6: vtitan.nav.v1.NavigatorPose
	(*RaceState)(nil),             // 7: vtitan.nav.v1.RaceState
	(*StuckDetection)(nil),        // 8: vtitan.nav.v1.StuckDetection
	(*Perception)(nil),            // 9: vtitan.nav.v1.Perception
	(*PathTracking)(nil),          // 10: vtitan.nav.v1.PathTracking
	(*SpeedSelection)(nil),        // 11: vtitan.nav.v1.SpeedSelection
	(*DriveCommand)(nil),          // 12: vtitan.nav.v1.DriveCommand
	(*Maneuver)(nil),              // 13: vtitan.nav.v1.Maneuver
	(*Parking)(nil),               // 14: vtitan.nav.v1.Parking
	(*SignRouting)(nil),           // 15: vtitan.nav.v1.SignRouting
	(*BlindCreep)(nil),            // 16: vtitan.nav.v1.BlindCreep
	(*NavigatorDebug)(nil),        // 17: vtitan.nav.v1.NavigatorDebug
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_vtitan_nav_v1_navigator_debug_proto_depIdxs = []int32{
	1,  // 0: vtitan.nav.v1.RaceState.direction:type_name -> vtitan.nav.v1.Direction
	2,  // 1: vtitan.nav.v1.RaceState.current_corridor:type_name -> vtitan.nav.v1.Section
	3,  // 2: vtitan.nav.v1.Perception.risk:type_name -> vtitan.nav.v1.RiskLevel
	3,  // 3: vtitan.nav.v1.Perception.escape_risk:type_name -> vtitan.nav.v1.RiskLevel
	4,  // 4: vtitan.nav.v1.Maneuver.active_type:type_name -> vtitan.nav.v1.ManeuverType
	5,  // 5: vtitan.nav.v1.Parking.phase:type_name -> vtitan.nav.v1.ParkPhase
	18, // 6: vtitan.nav.v1.NavigatorDebug.stamp:type_name -> google.protobuf.Timestamp
	0,  // 7: vtitan.nav.v1.NavigatorDebug.phase:type_name -> vtitan.nav.v1.Phase
	6,  // 8: vtitan.nav.v1.NavigatorDebug.pose:type_name -> vtitan.nav.v1.NavigatorPose
	7,  // 9: vtitan.nav.v1.NavigatorDebug.race:type_name -> vtitan.nav.v1.RaceState
	8,  // 10: vtitan.nav.v1.NavigatorDebug.stuck:type_name -> vtitan.nav.v1.StuckDetection
	9,  // 11: vtitan.nav.v1.NavigatorDebug.perception:type_name -> vtitan.nav.v1.Perception
	10, // 12: vtitan.nav.v1.NavigatorDebug.path_tracking:type_name -> vtitan.nav.v1.PathTracking
	11, // 13: vtitan.nav.v1.NavigatorDebug.speed:type_name -> vtitan.nav.v1.SpeedSelection
	12, // 14: vtitan.nav.v1.NavigatorDebug.command:type_name -> vtitan.nav.v1.DriveCommand
	13, // 15: vtitan.nav.v1.NavigatorDebug.maneuver:type_name -> vtitan.nav.v1.Maneuver
	14, // 16: vtitan.nav.v1.NavigatorDebug.parking:type_name -> vtitan.nav.v1.Parking
	15, // 17: vtitan.nav.v1.NavigatorDebug.sign_routing:type_name -> vtitan.nav.v1.SignRouting
	16, // 18: vtitan.nav.v1.NavigatorDebug.blind_creep:type_name -> vtitan.nav.v1.BlindCreep
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_vtitan_nav_v1_navigator_debug_proto_init() }
func file_vtitan_nav_v1_navigator_debug_proto_init() {
	if File_vtitan_nav_v1_navigator_debug_proto != nil {
		return
	}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[1].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[2].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[3].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[4].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[5].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[6].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[7].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[8].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[9].OneofWrappers = []any{}
	file_vtitan_nav_v1_navigator_debug_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_nav_v1_navigator_debug_proto_rawDesc), len(file_vtitan_nav_v1_navigator_debug_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_nav_v1_navigator_debug_proto_goTypes,
		DependencyIndexes: file_vtitan_nav_v1_navigator_debug_proto_depIdxs,
		EnumInfos:         file_vtitan_nav_v1_navigator_debug_proto_enumTypes,
		MessageInfos:      file_vtitan_nav_v1_navigator_debug_proto_msgTypes,
	}.Build()
	File_vtitan_nav_v1_navigator_debug_proto = out.File
	file_vtitan_nav_v1_navigator_debug_proto_goTypes = nil
	file_vtitan_nav_v1_navigator_debug_proto_depIdxs = nil
}
