"""Closed-loop Obstacles Challenge smoke tests.

``scenario_catalog.all_obstacles_demo_scenarios()`` loads real official-layout
fixtures generated by the Go generator (``simgen``, the real 36-scenario sign
table) rather than an ad-hoc Python-built demo layout. These tests confirm
``ScenarioSimulator`` actually drives them end-to-end: ``SignRouter`` and
``ParkController`` wire in without crashing and the car doesn't wall-collide
just from a sign nudging its waypoints.

Every Go-generated Obstacles Challenge scenario has *both* a sign layout and
a parking lot — the generator builds them together unconditionally
(``ScenarioGenerator.resolveObstacles`` in ``generator.go``), matching the
real competition (Obstacles Challenge is always sign avoidance + parking).
That's a behavior change from the previous ad-hoc Python catalog, which had
separate "sign-only" and "sign+parking" demo scenarios specifically so a
``SignRouter`` bug could never be masked by a ``ParkController`` bug or vice
versa — every scenario below now exercises both systems together, so a
regression report has to look at *which* assertion failed (collision vs.
under-engaged sign vs. never-parked) rather than "which scenario subset"
failed to keep that isolation.

Multiple real bugs, found via this closed-loop wiring (never exercised by
``test_sign_router.py``, which only unit-tests ``apply_deformation`` math in
isolation) plus direct user feedback watching it live in RViz, were fixed in
``sign_router.py``/``core_navigator.py``/``scenario_catalog.py`` — see
``memory/obstacles_closed_loop_sign_router_bug.md`` for the full history.
Most recently: ``SignRouter._passed`` was never cleared between laps, so a
sign avoided once (lap 1) was silently ignored on laps 2-3 of every 3-lap
scenario — fixed with ``SignRouter.reset_for_new_lap()``, called from
``core_navigator.py`` at both lap-completion sites. ``core_navigator.py``
applies sign deformation to whichever waypoint the pure-pursuit lookahead
search actually returns (after the search, not before) — deforming a raw-path
candidate before the search picked from it let the search itself decide
whether the nudge ever reached steering.

Also fixed: ``ROUTING_TABLE`` pinned red/green to the robot's OWN left/right
(travel-relative), which flips outward vs inward between CW and CCW. The
actual WRO rule is absolute: red is always avoided OUTWARD, green always
INWARD, regardless of which direction the round is driven. The COUNTERCLOCKWISE
rows were wrong under the correct interpretation; ``TestPassSideRule`` and
``TestDeformationDirections`` in ``test_sign_router.py`` were rewritten to pin
the absolute rule instead of the travel-relative one.
"""

from __future__ import annotations

import logging
import math
from dataclasses import replace
from typing import Any

import pytest
from shared.domain.models import SignColor, Waypoint

import src.navigation.planning.sign_router as sign_router_module
import src.simulation.simulated_hardware_gateway as gateway_module
from src.navigation.planning.sign_router import signs_from_metadata
from src.simulation.scenario_catalog import all_obstacles_demo_scenarios
from src.simulation.scenario_simulator import ScenarioSimulator

logger = logging.getLogger(__name__)

# Full closed-loop sim (3 laps + parking) per scenario -- slow enough to skip
# from the default fast test loop (see task robot:test SCOPE=fast).
pytestmark = pytest.mark.slow

_MAX_STEPS = 6000
"""Every scenario now includes a parking maneuver, which needs more budget than a bare lap."""

# Loaded once at collection time (deterministic, file-backed fixtures) so each
# scenario can be its own @pytest.mark.parametrize case -- that lets xdist's
# worksteal scheduler spread the closed-loop runs across every core instead of
# one core working through a loop of ~16 scenarios serially.
_ALL_OBSTACLES_SCENARIOS = all_obstacles_demo_scenarios()
_SCENARIO_IDS = [s.label for s in _ALL_OBSTACLES_SCENARIOS]


class TestObstaclesDemoScenariosRun:
    """Every demo scenario must complete 3 laps, not collide, and park cleanly."""

    @pytest.mark.parametrize("scenario", _ALL_OBSTACLES_SCENARIOS, ids=_SCENARIO_IDS)
    def test_scenarios_complete_and_park(self, scenario: Any) -> None:
        result = ScenarioSimulator(
            scenario.metadata,
            num_laps=scenario.laps,
            seed=scenario.seed,
        ).run(max_steps=_MAX_STEPS)
        logger.info(
            "%s | laps=%d/%d collided=%s timeout=%s stuck=%s parked=%s",
            scenario.label,
            result.laps_completed,
            result.target_laps,
            result.collided,
            result.timed_out,
            result.stuck,
            result.parked,
        )
        failed = result.collided or result.laps_completed < scenario.laps or result.parked is None
        assert not failed, (scenario.label, result.collision_xy or result.final_pose)

    @pytest.mark.parametrize("scenario", _ALL_OBSTACLES_SCENARIOS, ids=_SCENARIO_IDS)
    def test_signs_actually_deform_the_path(self, scenario: Any, monkeypatch: pytest.MonkeyPatch) -> None:
        """Every scenario must trigger at least one real deformation.

        A scenario that "runs clean" only because its signs never actually
        engage (e.g. misplaced into a corridor the robot doesn't drive near)
        would pass ``test_scenarios_complete_and_park`` for the wrong reason —
        this catches that silently-disabled-routing failure mode directly.
        """
        orig = sign_router_module.SignRouter.deform_waypoint
        deform_count = 0

        def counting_deform_waypoint(self, waypoint, robot_pos, robot_yaw, corridor, observations=None):
            nonlocal deform_count
            result = orig(self, waypoint, robot_pos, robot_yaw, corridor, observations)
            if result != waypoint:
                deform_count += 1
            return result

        monkeypatch.setattr(
            sign_router_module.SignRouter,
            "deform_waypoint",
            counting_deform_waypoint,
        )

        ScenarioSimulator(
            scenario.metadata,
            num_laps=scenario.laps,
            seed=scenario.seed,
        ).run(max_steps=_MAX_STEPS)
        logger.info("%s | deformations=%d", scenario.label, deform_count)
        assert deform_count > 0, f"signs never engaged in {scenario.label}"

    @pytest.mark.parametrize("scenario", _ALL_OBSTACLES_SCENARIOS, ids=_SCENARIO_IDS)
    def test_signs_engage_on_every_lap(self, scenario: Any, monkeypatch: pytest.MonkeyPatch) -> None:
        """A sign avoided on lap 1 must be avoided again on laps 2 and 3.

        Regression guard for a real bug: ``SignRouter._passed`` never cleared
        between laps, so once a sign was marked passed on lap 1 it was
        silently skipped for the rest of a 3-lap scenario.
        """
        orig = sign_router_module.SignRouter.deform_waypoint
        laps_seen_per_sign: dict[int, set[int]] = {}
        navigator_ref: list = [None]

        def recording_deform_waypoint(self, waypoint, robot_pos, robot_yaw, corridor, observations=None):
            # deform_waypoint takes robot_pos as a plain (x, y) tuple and
            # converts it before reaching the private helper, which requires a
            # Waypoint. A wrapper calling that helper directly has to do the
            # same conversion or it raises AttributeError on .distance_to.
            candidates = self._active_sign_candidates(Waypoint(*robot_pos), robot_yaw, corridor)
            nearest_idx = candidates[0][0] if candidates else -1
            result = orig(self, waypoint, robot_pos, robot_yaw, corridor, observations)
            if result != waypoint and nearest_idx >= 0:
                laps_seen_per_sign.setdefault(nearest_idx, set()).add(
                    navigator_ref[0].laps_completed,
                )
            return result

        monkeypatch.setattr(
            sign_router_module.SignRouter,
            "deform_waypoint",
            recording_deform_waypoint,
        )

        sim = ScenarioSimulator(scenario.metadata, num_laps=scenario.laps, seed=scenario.seed)
        navigator_ref[0] = sim._navigator
        sim.run(max_steps=_MAX_STEPS)
        under_engaged = [
            (i, sorted(laps_seen_per_sign.get(i, set())))
            for i in range(len(scenario.metadata["sign_positions"]))
            if len(laps_seen_per_sign.get(i, set())) < scenario.laps
        ]
        assert not under_engaged, f"{scenario.label}: sign engaged on fewer than {scenario.laps} laps: {under_engaged}"


class TestVisionConfirmedSignRouting:
    """Closed-loop coverage for the camera-detection confirmation path.

    Every test above drives ``SignRouter`` with ``detections=None`` (ground
    truth only) — ``match_detection_to_sign`` / ``_detection_to_world``, the
    one part of the stack where a live sensor reading can override
    known-good scenario metadata, was previously never exercised end-to-end
    (review 2026-07-11 §2.2 / recommendation #1). These tests drive the same
    demo scenarios through a synthetic camera (``src/simulation/vision_emulator.py``)
    instead of bypassing vision entirely.
    """

    @pytest.mark.parametrize("scenario", _ALL_OBSTACLES_SCENARIOS, ids=_SCENARIO_IDS)
    def test_vision_confirmed_sign_scenarios_complete_without_collision(self, scenario: Any) -> None:
        result = ScenarioSimulator(
            scenario.metadata,
            num_laps=scenario.laps,
            seed=scenario.seed,
            emit_vision_detections=True,
        ).run(max_steps=_MAX_STEPS)
        logger.info(
            "%s | laps=%d/%d collided=%s timeout=%s stuck=%s",
            scenario.label,
            result.laps_completed,
            result.target_laps,
            result.collided,
            result.timed_out,
            result.stuck,
        )
        failed = result.collided or result.laps_completed < scenario.laps
        assert not failed, (scenario.label, result.collision_xy or result.final_pose)

    def test_wrong_camera_color_overrides_ground_truth_mid_run(
        self,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """A camera detection that disagrees with scenario metadata actually wins.

        Monkeypatches the vision emulator to report every sign's color
        flipped from its ground-truth metadata color, then spies on
        ``apply_deformation`` (the function ``SignRouter.deform_waypoint``
        calls with whichever color it decided to use) to prove the flipped
        camera color — not the ground-truth metadata color — is what actually
        drove steering. Closes the review's "no scenario where a wrong/late
        camera confirmation changes sign-avoidance direction" gap.
        """
        scenario = _ALL_OBSTACLES_SCENARIOS[0]

        original_emulate = gateway_module.emulate_sign_observations

        def flipped_color_emulate(signs, robot_pos, robot_yaw):
            detections = original_emulate(signs, Waypoint(*robot_pos), robot_yaw)
            return [replace(d, color=SignColor.GREEN if d.color == SignColor.RED else SignColor.RED) for d in detections]

        monkeypatch.setattr(gateway_module, "emulate_sign_observations", flipped_color_emulate)

        # ``sign.color`` is always the untouched ground-truth metadata color
        # (SignRouter._signs is never mutated); ``color`` is whatever
        # deform_waypoint() actually decided to use. Comparing the two per
        # call — rather than comparing global color sets — stays correct even
        # when a scenario's two signs have different ground-truth colors.
        used_pairs: list[tuple[str, str]] = []
        original_apply = sign_router_module.apply_deformation

        def spying_apply_deformation(*args, **kwargs):
            # Trailing arguments pass straight through rather than being named:
            # pinning them here is how this spy would go stale the next time
            # ``apply_deformation`` grows one (it grew ``robot_pos``), with
            # nothing failing until the spy is needed.
            sign, color = args[1], args[2]
            used_pairs.append((sign.color, color))
            return original_apply(*args, **kwargs)

        monkeypatch.setattr(sign_router_module, "apply_deformation", spying_apply_deformation)

        result = ScenarioSimulator(
            scenario.metadata,
            num_laps=scenario.laps,
            seed=scenario.seed,
            emit_vision_detections=True,
        ).run(max_steps=_MAX_STEPS)

        assert not result.collided, scenario.label
        assert used_pairs, "sign never engaged — nothing to prove the override with"
        # Activation is distance-only (not FOV-gated), so a sign can be
        # "engaged" while briefly outside the camera's cone — deform_waypoint()
        # correctly falls back to ground truth on those ticks. What matters is
        # that the override actually won at least once during the run.
        overridden = [(gt, eff) for gt, eff in used_pairs if eff != gt]
        assert overridden, f"camera detection never overrode ground-truth color in this run: {used_pairs[:10]}"


class TestBlindSignDiscovery:
    """A blind run has to find the signs with its camera, not be handed them.

    WRO randomises the sign layout every round and no scenario file exists on
    the mat, so ``blind=True`` withholds the sign positions exactly as it
    already withholds the corridor widths and the travel direction. These pin
    that the withholding is real and that what replaces it is accurate enough
    to route on — the driving outcome is a separate question, currently blocked
    upstream (see ``docs/sign-avoidance-investigation.md``).
    """

    def test_blind_router_starts_with_no_signs(self) -> None:
        """Nothing is handed over: the router is empty before the robot moves."""
        scenario = _ALL_OBSTACLES_SCENARIOS[0]
        sim = ScenarioSimulator(scenario.metadata, num_laps=scenario.laps, seed=scenario.seed, blind=True)

        assert sim.routed_signs == []

    @pytest.mark.parametrize("scenario", _ALL_OBSTACLES_SCENARIOS, ids=_SCENARIO_IDS)
    def test_blind_run_discovers_signs_the_robot_drives_past(self, scenario: Any) -> None:
        """Discovery finds real signs, in the right place and the right colour.

        Only signs the robot actually reaches can be discovered, so this
        asserts on the quality of what was found rather than on finding all of
        them — the runs still end early on a sign collision, which caps how
        much of the layout is ever seen.
        """
        metadata = scenario.metadata
        truth = signs_from_metadata(metadata if isinstance(metadata, dict) else metadata.model_dump())

        sim = ScenarioSimulator(metadata, num_laps=scenario.laps, seed=scenario.seed, blind=True)
        sim.run(max_steps=_MAX_STEPS)
        discovered = sim.routed_signs

        assert discovered, f"{scenario.label}: discovered nothing"

        failures = []
        for spec in discovered:
            nearest = min(truth, key=lambda t: math.dist((t.x, t.y), (spec.x, spec.y)))
            error = math.dist((nearest.x, nearest.y), (spec.x, spec.y))
            # A sign sits on a grid whose lanes are ~0.20 m apart, so an
            # error near that would put it in the wrong lane and route the
            # robot to the wrong side of it. 10 cm keeps a clear margin.
            if error > 0.10:
                failures.append(f"{spec} is {error * 100:.0f} cm from any real sign")
            elif nearest.color != spec.color:
                failures.append(f"{spec} mis-coloured (truth {nearest.color})")

        assert not failures, f"{scenario.label}: {failures}"
