"""Closed-loop Obstacles Challenge smoke tests.

``scenario_catalog.all_obstacles_demo_scenarios()`` loads real official-layout
fixtures generated by the Go generator (``simgen``, the real 36-scenario sign
table) rather than an ad-hoc Python-built demo layout. These tests confirm
``ScenarioSimulator`` actually drives them end-to-end: ``SignRouter`` and
``ParkController`` wire in without crashing and the car doesn't wall-collide
just from a sign nudging its waypoints.

Every Go-generated Obstacles Challenge scenario has *both* a sign layout and
a parking lot — the generator builds them together unconditionally
(``ScenarioGenerator.resolveObstacles`` in ``generator.go``), matching the
real competition (Obstacles Challenge is always sign avoidance + parking).
That's a behavior change from the previous ad-hoc Python catalog, which had
separate "sign-only" and "sign+parking" demo scenarios specifically so a
``SignRouter`` bug could never be masked by a ``ParkController`` bug or vice
versa — every scenario below now exercises both systems together, so a
regression report has to look at *which* assertion failed (collision vs.
under-engaged sign vs. never-parked) rather than "which scenario subset"
failed to keep that isolation.

Multiple real bugs, found via this closed-loop wiring (never exercised by
``test_sign_router.py``, which only unit-tests ``_apply_deformation`` math in
isolation) plus direct user feedback watching it live in RViz, were fixed in
``sign_router.py``/``core_navigator.py``/``scenario_catalog.py`` — see
``memory/obstacles_closed_loop_sign_router_bug.md`` for the full history.
Most recently: ``SignRouter._passed`` was never cleared between laps, so a
sign avoided once (lap 1) was silently ignored on laps 2-3 of every 3-lap
scenario — fixed with ``SignRouter.reset_for_new_lap()``, called from
``core_navigator.py`` at both lap-completion sites. ``core_navigator.py``
applies sign deformation to whichever waypoint the pure-pursuit lookahead
search actually returns (after the search, not before) — deforming a raw-path
candidate before the search picked from it let the search itself decide
whether the nudge ever reached steering.

Also fixed: ``_ROUTING_TABLE`` pinned red/green to the robot's OWN left/right
(travel-relative), which flips outward vs inward between CW and CCW. The
actual WRO rule is absolute: red is always avoided OUTWARD, green always
INWARD, regardless of which direction the round is driven. The COUNTERCLOCKWISE
rows were wrong under the correct interpretation; ``TestPassSideRule`` and
``TestDeformationDirections`` in ``test_sign_router.py`` were rewritten to pin
the absolute rule instead of the travel-relative one.
"""

from __future__ import annotations

import logging
from dataclasses import replace
from typing import TYPE_CHECKING

import src.navigation.planning.sign_router as sign_router_module
import src.simulation.gateway as gateway_module
from src.simulation.gateway import ScenarioSimulator
from src.simulation.scenario_catalog import all_obstacles_demo_scenarios

if TYPE_CHECKING:
    import pytest

logger = logging.getLogger(__name__)

_MAX_STEPS = 6000
"""Every scenario now includes a parking maneuver, which needs more budget than a bare lap."""


class TestObstaclesDemoScenariosRun:
    """Every demo scenario must complete 3 laps, not collide, and park cleanly."""

    def test_scenarios_complete_and_park(self) -> None:
        failures = []
        for scenario in all_obstacles_demo_scenarios():
            result = ScenarioSimulator(
                scenario.metadata, num_laps=scenario.laps, seed=scenario.seed,
            ).run(max_steps=_MAX_STEPS)
            logger.info(
                "%s | laps=%d/%d collided=%s timeout=%s parked=%s",
                scenario.label, result.laps_completed, result.target_laps,
                result.collided, result.timed_out, result.parked,
            )
            if result.collided or result.laps_completed < scenario.laps or result.parked is None:
                failures.append((scenario.label, result))
        assert not failures, [(label, r.collision_xy or r.final_pose) for label, r in failures]

    def test_signs_actually_deform_the_path(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Every scenario must trigger at least one real deformation.

        A scenario that "runs clean" only because its signs never actually
        engage (e.g. misplaced into a corridor the robot doesn't drive near)
        would pass ``test_scenarios_complete_and_park`` for the wrong reason —
        this catches that silently-disabled-routing failure mode directly.
        """
        deform_counts: dict[str, int] = {}
        current_label = [""]
        orig = sign_router_module.SignRouter.deform_waypoint

        def counting_deform_waypoint(self, waypoint, robot_pos, robot_yaw, corridor, detections=None):
            result = orig(self, waypoint, robot_pos, robot_yaw, corridor, detections)
            if result != waypoint:
                deform_counts[current_label[0]] = deform_counts.get(current_label[0], 0) + 1
            return result

        monkeypatch.setattr(
            sign_router_module.SignRouter, "deform_waypoint", counting_deform_waypoint,
        )

        never_engaged = []
        for scenario in all_obstacles_demo_scenarios():
            current_label[0] = scenario.label
            ScenarioSimulator(
                scenario.metadata, num_laps=scenario.laps, seed=scenario.seed,
            ).run(max_steps=_MAX_STEPS)
            count = deform_counts.get(scenario.label, 0)
            logger.info("%s | deformations=%d", scenario.label, count)
            if count == 0:
                never_engaged.append(scenario.label)

        assert not never_engaged, f"signs never engaged in: {never_engaged}"

    def test_signs_engage_on_every_lap(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """A sign avoided on lap 1 must be avoided again on laps 2 and 3.

        Regression guard for a real bug: ``SignRouter._passed`` never cleared
        between laps, so once a sign was marked passed on lap 1 it was
        silently skipped for the rest of a 3-lap scenario.
        """
        orig = sign_router_module.SignRouter.deform_waypoint
        laps_seen_per_sign: dict[int, set[int]] = {}
        navigator_ref: list = [None]

        def recording_deform_waypoint(self, waypoint, robot_pos, robot_yaw, corridor, detections=None):
            nearest_idx, _ = self._nearest_active_sign(robot_pos, corridor)
            result = orig(self, waypoint, robot_pos, robot_yaw, corridor, detections)
            if result != waypoint and nearest_idx >= 0:
                laps_seen_per_sign.setdefault(nearest_idx, set()).add(
                    navigator_ref[0].laps_completed,
                )
            return result

        monkeypatch.setattr(
            sign_router_module.SignRouter, "deform_waypoint", recording_deform_waypoint,
        )

        under_engaged = []
        for scenario in all_obstacles_demo_scenarios():
            laps_seen_per_sign.clear()
            sim = ScenarioSimulator(scenario.metadata, num_laps=scenario.laps, seed=scenario.seed)
            navigator_ref[0] = sim._navigator
            sim.run(max_steps=_MAX_STEPS)
            for i in range(len(scenario.metadata["sign_positions"])):
                laps = laps_seen_per_sign.get(i, set())
                if len(laps) < scenario.laps:
                    under_engaged.append((scenario.label, i, sorted(laps)))

        assert not under_engaged, f"sign engaged on fewer than {scenario.laps} laps: {under_engaged}"


class TestVisionConfirmedSignRouting:
    """Closed-loop coverage for the camera-detection confirmation path.

    Every test above drives ``SignRouter`` with ``detections=None`` (ground
    truth only) — ``_match_detection_to_sign`` / ``_detection_to_world``, the
    one part of the stack where a live sensor reading can override
    known-good scenario metadata, was previously never exercised end-to-end
    (review 2026-07-11 §2.2 / recommendation #1). These tests drive the same
    demo scenarios through a synthetic camera (``src/simulation/vision_emulator.py``)
    instead of bypassing vision entirely.
    """

    def test_vision_confirmed_sign_scenarios_complete_without_collision(self) -> None:
        failures = []
        for scenario in all_obstacles_demo_scenarios():
            result = ScenarioSimulator(
                scenario.metadata, num_laps=scenario.laps, seed=scenario.seed,
                emit_vision_detections=True,
            ).run(max_steps=_MAX_STEPS)
            logger.info(
                "%s | laps=%d/%d collided=%s timeout=%s",
                scenario.label, result.laps_completed, result.target_laps,
                result.collided, result.timed_out,
            )
            if result.collided or result.laps_completed < scenario.laps:
                failures.append((scenario.label, result))
        assert not failures, [(label, r.collision_xy or r.final_pose) for label, r in failures]

    def test_wrong_camera_color_overrides_ground_truth_mid_run(
        self, monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """A camera detection that disagrees with scenario metadata actually wins.

        Monkeypatches the vision emulator to report every sign's color
        flipped from its ground-truth metadata color, then spies on
        ``_apply_deformation`` (the function ``SignRouter.deform_waypoint``
        calls with whichever color it decided to use) to prove the flipped
        camera color — not the ground-truth metadata color — is what actually
        drove steering. Closes the review's "no scenario where a wrong/late
        camera confirmation changes sign-avoidance direction" gap.
        """
        scenario = all_obstacles_demo_scenarios()[0]

        original_emulate = gateway_module.emulate_sign_detections

        def flipped_color_emulate(signs, robot_pos, robot_yaw):
            detections = original_emulate(signs, robot_pos, robot_yaw)
            return [
                replace(d, class_name="green" if d.class_name == "red" else "red")
                for d in detections
            ]

        monkeypatch.setattr(gateway_module, "emulate_sign_detections", flipped_color_emulate)

        # ``sign.color`` is always the untouched ground-truth metadata color
        # (SignRouter._signs is never mutated); ``color`` is whatever
        # deform_waypoint() actually decided to use. Comparing the two per
        # call — rather than comparing global color sets — stays correct even
        # when a scenario's two signs have different ground-truth colors.
        used_pairs: list[tuple[str, str]] = []
        original_apply = sign_router_module._apply_deformation

        def spying_apply_deformation(waypoint, sign, color, corridor, direction, lateral_offset):
            used_pairs.append((sign.color, color))
            return original_apply(waypoint, sign, color, corridor, direction, lateral_offset)

        monkeypatch.setattr(sign_router_module, "_apply_deformation", spying_apply_deformation)

        result = ScenarioSimulator(
            scenario.metadata, num_laps=scenario.laps, seed=scenario.seed,
            emit_vision_detections=True,
        ).run(max_steps=_MAX_STEPS)

        assert not result.collided, scenario.label
        assert used_pairs, "sign never engaged — nothing to prove the override with"
        # Activation is distance-only (not FOV-gated), so a sign can be
        # "engaged" while briefly outside the camera's cone — deform_waypoint()
        # correctly falls back to ground truth on those ticks. What matters is
        # that the override actually won at least once during the run.
        overridden = [(gt, eff) for gt, eff in used_pairs if eff != gt]
        assert overridden, (
            f"camera detection never overrode ground-truth color in this run: {used_pairs[:10]}"
        )
