// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: autoannotator/v1/compute.proto

// Package autoannotator.v1 is the language-neutral contract between the Go
// orchestration API (gRPC client) and the Python compute workers (gRPC servers).
// The workers own all ML compute (SAM inference, albumentations augmentation,
// Ultralytics YOLO training); the Go API owns the SQLite manifest DB.
//
// This is the single source of truth shared by both services. Each side vendors
// its own generated stubs: Go in api/internal/compute/pb, Python in
// backend/src/grpc_server/pb.

package computev1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A normalized 2-D point in the range [0, 1].
type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// A click point sent for SAM inference.
type ClickPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y         float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	PointType string  `protobuf:"bytes,3,opt,name=point_type,json=pointType,proto3" json:"point_type,omitempty"` // "positive" | "negative"
	ClassName string  `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
}

func (x *ClickPoint) Reset() {
	*x = ClickPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickPoint) ProtoMessage() {}

func (x *ClickPoint) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickPoint.ProtoReflect.Descriptor instead.
func (*ClickPoint) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{1}
}

func (x *ClickPoint) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClickPoint) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClickPoint) GetPointType() string {
	if x != nil {
		return x.PointType
	}
	return ""
}

func (x *ClickPoint) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

// A mask/bounding-box annotation returned by inference.
type Shape struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassName string   `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Points    []*Point `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *Shape) Reset() {
	*x = Shape{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shape) ProtoMessage() {}

func (x *Shape) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shape.ProtoReflect.Descriptor instead.
func (*Shape) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{2}
}

func (x *Shape) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shape) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Shape) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type SegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageId    int64         `protobuf:"varint,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImagePath  string        `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"` // absolute path on the shared filesystem
	Points     []*ClickPoint `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	ClassNames []string      `protobuf:"bytes,4,rep,name=class_names,json=classNames,proto3" json:"class_names,omitempty"` // valid class names (index = YOLO class id)
}

func (x *SegmentRequest) Reset() {
	*x = SegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRequest) ProtoMessage() {}

func (x *SegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRequest.ProtoReflect.Descriptor instead.
func (*SegmentRequest) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentRequest) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *SegmentRequest) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *SegmentRequest) GetPoints() []*ClickPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *SegmentRequest) GetClassNames() []string {
	if x != nil {
		return x.ClassNames
	}
	return nil
}

type SegmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State   string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "ready" | "error"
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Shapes  []*Shape `protobuf:"bytes,3,rep,name=shapes,proto3" json:"shapes,omitempty"`
}

func (x *SegmentResponse) Reset() {
	*x = SegmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentResponse) ProtoMessage() {}

func (x *SegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentResponse.ProtoReflect.Descriptor instead.
func (*SegmentResponse) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SegmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SegmentResponse) GetShapes() []*Shape {
	if x != nil {
		return x.Shapes
	}
	return nil
}

// An augmented image produced by the worker. The worker writes the files; the
// Go API inserts the corresponding DB row (single DB writer).
type AugmentedImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FormatUsed string `protobuf:"bytes,2,opt,name=format_used,json=formatUsed,proto3" json:"format_used,omitempty"` // "seg" | "det"
	ParentId   int64  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
}

func (x *AugmentedImage) Reset() {
	*x = AugmentedImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AugmentedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AugmentedImage) ProtoMessage() {}

func (x *AugmentedImage) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AugmentedImage.ProtoReflect.Descriptor instead.
func (*AugmentedImage) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{5}
}

func (x *AugmentedImage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AugmentedImage) GetFormatUsed() string {
	if x != nil {
		return x.FormatUsed
	}
	return ""
}

func (x *AugmentedImage) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type JobProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   string  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "running" | "completed" | "failed"
	Message  string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stage    string  `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Progress float64 `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 - 1.0
	Details  string  `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`     // free-form JSON (epoch/loss/map for training, counts for augment)
	Finished bool    `protobuf:"varint,6,opt,name=finished,proto3" json:"finished,omitempty"`
	Error    string  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// Set on augmentation progress events as copies are created, so the Go API can
	// persist them. Empty for training.
	Augmented *AugmentedImage `protobuf:"bytes,8,opt,name=augmented,proto3" json:"augmented,omitempty"`
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{6}
}

func (x *JobProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *JobProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *JobProgress) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *JobProgress) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *JobProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobProgress) GetAugmented() *AugmentedImage {
	if x != nil {
		return x.Augmented
	}
	return nil
}

// A source image to augment. The Go API resolves these from the DB (the single
// DB owner) so the worker only touches the filesystem.
type AugmentSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageId    int64  `protobuf:"varint,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Path       string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FormatUsed string `protobuf:"bytes,3,opt,name=format_used,json=formatUsed,proto3" json:"format_used,omitempty"` // "seg" | "det"
}

func (x *AugmentSource) Reset() {
	*x = AugmentSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AugmentSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AugmentSource) ProtoMessage() {}

func (x *AugmentSource) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AugmentSource.ProtoReflect.Descriptor instead.
func (*AugmentSource) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{7}
}

func (x *AugmentSource) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *AugmentSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AugmentSource) GetFormatUsed() string {
	if x != nil {
		return x.FormatUsed
	}
	return ""
}

type AugmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources          []*AugmentSource `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	NumAugmentations int32            `protobuf:"varint,2,opt,name=num_augmentations,json=numAugmentations,proto3" json:"num_augmentations,omitempty"`
}

func (x *AugmentRequest) Reset() {
	*x = AugmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AugmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AugmentRequest) ProtoMessage() {}

func (x *AugmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AugmentRequest.ProtoReflect.Descriptor instead.
func (*AugmentRequest) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{8}
}

func (x *AugmentRequest) GetSources() []*AugmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *AugmentRequest) GetNumAugmentations() int32 {
	if x != nil {
		return x.NumAugmentations
	}
	return 0
}

type TrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelName    string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Epochs       int32  `protobuf:"varint,2,opt,name=epochs,proto3" json:"epochs,omitempty"`
	Batch        int32  `protobuf:"varint,3,opt,name=batch,proto3" json:"batch,omitempty"`
	Imgsz        int32  `protobuf:"varint,4,opt,name=imgsz,proto3" json:"imgsz,omitempty"`
	DataYamlPath string `protobuf:"bytes,5,opt,name=data_yaml_path,json=dataYamlPath,proto3" json:"data_yaml_path,omitempty"` // absolute path to the Go-generated data.yaml
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autoannotator_v1_compute_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoannotator_v1_compute_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_autoannotator_v1_compute_proto_rawDescGZIP(), []int{9}
}

func (x *TrainRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *TrainRequest) GetEpochs() int32 {
	if x != nil {
		return x.Epochs
	}
	return 0
}

func (x *TrainRequest) GetBatch() int32 {
	if x != nil {
		return x.Batch
	}
	return 0
}

func (x *TrainRequest) GetImgsz() int32 {
	if x != nil {
		return x.Imgsz
	}
	return 0
}

func (x *TrainRequest) GetDataYamlPath() string {
	if x != nil {
		return x.DataYamlPath
	}
	return ""
}

var File_autoannotator_v1_compute_proto protoreflect.FileDescriptor

var file_autoannotator_v1_compute_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x66, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x63, 0x6b,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x67, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x34, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x0f,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2f, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x06, 0x73, 0x68, 0x61, 0x70, 0x65, 0x73,
	0x22, 0x62, 0x0a, 0x0e, 0x41, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0xfd, 0x01, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x3e, 0x0a, 0x09, 0x61, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x65,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x09, 0x61, 0x75, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x65, 0x64, 0x22, 0x5f, 0x0a, 0x0d, 0x41, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x5f, 0x75,
	0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x64, 0x22, 0x78, 0x0a, 0x0e, 0x41, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x5f, 0x61, 0x75, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x6e,
	0x75, 0x6d, 0x41, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x97, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6d, 0x67, 0x73, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6d,
	0x67, 0x73, 0x7a, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x79, 0x61, 0x6d, 0x6c,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x61, 0x74,
	0x61, 0x59, 0x61, 0x6d, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x32, 0x65, 0x0a, 0x13, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4e, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x61, 0x75,
	0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x6b, 0x0a, 0x13, 0x41, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x41, 0x75,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x61, 0x75, 0x74,
	0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61,
	0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4a, 0x6f, 0x62, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x30, 0x01, 0x32, 0x61, 0x0a,
	0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4e, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12,
	0x1e, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x30, 0x01,
	0x42, 0x67, 0x5a, 0x65, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x65, 0x61, 0x6d, 0x76, 0x6f, 0x6c, 0x64, 0x65, 0x6d, 0x6f, 0x72, 0x2f, 0x76, 0x6f, 0x6c, 0x64,
	0x65, 0x6d, 0x6f, 0x72, 0x62, 0x6f, 0x74, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x2d, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x61,
	0x75, 0x74, 0x6f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x3b,
	0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_autoannotator_v1_compute_proto_rawDescOnce sync.Once
	file_autoannotator_v1_compute_proto_rawDescData = file_autoannotator_v1_compute_proto_rawDesc
)

func file_autoannotator_v1_compute_proto_rawDescGZIP() []byte {
	file_autoannotator_v1_compute_proto_rawDescOnce.Do(func() {
		file_autoannotator_v1_compute_proto_rawDescData = protoimpl.X.CompressGZIP(file_autoannotator_v1_compute_proto_rawDescData)
	})
	return file_autoannotator_v1_compute_proto_rawDescData
}

var file_autoannotator_v1_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_autoannotator_v1_compute_proto_goTypes = []interface{}{
	(*Point)(nil),           // 0: autoannotator.v1.Point
	(*ClickPoint)(nil),      // 1: autoannotator.v1.ClickPoint
	(*Shape)(nil),           // 2: autoannotator.v1.Shape
	(*SegmentRequest)(nil),  // 3: autoannotator.v1.SegmentRequest
	(*SegmentResponse)(nil), // 4: autoannotator.v1.SegmentResponse
	(*AugmentedImage)(nil),  // 5: autoannotator.v1.AugmentedImage
	(*JobProgress)(nil),     // 6: autoannotator.v1.JobProgress
	(*AugmentSource)(nil),   // 7: autoannotator.v1.AugmentSource
	(*AugmentRequest)(nil),  // 8: autoannotator.v1.AugmentRequest
	(*TrainRequest)(nil),    // 9: autoannotator.v1.TrainRequest
}
var file_autoannotator_v1_compute_proto_depIdxs = []int32{
	0, // 0: autoannotator.v1.Shape.points:type_name -> autoannotator.v1.Point
	1, // 1: autoannotator.v1.SegmentRequest.points:type_name -> autoannotator.v1.ClickPoint
	2, // 2: autoannotator.v1.SegmentResponse.shapes:type_name -> autoannotator.v1.Shape
	5, // 3: autoannotator.v1.JobProgress.augmented:type_name -> autoannotator.v1.AugmentedImage
	7, // 4: autoannotator.v1.AugmentRequest.sources:type_name -> autoannotator.v1.AugmentSource
	3, // 5: autoannotator.v1.SegmentationService.Segment:input_type -> autoannotator.v1.SegmentRequest
	8, // 6: autoannotator.v1.AugmentationService.RunAugmentation:input_type -> autoannotator.v1.AugmentRequest
	9, // 7: autoannotator.v1.TrainingService.RunTraining:input_type -> autoannotator.v1.TrainRequest
	4, // 8: autoannotator.v1.SegmentationService.Segment:output_type -> autoannotator.v1.SegmentResponse
	6, // 9: autoannotator.v1.AugmentationService.RunAugmentation:output_type -> autoannotator.v1.JobProgress
	6, // 10: autoannotator.v1.TrainingService.RunTraining:output_type -> autoannotator.v1.JobProgress
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_autoannotator_v1_compute_proto_init() }
func file_autoannotator_v1_compute_proto_init() {
	if File_autoannotator_v1_compute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_autoannotator_v1_compute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shape); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AugmentedImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AugmentSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AugmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autoannotator_v1_compute_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_autoannotator_v1_compute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_autoannotator_v1_compute_proto_goTypes,
		DependencyIndexes: file_autoannotator_v1_compute_proto_depIdxs,
		MessageInfos:      file_autoannotator_v1_compute_proto_msgTypes,
	}.Build()
	File_autoannotator_v1_compute_proto = out.File
	file_autoannotator_v1_compute_proto_rawDesc = nil
	file_autoannotator_v1_compute_proto_goTypes = nil
	file_autoannotator_v1_compute_proto_depIdxs = nil
}
