# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compute_pb2 as compute__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SegmentationServiceStub:
    """SAM point-prompted segmentation. Stateless: every call carries all points.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Segment = channel.unary_unary(
                '/autoannotator.v1.SegmentationService/Segment',
                request_serializer=compute__pb2.SegmentRequest.SerializeToString,
                response_deserializer=compute__pb2.SegmentResponse.FromString,
                _registered_method=True)


class SegmentationServiceServicer:
    """SAM point-prompted segmentation. Stateless: every call carries all points.
    """

    def Segment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Segment': grpc.unary_unary_rpc_method_handler(
                    servicer.Segment,
                    request_deserializer=compute__pb2.SegmentRequest.FromString,
                    response_serializer=compute__pb2.SegmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoannotator.v1.SegmentationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoannotator.v1.SegmentationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SegmentationService:
    """SAM point-prompted segmentation. Stateless: every call carries all points.
    """

    @staticmethod
    def Segment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoannotator.v1.SegmentationService/Segment',
            compute__pb2.SegmentRequest.SerializeToString,
            compute__pb2.SegmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AugmentationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAugmentation = channel.unary_stream(
                '/autoannotator.v1.AugmentationService/RunAugmentation',
                request_serializer=compute__pb2.AugmentRequest.SerializeToString,
                response_deserializer=compute__pb2.JobProgress.FromString,
                _registered_method=True)


class AugmentationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunAugmentation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AugmentationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAugmentation': grpc.unary_stream_rpc_method_handler(
                    servicer.RunAugmentation,
                    request_deserializer=compute__pb2.AugmentRequest.FromString,
                    response_serializer=compute__pb2.JobProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoannotator.v1.AugmentationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoannotator.v1.AugmentationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AugmentationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAugmentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/autoannotator.v1.AugmentationService/RunAugmentation',
            compute__pb2.AugmentRequest.SerializeToString,
            compute__pb2.JobProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrainingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTraining = channel.unary_stream(
                '/autoannotator.v1.TrainingService/RunTraining',
                request_serializer=compute__pb2.TrainRequest.SerializeToString,
                response_deserializer=compute__pb2.JobProgress.FromString,
                _registered_method=True)


class TrainingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTraining': grpc.unary_stream_rpc_method_handler(
                    servicer.RunTraining,
                    request_deserializer=compute__pb2.TrainRequest.FromString,
                    response_serializer=compute__pb2.JobProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoannotator.v1.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoannotator.v1.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/autoannotator.v1.TrainingService/RunTraining',
            compute__pb2.TrainRequest.SerializeToString,
            compute__pb2.JobProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
