// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/ui/v1/button_event.proto

package uiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind mirrors internal/driver/button.Kind exactly (see that type's doc
// comment for what triggers each value).
type ButtonEvent_Kind int32

const (
	ButtonEvent_KIND_UNSPECIFIED    ButtonEvent_Kind = 0
	ButtonEvent_KIND_PRESSED        ButtonEvent_Kind = 1
	ButtonEvent_KIND_LONG_PRESS     ButtonEvent_Kind = 2
	ButtonEvent_KIND_SHUTDOWN_PRESS ButtonEvent_Kind = 3
	ButtonEvent_KIND_SHORT_PRESS    ButtonEvent_Kind = 4
	ButtonEvent_KIND_RELEASED       ButtonEvent_Kind = 5
)

// Enum value maps for ButtonEvent_Kind.
var (
	ButtonEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_PRESSED",
		2: "KIND_LONG_PRESS",
		3: "KIND_SHUTDOWN_PRESS",
		4: "KIND_SHORT_PRESS",
		5: "KIND_RELEASED",
	}
	ButtonEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":    0,
		"KIND_PRESSED":        1,
		"KIND_LONG_PRESS":     2,
		"KIND_SHUTDOWN_PRESS": 3,
		"KIND_SHORT_PRESS":    4,
		"KIND_RELEASED":       5,
	}
)

func (x ButtonEvent_Kind) Enum() *ButtonEvent_Kind {
	p := new(ButtonEvent_Kind)
	*p = x
	return p
}

func (x ButtonEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_ui_v1_button_event_proto_enumTypes[0].Descriptor()
}

func (ButtonEvent_Kind) Type() protoreflect.EnumType {
	return &file_vtitan_ui_v1_button_event_proto_enumTypes[0]
}

func (x ButtonEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonEvent_Kind.Descriptor instead.
func (ButtonEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_ui_v1_button_event_proto_rawDescGZIP(), []int{0, 0}
}

// ButtonEvent is one debounced button transition, matching
// internal/driver/button.Event (the Go analog of
// platform/robot/src/hardware/button/event.py's ButtonEvent). Published on
// the `vtitan.ui.v1.button_event` NATS subject by cmd/pi-zero's physical
// button driver, and by anything (e.g. a future backend-command dispatcher)
// synthesizing a button press remotely -- both producers publish to the
// same subject so a consumer (the state machine) treats a physical and a
// synthetic press identically, exactly as command_channel.py's
// `_dispatch_button_event` does today by publishing onto the same
// `/button/event` topic the physical driver uses.
type ButtonEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Stamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Kind  ButtonEvent_Kind       `protobuf:"varint,2,opt,name=kind,proto3,enum=vtitan.ui.v1.ButtonEvent_Kind" json:"kind,omitempty"`
	// How long the button had been held, in seconds, at the moment this
	// event fired. Zero for KIND_PRESSED, matching Event.HeldSec.
	HeldSec       float64 `protobuf:"fixed64,3,opt,name=held_sec,json=heldSec,proto3" json:"held_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonEvent) Reset() {
	*x = ButtonEvent{}
	mi := &file_vtitan_ui_v1_button_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonEvent) ProtoMessage() {}

func (x *ButtonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_ui_v1_button_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonEvent.ProtoReflect.Descriptor instead.
func (*ButtonEvent) Descriptor() ([]byte, []int) {
	return file_vtitan_ui_v1_button_event_proto_rawDescGZIP(), []int{0}
}

func (x *ButtonEvent) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *ButtonEvent) GetKind() ButtonEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return ButtonEvent_KIND_UNSPECIFIED
}

func (x *ButtonEvent) GetHeldSec() float64 {
	if x != nil {
		return x.HeldSec
	}
	return 0
}

var File_vtitan_ui_v1_button_event_proto protoreflect.FileDescriptor

const file_vtitan_ui_v1_button_event_proto_rawDesc = "" +
	"\n" +
	"\x1fvtitan/ui/v1/button_event.proto\x12\fvtitan.ui.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\vButtonEvent\x120\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05stamp\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.vtitan.ui.v1.ButtonEvent.KindR\x04kind\x12\x19\n" +
	"\bheld_sec\x18\x03 \x01(\x01R\aheldSec\"\x85\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fKIND_PRESSED\x10\x01\x12\x13\n" +
	"\x0fKIND_LONG_PRESS\x10\x02\x12\x17\n" +
	"\x13KIND_SHUTDOWN_PRESS\x10\x03\x12\x14\n" +
	"\x10KIND_SHORT_PRESS\x10\x04\x12\x11\n" +
	"\rKIND_RELEASED\x10\x05BJZHgithub.com/teamvoltimor/vtitan/platform/robot-go/internal/schema/pb/uiv1b\x06proto3"

var (
	file_vtitan_ui_v1_button_event_proto_rawDescOnce sync.Once
	file_vtitan_ui_v1_button_event_proto_rawDescData []byte
)

func file_vtitan_ui_v1_button_event_proto_rawDescGZIP() []byte {
	file_vtitan_ui_v1_button_event_proto_rawDescOnce.Do(func() {
		file_vtitan_ui_v1_button_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_ui_v1_button_event_proto_rawDesc), len(file_vtitan_ui_v1_button_event_proto_rawDesc)))
	})
	return file_vtitan_ui_v1_button_event_proto_rawDescData
}

var file_vtitan_ui_v1_button_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vtitan_ui_v1_button_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_ui_v1_button_event_proto_goTypes = []any{
	(ButtonEvent_Kind)(0),         // 0: vtitan.ui.v1.ButtonEvent.Kind
	(*ButtonEvent)(nil),           // 1: vtitan.ui.v1.ButtonEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_vtitan_ui_v1_button_event_proto_depIdxs = []int32{
	2, // 0: vtitan.ui.v1.ButtonEvent.stamp:type_name -> google.protobuf.Timestamp
	0, // 1: vtitan.ui.v1.ButtonEvent.kind:type_name -> vtitan.ui.v1.ButtonEvent.Kind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vtitan_ui_v1_button_event_proto_init() }
func file_vtitan_ui_v1_button_event_proto_init() {
	if File_vtitan_ui_v1_button_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_ui_v1_button_event_proto_rawDesc), len(file_vtitan_ui_v1_button_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_ui_v1_button_event_proto_goTypes,
		DependencyIndexes: file_vtitan_ui_v1_button_event_proto_depIdxs,
		EnumInfos:         file_vtitan_ui_v1_button_event_proto_enumTypes,
		MessageInfos:      file_vtitan_ui_v1_button_event_proto_msgTypes,
	}.Build()
	File_vtitan_ui_v1_button_event_proto = out.File
	file_vtitan_ui_v1_button_event_proto_goTypes = nil
	file_vtitan_ui_v1_button_event_proto_depIdxs = nil
}
