// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/sensor/v1/camera.proto

package sensorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CameraFrame is one raw (un-annotated) camera frame, published on the
// `vtitan.sensor.v1.camera` NATS subject. It is the Go analog of the ROS2
// /camera/image_raw topic, and the `camera_source = "topic"` input path the
// Python VisionNode supports (config/hardware/vision/node.toml) -- so a Go
// capture-node can consume the same frames the ROS2 pipeline produces, without
// touching the CSI device directly.
type CameraFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replaces ROS2 Header: stamp + frame_id.
	Stamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FrameId string                 `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// Pixel layout. Encoded as contiguous rows of `width` x `height` pixels,
	// each pixel `stride` bytes, in the channel order `encoding` names.
	Width  uint32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Stride uint32 `protobuf:"varint,5,opt,name=stride,proto3" json:"stride,omitempty"`
	// Channel encoding, e.g. "rgb8", "bgr8", "yuv422". Mirrors sensor_msgs/Image
	// encoding names so a ROS2 bridge can forward frames without transcoding.
	Encoding string `protobuf:"bytes,6,opt,name=encoding,proto3" json:"encoding,omitempty"`
	// Raw pixel buffer (length = height * stride). No compression; the recorder
	// encodes to mp4/jpg at write time, matching Python's "capture raw, encode
	// later" split (dataset_capture.py writes the raw rgb; video_recorder.py
	// encodes annotated frames).
	Data          []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraFrame) Reset() {
	*x = CameraFrame{}
	mi := &file_vtitan_sensor_v1_camera_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraFrame) ProtoMessage() {}

func (x *CameraFrame) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_sensor_v1_camera_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraFrame.ProtoReflect.Descriptor instead.
func (*CameraFrame) Descriptor() ([]byte, []int) {
	return file_vtitan_sensor_v1_camera_proto_rawDescGZIP(), []int{0}
}

func (x *CameraFrame) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *CameraFrame) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *CameraFrame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CameraFrame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CameraFrame) GetStride() uint32 {
	if x != nil {
		return x.Stride
	}
	return 0
}

func (x *CameraFrame) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *CameraFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_vtitan_sensor_v1_camera_proto protoreflect.FileDescriptor

const file_vtitan_sensor_v1_camera_proto_rawDesc = "" +
	"\n" +
	"\x1dvtitan/sensor/v1/camera.proto\x12\x10vtitan.sensor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n" +
	"\vCameraFrame\x120\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05stamp\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\tR\aframeId\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x16\n" +
	"\x06stride\x18\x05 \x01(\rR\x06stride\x12\x1a\n" +
	"\bencoding\x18\x06 \x01(\tR\bencoding\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04dataBCZAgithub.com/teamvoltimor/vtitan/src/go/internal/schema/pb/sensorv1b\x06proto3"

var (
	file_vtitan_sensor_v1_camera_proto_rawDescOnce sync.Once
	file_vtitan_sensor_v1_camera_proto_rawDescData []byte
)

func file_vtitan_sensor_v1_camera_proto_rawDescGZIP() []byte {
	file_vtitan_sensor_v1_camera_proto_rawDescOnce.Do(func() {
		file_vtitan_sensor_v1_camera_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_sensor_v1_camera_proto_rawDesc), len(file_vtitan_sensor_v1_camera_proto_rawDesc)))
	})
	return file_vtitan_sensor_v1_camera_proto_rawDescData
}

var file_vtitan_sensor_v1_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_sensor_v1_camera_proto_goTypes = []any{
	(*CameraFrame)(nil),           // 0: vtitan.sensor.v1.CameraFrame
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_vtitan_sensor_v1_camera_proto_depIdxs = []int32{
	1, // 0: vtitan.sensor.v1.CameraFrame.stamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vtitan_sensor_v1_camera_proto_init() }
func file_vtitan_sensor_v1_camera_proto_init() {
	if File_vtitan_sensor_v1_camera_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_sensor_v1_camera_proto_rawDesc), len(file_vtitan_sensor_v1_camera_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_sensor_v1_camera_proto_goTypes,
		DependencyIndexes: file_vtitan_sensor_v1_camera_proto_depIdxs,
		MessageInfos:      file_vtitan_sensor_v1_camera_proto_msgTypes,
	}.Build()
	File_vtitan_sensor_v1_camera_proto = out.File
	file_vtitan_sensor_v1_camera_proto_goTypes = nil
	file_vtitan_sensor_v1_camera_proto_depIdxs = nil
}
