// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/sensor/v1/scan.proto

package sensorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scan mirrors sensor_msgs/LaserScan. Published on the
// `vtitan.sensor.v1.scan` NATS subject.
type Scan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replaces ROS2 Header: stamp + frame_id.
	Stamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FrameId string                 `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// Start angle of the scan [rad].
	AngleMin float32 `protobuf:"fixed32,3,opt,name=angle_min,json=angleMin,proto3" json:"angle_min,omitempty"`
	// End angle of the scan [rad].
	AngleMax float32 `protobuf:"fixed32,4,opt,name=angle_max,json=angleMax,proto3" json:"angle_max,omitempty"`
	// Angular distance between measurements [rad].
	AngleIncrement float32 `protobuf:"fixed32,5,opt,name=angle_increment,json=angleIncrement,proto3" json:"angle_increment,omitempty"`
	// Time between measurements [seconds].
	TimeIncrement float32 `protobuf:"fixed32,6,opt,name=time_increment,json=timeIncrement,proto3" json:"time_increment,omitempty"`
	// Time between scans [seconds].
	ScanTime float32 `protobuf:"fixed32,7,opt,name=scan_time,json=scanTime,proto3" json:"scan_time,omitempty"`
	// Minimum range value [m].
	RangeMin float32 `protobuf:"fixed32,8,opt,name=range_min,json=rangeMin,proto3" json:"range_min,omitempty"`
	// Maximum range value [m].
	RangeMax float32 `protobuf:"fixed32,9,opt,name=range_max,json=rangeMax,proto3" json:"range_max,omitempty"`
	// Range data [m]. Value < range_min or > range_max should be discarded.
	Ranges []float32 `protobuf:"fixed32,10,rep,packed,name=ranges,proto3" json:"ranges,omitempty"`
	// Intensity data. Units are device-specific; empty if not supported.
	Intensities   []float32 `protobuf:"fixed32,11,rep,packed,name=intensities,proto3" json:"intensities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan) Reset() {
	*x = Scan{}
	mi := &file_vtitan_sensor_v1_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_sensor_v1_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_vtitan_sensor_v1_scan_proto_rawDescGZIP(), []int{0}
}

func (x *Scan) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *Scan) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *Scan) GetAngleMin() float32 {
	if x != nil {
		return x.AngleMin
	}
	return 0
}

func (x *Scan) GetAngleMax() float32 {
	if x != nil {
		return x.AngleMax
	}
	return 0
}

func (x *Scan) GetAngleIncrement() float32 {
	if x != nil {
		return x.AngleIncrement
	}
	return 0
}

func (x *Scan) GetTimeIncrement() float32 {
	if x != nil {
		return x.TimeIncrement
	}
	return 0
}

func (x *Scan) GetScanTime() float32 {
	if x != nil {
		return x.ScanTime
	}
	return 0
}

func (x *Scan) GetRangeMin() float32 {
	if x != nil {
		return x.RangeMin
	}
	return 0
}

func (x *Scan) GetRangeMax() float32 {
	if x != nil {
		return x.RangeMax
	}
	return 0
}

func (x *Scan) GetRanges() []float32 {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *Scan) GetIntensities() []float32 {
	if x != nil {
		return x.Intensities
	}
	return nil
}

var File_vtitan_sensor_v1_scan_proto protoreflect.FileDescriptor

const file_vtitan_sensor_v1_scan_proto_rawDesc = "" +
	"\n" +
	"\x1bvtitan/sensor/v1/scan.proto\x12\x10vtitan.sensor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x02\n" +
	"\x04Scan\x120\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05stamp\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\tR\aframeId\x12\x1b\n" +
	"\tangle_min\x18\x03 \x01(\x02R\bangleMin\x12\x1b\n" +
	"\tangle_max\x18\x04 \x01(\x02R\bangleMax\x12'\n" +
	"\x0fangle_increment\x18\x05 \x01(\x02R\x0eangleIncrement\x12%\n" +
	"\x0etime_increment\x18\x06 \x01(\x02R\rtimeIncrement\x12\x1b\n" +
	"\tscan_time\x18\a \x01(\x02R\bscanTime\x12\x1b\n" +
	"\trange_min\x18\b \x01(\x02R\brangeMin\x12\x1b\n" +
	"\trange_max\x18\t \x01(\x02R\brangeMax\x12\x16\n" +
	"\x06ranges\x18\n" +
	" \x03(\x02R\x06ranges\x12 \n" +
	"\vintensities\x18\v \x03(\x02R\vintensitiesBNZLgithub.com/teamvoltimor/vtitan/platform/robot-go/internal/schema/pb/sensorv1b\x06proto3"

var (
	file_vtitan_sensor_v1_scan_proto_rawDescOnce sync.Once
	file_vtitan_sensor_v1_scan_proto_rawDescData []byte
)

func file_vtitan_sensor_v1_scan_proto_rawDescGZIP() []byte {
	file_vtitan_sensor_v1_scan_proto_rawDescOnce.Do(func() {
		file_vtitan_sensor_v1_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_sensor_v1_scan_proto_rawDesc), len(file_vtitan_sensor_v1_scan_proto_rawDesc)))
	})
	return file_vtitan_sensor_v1_scan_proto_rawDescData
}

var file_vtitan_sensor_v1_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_sensor_v1_scan_proto_goTypes = []any{
	(*Scan)(nil),                  // 0: vtitan.sensor.v1.Scan
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_vtitan_sensor_v1_scan_proto_depIdxs = []int32{
	1, // 0: vtitan.sensor.v1.Scan.stamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vtitan_sensor_v1_scan_proto_init() }
func file_vtitan_sensor_v1_scan_proto_init() {
	if File_vtitan_sensor_v1_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_sensor_v1_scan_proto_rawDesc), len(file_vtitan_sensor_v1_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_sensor_v1_scan_proto_goTypes,
		DependencyIndexes: file_vtitan_sensor_v1_scan_proto_depIdxs,
		MessageInfos:      file_vtitan_sensor_v1_scan_proto_msgTypes,
	}.Build()
	File_vtitan_sensor_v1_scan_proto = out.File
	file_vtitan_sensor_v1_scan_proto_goTypes = nil
	file_vtitan_sensor_v1_scan_proto_depIdxs = nil
}
