// Package navigation provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package navigation

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for NavigationStatusPhase.
const (
	AVOIDING NavigationStatusPhase = "AVOIDING"
	ESCAPING NavigationStatusPhase = "ESCAPING"
	FINISHED NavigationStatusPhase = "FINISHED"
	PARKING  NavigationStatusPhase = "PARKING"
	TRACKING NavigationStatusPhase = "TRACKING"
)

// Valid indicates whether the value is a known member of the NavigationStatusPhase enum.
func (e NavigationStatusPhase) Valid() bool {
	switch e {
	case AVOIDING:
		return true
	case ESCAPING:
		return true
	case FINISHED:
		return true
	case PARKING:
		return true
	case TRACKING:
		return true
	default:
		return false
	}
}

// Defines values for NavigationStatusRiskLevel.
const (
	CRITICAL NavigationStatusRiskLevel = "CRITICAL"
	OBSTACLE NavigationStatusRiskLevel = "OBSTACLE"
	SAFE     NavigationStatusRiskLevel = "SAFE"
)

// Valid indicates whether the value is a known member of the NavigationStatusRiskLevel enum.
func (e NavigationStatusRiskLevel) Valid() bool {
	switch e {
	case CRITICAL:
		return true
	case OBSTACLE:
		return true
	case SAFE:
		return true
	default:
		return false
	}
}

// ClearanceData defines model for ClearanceData.
type ClearanceData struct {
	Back           *float64  `json:"back"`
	Front          *float64  `json:"front"`
	Left           *float64  `json:"left"`
	PointsCaptured *int      `json:"points_captured,omitempty"`
	RangeMax       *float64  `json:"range_max,omitempty"`
	RangeMin       *float64  `json:"range_min,omitempty"`
	Right          *float64  `json:"right"`
	Timestamp      time.Time `json:"timestamp"`
}

// CreateWaypointRequest defines model for CreateWaypointRequest.
type CreateWaypointRequest struct {
	Section   *string  `json:"section,omitempty"`
	Tolerance *float64 `json:"tolerance,omitempty"`
	X         float64  `binding:"required" json:"x"`
	Y         float64  `binding:"required" json:"y"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// NavigationStatus defines model for NavigationStatus.
type NavigationStatus struct {
	Active               bool                       `json:"active"`
	CurrentSection       *string                    `json:"current_section,omitempty"`
	CurrentWaypointIndex int                        `json:"current_waypoint_index"`
	LastReplan           *time.Time                 `json:"last_replan,omitempty"`
	Phase                *NavigationStatusPhase     `json:"phase,omitempty"`
	RiskLevel            *NavigationStatusRiskLevel `json:"risk_level,omitempty"`
	TotalWaypoints       int                        `json:"total_waypoints"`
}

// NavigationStatusPhase defines model for NavigationStatus.Phase.
type NavigationStatusPhase string

// NavigationStatusRiskLevel defines model for NavigationStatus.RiskLevel.
type NavigationStatusRiskLevel string

// NavigationTuning defines model for NavigationTuning.
type NavigationTuning struct {
	ContactDist     *float64 `json:"contact_dist,omitempty"`
	FastDist        *float64 `json:"fast_dist,omitempty"`
	LookaheadLong   *float64 `json:"lookahead_long,omitempty"`
	LookaheadShort  *float64 `json:"lookahead_short,omitempty"`
	MaxSpeed        *float64 `json:"max_speed,omitempty"`
	MaxSteeringRate *float64 `json:"max_steering_rate,omitempty"`
	MediumDist      *float64 `json:"medium_dist,omitempty"`
	MinSpeed        *float64 `json:"min_speed,omitempty"`
	SlowDist        *float64 `json:"slow_dist,omitempty"`
	SteerKp         *float64 `json:"steer_kp,omitempty"`
}

// PlanRouteRequest defines model for PlanRouteRequest.
type PlanRouteRequest struct {
	Laps     *int     `json:"laps,omitempty"`
	StartX   float64  `json:"start_x"`
	StartY   float64  `json:"start_y"`
	StartYaw *float64 `json:"start_yaw,omitempty"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// Route defines model for Route.
type Route struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// EstimatedDurationS Estimated duration in seconds
	EstimatedDurationS float64             `json:"estimated_duration_s"`
	Id                 *openapi_types.UUID `json:"id,omitempty"`

	// Laps Number of laps in the route
	Laps *int `json:"laps,omitempty"`

	// TotalDistance Total route distance in meters
	TotalDistance float64    `json:"total_distance"`
	Waypoints     []Waypoint `json:"waypoints"`
}

// Waypoint defines model for Waypoint.
type Waypoint struct {
	Id openapi_types.UUID `json:"id"`

	// Index Order in the waypoint sequence
	Index int `json:"index"`

	// Section Track section identifier
	Section *string `json:"section,omitempty"`

	// Tolerance Acceptance radius in meters
	Tolerance *float64 `json:"tolerance,omitempty"`

	// X X position in meters
	X float64 `json:"x"`

	// Y Y position in meters
	Y float64 `json:"y"`
}

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ProblemDetails

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// PlanRouteJSONRequestBody defines body for PlanRoute for application/json ContentType.
type PlanRouteJSONRequestBody = PlanRouteRequest

// UpdateTuningParamsJSONRequestBody defines body for UpdateTuningParams for application/json ContentType.
type UpdateTuningParamsJSONRequestBody = NavigationTuning

// CreateWaypointJSONRequestBody defines body for CreateWaypoint for application/json ContentType.
type CreateWaypointJSONRequestBody = CreateWaypointRequest
