// Code generated by `simgen generate-track-constants` from src/config/track.toml. DO NOT EDIT.

package simconfig

// Track dimensions (meters). Official WRO 2026 Future Engineers spec.
const (
	TrackMatSize     = 3.2
	TrackSize        = 3.0
	TrackMinCoord    = 0.0
	TrackMaxCoord    = 3.0
	TrackCenterCoord = 1.5
	TrackCornerMin   = 1.0
	TrackCornerMax   = 2.0
	TrackCornerSize  = 1.0
)

// Wall dimensions (meters).
const (
	WallHeight             = 0.1
	WallThickness          = 0.1
	WallCollisionThickness = 0.1
	WallExteriorOffset     = 0.05
	WallInteriorOffset     = 0.05
)

// Corridor widths (meters).
const (
	CorridorNarrow    = 0.6
	CorridorWide      = 1.0
	CorridorObstacles = 1.0
	CorridorMinWidth  = 0.5
	CorridorMaxWidth  = 1.5

	// Division lines painted across every corridor, out from the outer wall.
	CorridorDivOuter = 0.4
	CorridorDivInner = 0.6
	CorridorDivWidth = 0.2
)

// Traffic sign dimensions and grid positions (meters). WRO Spec 13.21-13.22.
const (
	SignWidth           = 0.05
	SignDepth           = 0.05
	SignHeight          = 0.1
	SignZPosition       = 0.05
	SignGridDepthNear   = 1.0
	SignGridDepthMiddle = 1.5
	SignGridDepthFar    = 2.0
	// Pillars stand on the corridor division lines.
	SignGridWidthOuter = 0.4
	SignGridWidthInner = 0.6
	// Circle each pillar is placed within. Nudging a pillar is legal; the run
	// stays valid while ANY corner of its square is still inside this circle.
	SignPlacementCircleDiameter = 0.085
	SignMinCount                = 6
	SignMaxCount                = 14
)

// Parking block dimensions (meters, obstacles challenge only).
const (
	ParkingLength        = 0.2
	ParkingWidth         = 0.02
	ParkingHeight        = 0.1
	ParkingZPosition     = 0.05
	ParkingWallOffset    = 0.1
	ParkingSpacingFactor = 1.5
)

// Starting zone dimensions (meters).
const (
	StartingZoneDefaultLength = 0.5
	// StartingZoneWidth is the middle band's width, used for the parking-derived
	// zone and the base template placeholder. Open Challenge zones are as wide as
	// whichever band their cell sits in -- see StartingZoneBandWidths.
	StartingZoneWidth           = 0.2
	StartingZoneThickness       = 0.001
	StartingZoneObstaclesFactor = 0.9
	StartingZoneIndicatorRadius = 0.035
)

// Along-corridor midpoints of the two starting cells in each band.
const (
	GridLengthSectionLeft  = 1.25
	GridLengthSectionRight = 1.75
)

var (
	// WallColor is the normalized RGB for all walls.
	WallColor = [3]float64{0.0, 0.0, 0.0}

	// SignColorRed is the official WRO red pillar color (RGB normalized).
	SignColorRed = [3]float64{0.933, 0.153, 0.216}

	// SignColorGreen is the official WRO green pillar color (RGB normalized).
	SignColorGreen = [3]float64{0.267, 0.839, 0.173}

	// SignColorRedStd is the per-channel stddev for red pillar color noise.
	SignColorRedStd = [3]float64{0.05, 0.02, 0.02}

	// SignColorGreenStd is the per-channel stddev for green pillar color noise.
	SignColorGreenStd = [3]float64{0.02, 0.05, 0.02}

	// ParkingColor is the magenta parking block color (RGB normalized).
	ParkingColor = [3]float64{1.0, 0.0, 1.0}

	// StartingZoneColor is the grey base rectangle color.
	StartingZoneColor = [3]float64{0.5, 0.5, 0.5}

	// StartingZoneClockwiseColor marks a clockwise round.
	StartingZoneClockwiseColor = [3]float64{0.2, 0.4, 1.0}

	// StartingZoneCounterClockwiseColor marks a counterclockwise round.
	StartingZoneCounterClockwiseColor = [3]float64{0.2, 1.0, 0.4}

	// StartingZoneBandWidths are the starting square's bands across the
	// corridor, measured out from the outer wall. Derived from the corridor
	// division lines: they are the widths those lines delimit.
	//
	// The band widths are what make the layout conditional. A band is a legal
	// start only while it lies inside the corridor, so a narrow corridor holds
	// only the outer bands and a wide one holds them all. See generate.StartCells.
	StartingZoneBandWidths = [...]float64{0.4, 0.2, 0.4}

	// StartingZoneSpawnOffsets are where the robot is placed inside each band,
	// out from the outer wall -- absolute metres, not fractions of the corridor.
	//
	// Derived by pushing the chassis flush against the band edge named in
	// track.toml's spawn_alignment, never centred: one band edge is a painted
	// line the robot can sit against harmlessly, the other may be the inner
	// block, so splitting the slack evenly would spend half the margin on the
	// line. Recomputed from the chassis width, so it follows a re-measurement.
	StartingZoneSpawnOffsets = [...]float64{0.303, 0.497, 0.697}
)
