// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/actuation/v1/ackermann_cmd.proto

package actuationv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AckermannCmd mirrors ackermann_msgs/AckermannDriveStamped. Published on
// the `vtitan.actuation.v1.ackermann_cmd` NATS subject. The motor node
// enforces its own deadline watchdog on this topic (no DDS DEADLINE QoS
// equivalent in NATS) — see go-migration-plan.md.
//
// protovalidate constraints here are deliberately structural (required,
// finite) rather than hardware-specific numeric bounds — the actual
// steering/speed limits live in platform/config/hardware/motors/
// motors.toml and haven't been reconciled into this schema yet. Do not
// invent bound values here; pull them from motors.toml when this gets
// wired to a real driver.
type AckermannCmd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replaces ROS2 Header: stamp + frame_id.
	Stamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FrameId string                 `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// Virtual bicycle-model steering angle [rad].
	SteeringAngle float32 `protobuf:"fixed32,3,opt,name=steering_angle,json=steeringAngle,proto3" json:"steering_angle,omitempty"`
	// Desired rate of change of steering angle [rad/s].
	SteeringAngleVelocity float32 `protobuf:"fixed32,4,opt,name=steering_angle_velocity,json=steeringAngleVelocity,proto3" json:"steering_angle_velocity,omitempty"`
	// Forward speed [m/s].
	Speed float32 `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
	// Desired acceleration [m/s^2].
	Acceleration float32 `protobuf:"fixed32,6,opt,name=acceleration,proto3" json:"acceleration,omitempty"`
	// Desired jerk [m/s^3].
	Jerk          float32 `protobuf:"fixed32,7,opt,name=jerk,proto3" json:"jerk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckermannCmd) Reset() {
	*x = AckermannCmd{}
	mi := &file_vtitan_actuation_v1_ackermann_cmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckermannCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckermannCmd) ProtoMessage() {}

func (x *AckermannCmd) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_actuation_v1_ackermann_cmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckermannCmd.ProtoReflect.Descriptor instead.
func (*AckermannCmd) Descriptor() ([]byte, []int) {
	return file_vtitan_actuation_v1_ackermann_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *AckermannCmd) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *AckermannCmd) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *AckermannCmd) GetSteeringAngle() float32 {
	if x != nil {
		return x.SteeringAngle
	}
	return 0
}

func (x *AckermannCmd) GetSteeringAngleVelocity() float32 {
	if x != nil {
		return x.SteeringAngleVelocity
	}
	return 0
}

func (x *AckermannCmd) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *AckermannCmd) GetAcceleration() float32 {
	if x != nil {
		return x.Acceleration
	}
	return 0
}

func (x *AckermannCmd) GetJerk() float32 {
	if x != nil {
		return x.Jerk
	}
	return 0
}

var File_vtitan_actuation_v1_ackermann_cmd_proto protoreflect.FileDescriptor

const file_vtitan_actuation_v1_ackermann_cmd_proto_rawDesc = "" +
	"\n" +
	"'vtitan/actuation/v1/ackermann_cmd.proto\x12\x13vtitan.actuation.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n" +
	"\fAckermannCmd\x128\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x05stamp\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\tR\aframeId\x12.\n" +
	"\x0esteering_angle\x18\x03 \x01(\x02B\a\xbaH\x04\n" +
	"\x02@\x01R\rsteeringAngle\x12?\n" +
	"\x17steering_angle_velocity\x18\x04 \x01(\x02B\a\xbaH\x04\n" +
	"\x02@\x01R\x15steeringAngleVelocity\x12\x1d\n" +
	"\x05speed\x18\x05 \x01(\x02B\a\xbaH\x04\n" +
	"\x02@\x01R\x05speed\x12+\n" +
	"\facceleration\x18\x06 \x01(\x02B\a\xbaH\x04\n" +
	"\x02@\x01R\facceleration\x12\x1b\n" +
	"\x04jerk\x18\a \x01(\x02B\a\xbaH\x04\n" +
	"\x02@\x01R\x04jerkBQZOgithub.com/teamvoltimor/vtitan/platform/robot-go/internal/schema/pb/actuationv1b\x06proto3"

var (
	file_vtitan_actuation_v1_ackermann_cmd_proto_rawDescOnce sync.Once
	file_vtitan_actuation_v1_ackermann_cmd_proto_rawDescData []byte
)

func file_vtitan_actuation_v1_ackermann_cmd_proto_rawDescGZIP() []byte {
	file_vtitan_actuation_v1_ackermann_cmd_proto_rawDescOnce.Do(func() {
		file_vtitan_actuation_v1_ackermann_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_actuation_v1_ackermann_cmd_proto_rawDesc), len(file_vtitan_actuation_v1_ackermann_cmd_proto_rawDesc)))
	})
	return file_vtitan_actuation_v1_ackermann_cmd_proto_rawDescData
}

var file_vtitan_actuation_v1_ackermann_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_actuation_v1_ackermann_cmd_proto_goTypes = []any{
	(*AckermannCmd)(nil),          // 0: vtitan.actuation.v1.AckermannCmd
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_vtitan_actuation_v1_ackermann_cmd_proto_depIdxs = []int32{
	1, // 0: vtitan.actuation.v1.AckermannCmd.stamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vtitan_actuation_v1_ackermann_cmd_proto_init() }
func file_vtitan_actuation_v1_ackermann_cmd_proto_init() {
	if File_vtitan_actuation_v1_ackermann_cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_actuation_v1_ackermann_cmd_proto_rawDesc), len(file_vtitan_actuation_v1_ackermann_cmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_actuation_v1_ackermann_cmd_proto_goTypes,
		DependencyIndexes: file_vtitan_actuation_v1_ackermann_cmd_proto_depIdxs,
		MessageInfos:      file_vtitan_actuation_v1_ackermann_cmd_proto_msgTypes,
	}.Build()
	File_vtitan_actuation_v1_ackermann_cmd_proto = out.File
	file_vtitan_actuation_v1_ackermann_cmd_proto_goTypes = nil
	file_vtitan_actuation_v1_ackermann_cmd_proto_depIdxs = nil
}
