// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/actuation/v1/joint_states.proto

package actuationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JointStates mirrors sensor_msgs/JointState. Published on the
// `vtitan.actuation.v1.joint_states` NATS subject.
type JointStates struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replaces ROS2 Header: stamp + frame_id.
	Stamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FrameId string                 `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// name[i] describes joint state at index i. position/velocity/effort
	// may be shorter than name if a joint doesn't report every field.
	Name          []string  `protobuf:"bytes,3,rep,name=name,proto3" json:"name,omitempty"`
	Position      []float64 `protobuf:"fixed64,4,rep,packed,name=position,proto3" json:"position,omitempty"`
	Velocity      []float64 `protobuf:"fixed64,5,rep,packed,name=velocity,proto3" json:"velocity,omitempty"`
	Effort        []float64 `protobuf:"fixed64,6,rep,packed,name=effort,proto3" json:"effort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JointStates) Reset() {
	*x = JointStates{}
	mi := &file_vtitan_actuation_v1_joint_states_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JointStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointStates) ProtoMessage() {}

func (x *JointStates) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_actuation_v1_joint_states_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointStates.ProtoReflect.Descriptor instead.
func (*JointStates) Descriptor() ([]byte, []int) {
	return file_vtitan_actuation_v1_joint_states_proto_rawDescGZIP(), []int{0}
}

func (x *JointStates) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *JointStates) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *JointStates) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *JointStates) GetPosition() []float64 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *JointStates) GetVelocity() []float64 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *JointStates) GetEffort() []float64 {
	if x != nil {
		return x.Effort
	}
	return nil
}

var File_vtitan_actuation_v1_joint_states_proto protoreflect.FileDescriptor

const file_vtitan_actuation_v1_joint_states_proto_rawDesc = "" +
	"\n" +
	"&vtitan/actuation/v1/joint_states.proto\x12\x13vtitan.actuation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\vJointStates\x120\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05stamp\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\tR\aframeId\x12\x12\n" +
	"\x04name\x18\x03 \x03(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x04 \x03(\x01R\bposition\x12\x1a\n" +
	"\bvelocity\x18\x05 \x03(\x01R\bvelocity\x12\x16\n" +
	"\x06effort\x18\x06 \x03(\x01R\x06effortBQZOgithub.com/teamvoltimor/vtitan/platform/robot-go/internal/schema/pb/actuationv1b\x06proto3"

var (
	file_vtitan_actuation_v1_joint_states_proto_rawDescOnce sync.Once
	file_vtitan_actuation_v1_joint_states_proto_rawDescData []byte
)

func file_vtitan_actuation_v1_joint_states_proto_rawDescGZIP() []byte {
	file_vtitan_actuation_v1_joint_states_proto_rawDescOnce.Do(func() {
		file_vtitan_actuation_v1_joint_states_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_actuation_v1_joint_states_proto_rawDesc), len(file_vtitan_actuation_v1_joint_states_proto_rawDesc)))
	})
	return file_vtitan_actuation_v1_joint_states_proto_rawDescData
}

var file_vtitan_actuation_v1_joint_states_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_actuation_v1_joint_states_proto_goTypes = []any{
	(*JointStates)(nil),           // 0: vtitan.actuation.v1.JointStates
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_vtitan_actuation_v1_joint_states_proto_depIdxs = []int32{
	1, // 0: vtitan.actuation.v1.JointStates.stamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vtitan_actuation_v1_joint_states_proto_init() }
func file_vtitan_actuation_v1_joint_states_proto_init() {
	if File_vtitan_actuation_v1_joint_states_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_actuation_v1_joint_states_proto_rawDesc), len(file_vtitan_actuation_v1_joint_states_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_actuation_v1_joint_states_proto_goTypes,
		DependencyIndexes: file_vtitan_actuation_v1_joint_states_proto_depIdxs,
		MessageInfos:      file_vtitan_actuation_v1_joint_states_proto_msgTypes,
	}.Build()
	File_vtitan_actuation_v1_joint_states_proto = out.File
	file_vtitan_actuation_v1_joint_states_proto_goTypes = nil
	file_vtitan_actuation_v1_joint_states_proto_depIdxs = nil
}
