// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package db

import (
	"context"
	"database/sql"
)

const getImageByID = `-- name: GetImageByID :one
SELECT id, path, status, format_used, updated_at, parent_id
FROM images
WHERE id = ? AND deleted_at IS NULL
`

type GetImageByIDRow struct {
	ID         int64
	Path       string
	Status     int64
	FormatUsed sql.NullString
	UpdatedAt  sql.NullString
	ParentID   sql.NullInt64
}

func (q *Queries) GetImageByID(ctx context.Context, id int64) (GetImageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i GetImageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Status,
		&i.FormatUsed,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const getStatusCounts = `-- name: GetStatusCounts :many
SELECT status, COUNT(*) AS cnt
FROM images
WHERE deleted_at IS NULL
GROUP BY status
`

type GetStatusCountsRow struct {
	Status int64
	Cnt    int64
}

func (q *Queries) GetStatusCounts(ctx context.Context) ([]GetStatusCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatusCountsRow{}
	for rows.Next() {
		var i GetStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAugmentedImage = `-- name: InsertAugmentedImage :exec
INSERT OR IGNORE INTO images (path, status, format_used, parent_id, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertAugmentedImageParams struct {
	Path       string
	Status     int64
	FormatUsed sql.NullString
	ParentID   sql.NullInt64
	UpdatedAt  sql.NullString
}

func (q *Queries) InsertAugmentedImage(ctx context.Context, arg InsertAugmentedImageParams) error {
	_, err := q.db.ExecContext(ctx, insertAugmentedImage,
		arg.Path,
		arg.Status,
		arg.FormatUsed,
		arg.ParentID,
		arg.UpdatedAt,
	)
	return err
}

const insertImageOrIgnore = `-- name: InsertImageOrIgnore :exec
INSERT OR IGNORE INTO images (path) VALUES (?)
`

func (q *Queries) InsertImageOrIgnore(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, insertImageOrIgnore, path)
	return err
}

const listGroupedImages = `-- name: ListGroupedImages :many
SELECT i.id, i.path, i.status, i.format_used, i.updated_at,
       COUNT(c.id) AS aug_count
FROM images i
LEFT JOIN images c ON c.parent_id = i.id AND c.deleted_at IS NULL
WHERE i.parent_id IS NULL AND i.deleted_at IS NULL
GROUP BY i.id
ORDER BY i.id ASC
`

type ListGroupedImagesRow struct {
	ID         int64
	Path       string
	Status     int64
	FormatUsed sql.NullString
	UpdatedAt  sql.NullString
	AugCount   int64
}

func (q *Queries) ListGroupedImages(ctx context.Context) ([]ListGroupedImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupedImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupedImagesRow{}
	for rows.Next() {
		var i ListGroupedImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Status,
			&i.FormatUsed,
			&i.UpdatedAt,
			&i.AugCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForBrowse = `-- name: ListImagesForBrowse :many
SELECT id, path, status, format_used, updated_at
FROM images
WHERE deleted_at IS NULL
ORDER BY id ASC
`

type ListImagesForBrowseRow struct {
	ID         int64
	Path       string
	Status     int64
	FormatUsed sql.NullString
	UpdatedAt  sql.NullString
}

func (q *Queries) ListImagesForBrowse(ctx context.Context) ([]ListImagesForBrowseRow, error) {
	rows, err := q.db.QueryContext(ctx, listImagesForBrowse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesForBrowseRow{}
	for rows.Next() {
		var i ListImagesForBrowseRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Status,
			&i.FormatUsed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImageDone = `-- name: MarkImageDone :exec
UPDATE images SET status = ?, format_used = ?, updated_at = ? WHERE id = ?
`

type MarkImageDoneParams struct {
	Status     int64
	FormatUsed sql.NullString
	UpdatedAt  sql.NullString
	ID         int64
}

func (q *Queries) MarkImageDone(ctx context.Context, arg MarkImageDoneParams) error {
	_, err := q.db.ExecContext(ctx, markImageDone,
		arg.Status,
		arg.FormatUsed,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const markImageSkipped = `-- name: MarkImageSkipped :exec
UPDATE images SET status = ?, updated_at = ? WHERE id = ?
`

type MarkImageSkippedParams struct {
	Status    int64
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) MarkImageSkipped(ctx context.Context, arg MarkImageSkippedParams) error {
	_, err := q.db.ExecContext(ctx, markImageSkipped, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteImage = `-- name: SoftDeleteImage :exec
UPDATE images SET deleted_at = ? WHERE id = ?
`

type SoftDeleteImageParams struct {
	DeletedAt sql.NullString
	ID        int64
}

func (q *Queries) SoftDeleteImage(ctx context.Context, arg SoftDeleteImageParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteImage, arg.DeletedAt, arg.ID)
	return err
}
