// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classes.sql

package db

import (
	"context"
)

const countClasses = `-- name: CountClasses :one
SELECT COUNT(*) FROM classes
`

func (q *Queries) CountClasses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClasses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertClassOrIgnore = `-- name: InsertClassOrIgnore :exec
INSERT OR IGNORE INTO classes (name, color) VALUES (?, ?)
`

type InsertClassOrIgnoreParams struct {
	Name  string
	Color string
}

func (q *Queries) InsertClassOrIgnore(ctx context.Context, arg InsertClassOrIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, insertClassOrIgnore, arg.Name, arg.Color)
	return err
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, color FROM classes ORDER BY id ASC
`

type ListClassesRow struct {
	ID    int64
	Name  string
	Color string
}

func (q *Queries) ListClasses(ctx context.Context) ([]ListClassesRow, error) {
	rows, err := q.db.QueryContext(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesRow{}
	for rows.Next() {
		var i ListClassesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClass = `-- name: UpsertClass :exec
INSERT INTO classes (name, color) VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET color = excluded.color
`

type UpsertClassParams struct {
	Name  string
	Color string
}

func (q *Queries) UpsertClass(ctx context.Context, arg UpsertClassParams) error {
	_, err := q.db.ExecContext(ctx, upsertClass, arg.Name, arg.Color)
	return err
}
