// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Class struct {
	ID        int64
	Name      string
	Color     string
	CreatedAt sql.NullString
}

type Image struct {
	ID         int64
	Path       string
	Status     int64
	FormatUsed sql.NullString
	ParentID   sql.NullInt64
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
	DeletedAt  sql.NullString
}
