// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vtitan/state/v1/robot_state.proto

package statev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State is the machine's current state. The cycle FINISHED -> BOOT_CHECK
// -> READY -> RACING can be driven purely by the physical button with no
// process restart, which is why consumers must treat every transition as
// possible rather than assuming a one-way progression.
type RobotState_State int32

const (
	RobotState_STATE_UNSPECIFIED RobotState_State = 0
	RobotState_STATE_BOOT_CHECK  RobotState_State = 1
	RobotState_STATE_READY       RobotState_State = 2
	RobotState_STATE_RACING      RobotState_State = 3
	RobotState_STATE_FINISHED    RobotState_State = 4
)

// Enum value maps for RobotState_State.
var (
	RobotState_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_BOOT_CHECK",
		2: "STATE_READY",
		3: "STATE_RACING",
		4: "STATE_FINISHED",
	}
	RobotState_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_BOOT_CHECK":  1,
		"STATE_READY":       2,
		"STATE_RACING":      3,
		"STATE_FINISHED":    4,
	}
)

func (x RobotState_State) Enum() *RobotState_State {
	p := new(RobotState_State)
	*p = x
	return p
}

func (x RobotState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RobotState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_vtitan_state_v1_robot_state_proto_enumTypes[0].Descriptor()
}

func (RobotState_State) Type() protoreflect.EnumType {
	return &file_vtitan_state_v1_robot_state_proto_enumTypes[0]
}

func (x RobotState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RobotState_State.Descriptor instead.
func (RobotState_State) EnumDescriptor() ([]byte, []int) {
	return file_vtitan_state_v1_robot_state_proto_rawDescGZIP(), []int{0, 0}
}

// RobotState is the Go-stack replacement for /robot_state, currently a
// std_msgs/String carrying the state name. Published on the
// `vtitan.state.v1.robot_state` NATS subject.
//
// Mirrors internal/statemachine/core's RobotState, which was ported from
// src/state_machine/core.py against its real 4-state machine and 8-rule
// transition table.
type RobotState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stamp         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	State         RobotState_State       `protobuf:"varint,2,opt,name=state,proto3,enum=vtitan.state.v1.RobotState_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotState) Reset() {
	*x = RobotState{}
	mi := &file_vtitan_state_v1_robot_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotState) ProtoMessage() {}

func (x *RobotState) ProtoReflect() protoreflect.Message {
	mi := &file_vtitan_state_v1_robot_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotState.ProtoReflect.Descriptor instead.
func (*RobotState) Descriptor() ([]byte, []int) {
	return file_vtitan_state_v1_robot_state_proto_rawDescGZIP(), []int{0}
}

func (x *RobotState) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *RobotState) GetState() RobotState_State {
	if x != nil {
		return x.State
	}
	return RobotState_STATE_UNSPECIFIED
}

var File_vtitan_state_v1_robot_state_proto protoreflect.FileDescriptor

const file_vtitan_state_v1_robot_state_proto_rawDesc = "" +
	"\n" +
	"!vtitan/state/v1/robot_state.proto\x12\x0fvtitan.state.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\n" +
	"RobotState\x128\n" +
	"\x05stamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x05stamp\x12A\n" +
	"\x05state\x18\x02 \x01(\x0e2!.vtitan.state.v1.RobotState.StateB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05state\"k\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATE_BOOT_CHECK\x10\x01\x12\x0f\n" +
	"\vSTATE_READY\x10\x02\x12\x10\n" +
	"\fSTATE_RACING\x10\x03\x12\x12\n" +
	"\x0eSTATE_FINISHED\x10\x04BBZ@github.com/teamvoltimor/vtitan/src/go/internal/schema/pb/statev1b\x06proto3"

var (
	file_vtitan_state_v1_robot_state_proto_rawDescOnce sync.Once
	file_vtitan_state_v1_robot_state_proto_rawDescData []byte
)

func file_vtitan_state_v1_robot_state_proto_rawDescGZIP() []byte {
	file_vtitan_state_v1_robot_state_proto_rawDescOnce.Do(func() {
		file_vtitan_state_v1_robot_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtitan_state_v1_robot_state_proto_rawDesc), len(file_vtitan_state_v1_robot_state_proto_rawDesc)))
	})
	return file_vtitan_state_v1_robot_state_proto_rawDescData
}

var file_vtitan_state_v1_robot_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vtitan_state_v1_robot_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vtitan_state_v1_robot_state_proto_goTypes = []any{
	(RobotState_State)(0),         // 0: vtitan.state.v1.RobotState.State
	(*RobotState)(nil),            // 1: vtitan.state.v1.RobotState
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_vtitan_state_v1_robot_state_proto_depIdxs = []int32{
	2, // 0: vtitan.state.v1.RobotState.stamp:type_name -> google.protobuf.Timestamp
	0, // 1: vtitan.state.v1.RobotState.state:type_name -> vtitan.state.v1.RobotState.State
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_vtitan_state_v1_robot_state_proto_init()
}
func file_vtitan_state_v1_robot_state_proto_init() {
	if File_vtitan_state_v1_robot_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtitan_state_v1_robot_state_proto_rawDesc), len(file_vtitan_state_v1_robot_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtitan_state_v1_robot_state_proto_goTypes,
		DependencyIndexes: file_vtitan_state_v1_robot_state_proto_depIdxs,
		EnumInfos:         file_vtitan_state_v1_robot_state_proto_enumTypes,
		MessageInfos:      file_vtitan_state_v1_robot_state_proto_msgTypes,
	}.Build()
	File_vtitan_state_v1_robot_state_proto = out.File
	file_vtitan_state_v1_robot_state_proto_goTypes = nil
	file_vtitan_state_v1_robot_state_proto_depIdxs = nil
}
